### ISSUE TITLE
内存占用高问题

### ISSUE THREAD

**Issue by Lan-megumi** [monkeyWie/proxyee-down#102]
今天打开软件去云盘下载多个文件，大小都在1G-4G不等
后面我就挂着chrome等下载，然后去干点别的事情
回来打算一边看电影一边等下载
结果启动个播放器启动了我半天
这个时候发现不对调出任务管理器发现内存占用已经上了90%
吓得我赶紧把任务一个一个停下来
--------------------
电脑是win10 1607  的，内存8G，没有固态
个人感觉和没固态多少有点关系
毕竟在任务管理器上看不到有占用内存超过1G的进程
反倒是 system 把我磁盘吃爆了 （一般10m/s就满了，多任务同时开启的时候飙到了60m/s）

另外比较好奇怎么和传统软件的下载方式不太一样，主要是拓展名这块
例如我要下载一个叫123.zip的文件
用迅雷的话文件拓展名是 .zip.（迅雷） 嵌套着的，然后我看了下文件夹那里都是 .zip 
习惯性以为已经下载好了

快过年了大佬也不容易，还记得的话就改进改进下

**Comment by monkeyWie** [comment]
内存的问题新版本会优化的

**Comment by Hoshinonyaruko** [comment]
我也是内存占用很高，win10，SSD，12G内存，同时进行任务超过5个内存就会飙到99%

**Comment by Lan-megumi** [comment]
发现了个很有意思的玩意
10g大的错误报告
存放在 proxy-down-2.1-windows-x64\main\log 路径下的一个文件

**Comment by monkeyWie** [comment]
@Lan-megumi 
2.1的bug 最新版2.21了你还没升级吗

**Comment by Lan-megumi** [comment]
自动更新停在97不动了
不知道最近怎么样，还没去试
