### ISSUE TITLE
能否加入开机自动启动，且启动时不自动弹出view页面

### ISSUE THREAD

**Issue by xiaoliu2012** [monkeyWie/proxyee-down#103]
如题
另外能否列表排列任务列表呢？
最后，感谢作者提供这么好用的软件

**Comment by monkeyWie** [comment]
开机自动启动可以自己把快捷方式脱到windows启动目录就好了，任务列表后期会出的

**Comment by xiaoliu2012** [comment]
我目前是快捷方式脱到windows启动目录 来实现开机启动的
但是 程序每次启动都要打开浏览器 打开view页面 比较讨厌呢
所以我在想 是不是能不能程序原生支持开机启动 然后来个气泡提示，程序已启动

**Comment by monkeyWie** [comment]
这个可以加个设置启动是否弹窗
