### ISSUE TITLE
用过一次后，感觉被封号了！

### ISSUE THREAD

**Issue by geek8514** [monkeyWie/proxyee-down#104]
用了一次这个后，百度云上什么东东西都下不了了，不用这个也下不了，就算没装过这软件的机器也下不了，感觉被封号了，太坑人了！

**Comment by zenghongtu** [comment]
我用了大半个月稳得一批，速度基本满宽带，是不是你用过其他三方软件，不然不会这样的。

**Comment by geek8514** [comment]
我就是上周用过一次这个后，百度云的东西全下下不了，点完没反应。刚才我把账号退出后，再点就能下了。。。

**Comment by geek8514** [comment]
等等，我又试了一下我的云盘，旧的文件可以下，新的不行，看来有可能是我这边百度的问题。再观察。。。

**Comment by Lan-megumi** [comment]
你可以换一个账号去下载你网盘的资源
我用我自己账号下（我的已经小黑屋了，不支持外链断点，卡下载速度）是很慢的，在这个软件里把分段数调高可能速度会相对快点
但是个人不建议那么做，建议你把账号注销了再去下载你网盘内的文件
