### ISSUE TITLE
下载视频文件后无法打开

### ISSUE THREAD

**Issue by nextisleo** [monkeyWie/proxyee-down#106]
我跟我同事都出现了下载的视频文件无法打开的问题
![image](https://user-images.githubusercontent.com/18329813/35852764-a8950f70-0b66-11e8-884d-bd7d29769c7a.png)

**Comment by monkeyWie** [comment]
后缀名不对？

**Comment by nextisleo** [comment]
没有。后缀名没问题，rmvb以及mkv的都打不开报这个错。播放器肯定是没有问题的。另外不知道是否设置不对经常出现无法启动插件下载的情况。我看bug列表并没有别人提出来，不过我跟同事的下载文件都是打不开的状况。

**Comment by monkeyWie** [comment]
下载器什么版本呢

**Comment by nextisleo** [comment]
目前2.1我更新下2.2的试试，thanks~

**Comment by monkeyWie** [comment]
@nextisleo 2.1的下载可能会文件损坏 2.11以上就好

**Comment by duduniao666** [comment]
我也更新下2.2的试试

**Comment by nextisleo** [comment]
![image](https://user-images.githubusercontent.com/18329813/35907628-701e5296-0c29-11e8-8d55-1bdf76961177.png)
 控制台第一条403是单文件下载，报错这个。
第二条error是两个文件下载
![image](https://user-images.githubusercontent.com/18329813/35907664-8b7f9428-0c29-11e8-967c-a11f0d2b3b42.png)
目前显示是插件应该使用正常。
嗅探模式选择的全局，选择百度云也不行。
刚刚更新2.2版本并且重新安装了证书。
不知道是哪里操作不对或者设置不对~

**Comment by monkeyWie** [comment]
@nextisleo  今天下午百度云抽风了
