### ISSUE TITLE
百度网盘合并文件解压模块不能用了

### ISSUE THREAD

**Issue by Hoshinonyaruko** [monkeyWie/proxyee-down#109]
今天有一个153gb的pack文件下载到99后任务失败了，10M的宽带磨磨蹭蹭下了7天不忍心删了重来，于是想着99%的下载完成度应该大部分文件已经下载下来了就试着用软件内置的解压程式解压看看，结果成了，153.7gb解压出来了153gb，不过找不到哪里没有解压成功..但是之后问题就发生了，我还有两个80多个G的pack要解压，但是文件解压模块不认了，直接说不是百度云合并下载压缩包，但是它们的确是从百度合并下载的啊....现在任何文件都不能解压了，求解，文件都大于4G，只能用解压模块解压啊

**Comment by Hoshinonyaruko** [comment]
那个部分下载的文件没有提示解压成功，就是不停地正在解压，我就把程序关掉了，之后再打开就彻底不能解压了

**Comment by monkeyWie** [comment]
用新版本再解压试试

**Comment by Hoshinonyaruko** [comment]
成了，遗憾的是有一个文件删了找不到了要重新下，不过新版本能解压了，谢谢！
