### ISSUE TITLE
能否在设置页面加入“自动解压”选项而不是在任务创建页面，如图

### ISSUE THREAD

**Issue by xiaoliu2012** [monkeyWie/proxyee-down#115]
每次建立任务的时候都要点一下关闭 自动解压 按钮 不是太合理
<a href="http://www.niupic.com/photo/1173045.html"><img src="http://i.niupic.com/images/2018/02/07/8uCGuo.png"></a>

**Comment by monkeyWie** [comment]
非百度云批量下载的勾了也不会解压的，没事
