### ISSUE TITLE
希望窗口大小可调

### ISSUE THREAD

**Issue by StLym** [monkeyWie/proxyee-down#117]
使用的21:9屏幕，软件界面默认最大化，一不小心移动了位置，怎么都无法恢复初始位置了。而且窗口大小不可调，也不能分屏。希望能解决一下。

**Comment by monkeyWie** [comment]
2.11可以调解窗口大小了，具体看更新日志：https://github.com/monkeyWie/proxyee-down/releases/tag/2.21
