### ISSUE TITLE
更新2.2后，无法写入内存盘。

### ISSUE THREAD

**Issue by raininmy** [monkeyWie/proxyee-down#118]
作者您好，您写的软件非常好用。但今天在更新2.2版本后，出现了“无权访问下载路径，请修改路径或开放目录权限”的提示，内存盘是用Primo Ramdisk Server Edition创建的虚拟盘，在内存盘里的用户中修改了完全控制权限后，还是不能写入，2.11（含）之前的版本则无问题。如能修复，感激不尽。

**Comment by monkeyWie** [comment]
你用管理员身份运行软件试试

**Comment by raininmy** [comment]
用管理员运行，也不行。

**Comment by monkeyWie** [comment]
先降级吧

**Comment by monkeyWie** [comment]
2.3已修复
