### ISSUE TITLE
几个小问题

### ISSUE THREAD

**Issue by Joyrocky** [monkeyWie/proxyee-down#119]
1.重复打开客户端报端口占用错误
2.打开应用内的一些站外链接建议使用默认浏览器跳转，不要应用内跳转，不然只有重启应用才能恢复初始界面。
3.左侧的同一button重复点击后应返回同一个view，而不应该出现多个相同界面。

**Comment by monkeyWie** [comment]
谢谢你的反馈。
1.没有问题，正常错误提示
2.这个问题会进行修复
3.没有问题，现在只有工具界面可以重复打开，因为工具是可以并行使用的
