### ISSUE TITLE
Ubuntu无法启动

### ISSUE THREAD

**Issue by blzsb** [monkeyWie/proxyee-down#122]
在终端下打开显示“错误: 找不到或无法加载主类 proxyee-down-core.jar”
OpenJDK版本1.8.0_151

**Comment by SamHz** [comment]
同求ubuntu怎么使用的教程

**Comment by monkeyWie** [comment]
@blzsb 什么版本

**Comment by blzsb** [comment]
@monkeyWie 
系统版本Ubuntu 16.04 LTS
JRE版本openjdk version "1.8.0_151"
OpenJDK Runtime Environment (build 1.8.0_151-8u151-b12-0ubuntu0.16.04.2-b12)
OpenJDK 64-Bit Server VM (build 25.151-b12, mixed mode)
proxyee-down版本2.21

**Comment by monkeyWie** [comment]
linux教程已出：https://github.com/monkeyWie/proxyee-down/blob/master/.guide/linux/read.md
