### ISSUE TITLE
下载速度不慢

### ISSUE THREAD

**Issue by 911061873** [monkeyWie/proxyee-down#123]
之前一直用的2.1，速度没问题。今天下载一个文件，速度刚建立任务的时候能到1MB/S左右，过不了多久就变成几十KB/S。以为老版本被和谐了，来项目主页下载新版本，升级到2.21之后问题依旧。
是不是要跟新了？
![image](https://user-images.githubusercontent.com/19637526/35964264-2f816560-0cf2-11e8-9aa1-f690cc548af0.png)
![image](https://user-images.githubusercontent.com/19637526/35964282-39a50560-0cf2-11e8-80f5-608d10424813.png)

**Comment by monkeyWie** [comment]
参考问题列表，下载速度慢的问题
https://github.com/monkeyWie/proxyee-down/blob/master/.guide/FAQ.md

**Comment by 911061873** [comment]
✌  解决了 多谢。
