### ISSUE TITLE
2.2版本无法续传

### ISSUE THREAD

**Issue by castlexam** [monkeyWie/proxyee-down#127]
### 问题描述(必要)
下载一半之后暂时，到第二天点继续下载，无法正常继续，一点下载，很快又跳回暂时的状态。
### 版本号(必要)
2.2
### 相关日志

**Comment by monkeyWie** [comment]
可以刷新下载链接，https://github.com/monkeyWie/proxyee-down/blob/master/.guide/common/refresh/read.md

**Comment by castlexam** [comment]
可以了，谢了！
