### ISSUE TITLE
proxyee-down.jar打不开，要进入main文件夹打开proxyee-down-core.jar才能打开程序

### ISSUE THREAD

**Issue by aaxy132** [monkeyWie/proxyee-down#129]
### 问题描述(必要)
proxyee-down.jar打不开，要进入main文件夹打开proxyee-down-core.jar才能打开程序
### 版本号(必要)
2.21
### 相关截图
![1518150688913](https://user-images.githubusercontent.com/26320211/36011869-398548bc-0d95-11e8-89c7-942a81b2af64.jpg)

### 相关日志

**Comment by aaxy132** [comment]
![1518150688913](https://user-images.githubusercontent.com/26320211/36011854-2c3c0218-0d95-11e8-81b3-f396630748eb.jpg)

**Comment by zenghongtu** [comment]
直接打不开是你的java环境没配置好，可以选择在目录中`java -jar proxyee-down.jar`

**Comment by monkeyWie** [comment]
mac可参考新版教程,一键运行 https://github.com/monkeyWie/proxyee-down/blob/master/.guide/mac/read.md
