### ISSUE TITLE
在Win10子系统Ubuntu里不能使用proxyee-down

### ISSUE THREAD

**Issue by kukki** [monkeyWie/proxyee-down#13]
1. 在Windows 10开启Proxyee-down服务, 安装CA证书到Win根目录, 
2. 修改SS的pac.txt, 转发指定domain使用Proxyee-down下载
3. 下载百度云和其它网站的文件, 包插Zip, mp4, m4a等均正常
![2018-01-08 11_15_24-view](https://user-images.githubusercontent.com/897181/34657848-477cd2ee-f465-11e7-8cc9-e858bc881e51.png)

问题:
1. 在Windows 10的子系统Ubuntu里设置全局代理
`export http_proxy=http://localhost:9999`
`export https_proxy=http://localhost:9999`
2. 使用wget和aria2c下载文件, 使用以下命令
`wget --no-check-certificate http://xxxx.yyy.zz/aaa.zip`
`wget --ca-certificate=proxyee-down.ca http://xxxx.yyy.zz/aaa.zip`
`aria2c --check-certificate=false http://xxxx.yyy.zz/aaa.zip`
`aria2c --ca-certificate=proxyee-down.ca http://xxxx.yyy.zz/aaa.zip`
3. 均不能在Proxyee-down的UI里显示下载任务
4. 在子系统Ubuntu里提示直接链接目标地址进行下载, 并没有使用Proxyee-down分块下载
![2018-01-08 11_18_44-wget](https://user-images.githubusercontent.com/897181/34657917-cc3ac1bc-f465-11e7-9ff6-81b7ce25da86.png)

**Comment by monkeyWie** [comment]
@kukki 
1.首先请确认下，你在Ubuntu里设置的http代理是否生效，我看你的配置是**localhost**，虚拟机和win10间是同一个ip吗。
2.现在还不支持命令行的下载，需要浏览器支持。

**Comment by kukki** [comment]
1. 是的, Localhost是和Windows10用同一个IP. 子系统不是VM, 是融合在Win10里面的.
```
$ telnet localhost 9999
Trying 127.0.0.1...
Connected to localhost.
Escape character is '^]'.
]q
Connection closed by foreign host.
```
```
$ curl http://127.0.0.1:9999/
<html><body><div style="margin-top:100px;text-align:center;"><a href="ca.crt">ProxyeeRoot ca.crt</a></div></body></html>%      
```
能连通
2. 期待将来版本

更新:
我用127.0.0.1代替localhost设置代理, 在Debug里能看到转向本地9999代理端口, 估计之前用localhost设置代理不生效. 
![2018-01-08 11_43_07-wget](https://user-images.githubusercontent.com/897181/34658340-1e398d06-f469-11e7-955e-538e1a20b8bb.png)

**Comment by monkeyWie** [comment]
@kukki 
嗯，是有用到代理下载，但是没有浏览器支持的话后续无法交互。

**Comment by kukki** [comment]
如果在开启服务时能设置默认分段数和下载保存的路径, 那么支持命令行方式也就可行了?

**Comment by monkeyWie** [comment]
@kukki 以后单独出一个命令行版的工具吧
