### ISSUE TITLE
Windows 64 2.21版本窗口缩放问题

### ISSUE THREAD

**Issue by BenjaminGao** [monkeyWie/proxyee-down#131]
### 问题描述
GUI 窗口在 __向左缩放__ 的时候，__工具__ 中 __百度云解压__ 这几个字消失，而且其中的绿色方框没有固定宽度，被越来越长或越拉越短，甚至消失
在其他功能，比如 __任务__ 中依旧会出现此问题
### 版本号
WIndows 64 2.21 版本
### 相关截图
![gif](https://user-images.githubusercontent.com/16028320/36017434-a9d26330-0db2-11e8-8ce0-df577262a814.gif)
![gif](https://user-images.githubusercontent.com/16028320/36018028-218cd1ce-0db5-11e8-97a6-361252f835ce.gif)
__图二中窗口缩放过程中留下的浅色重影是 GIF 的问题__
### 相关日志
抱歉我不知道怎么调出日志=。=

**Comment by monkeyWie** [comment]
ui问题后期会调整的
