### ISSUE TITLE
能否再增加分段数到1024？

### ISSUE THREAD

**Issue by sleepinging** [monkeyWie/proxyee-down#132]
我被限速了，一个线程只能10K，256线程只有2.5M的速度，请求作者把上限提高到1024，感谢

**Comment by monkeyWie** [comment]
单文件下载被限速的解决方案请看常见问题列表。https://github.com/monkeyWie/proxyee-down/blob/master/.guide/FAQ.md

**Comment by AnzOOCH** [comment]
合并文件怕不是要合并到明年，滑稽
