### ISSUE TITLE
运行后不报任何信息。

### ISSUE THREAD

**Issue by lemos1235** [monkeyWie/proxyee-down#133]
问题描述(必要)
### 问题描述：
运行教程中的命令后没有任何输出。使用的 jdk 为 java-8-openjdk
```bash
ulimit -c unlimited
java -jar proxyee-down.jar
```
此外，main 目录下无日志文件

![image](https://user-images.githubusercontent.com/23135552/36026511-5fcf0a20-0dd2-11e8-9d41-e2e19bb2ca0d.png)

**Comment by monkeyWie** [comment]
可以运行下main目录里的proxyee-down-core.jar文件试试。
```
java -jar proxyee-down-core.jar
```

**Comment by ThinkerQAQ** [comment]
open-jdk-8 on archlinux has a lot of problems,please use oracle-jdk-xxx instead!
