### ISSUE TITLE
[功能]文件识别的问题

### ISSUE THREAD

**Issue by LamGC** [monkeyWie/proxyee-down#134]
Proxyee-down2.11 Win10x64

发现Proxyee-down可能会把网页上一些图片识别成一个下载文件?- -...建议完善一下文件类型的忽略吧=w=
如图:
![如图!=w=](https://lamgc.coding.me/P_File/QQ%E6%88%AA%E5%9B%BE20180209202937.png)

发现该问题的网址:
https://www.baidu.com/link?url=78MIHrkwrNPVF12-LVbK0QTXaq9eozFWqUMYTAbaSLkEknOnpCg8FaC9qWdzm8224ZtVDcU0yv5p5cikUvfhMq&wd=&eqid=b56d26820000a27b000000065a7d93e5

**Comment by kumoilain** [comment]
这个问题也遇到过。可以把文件转存为自己的，再分享，点下载试一下。然后这个网页打开是csdn问答...？

**Comment by monkeyWie** [comment]
2.3版本嗅探bug已修复

**Comment by LamGC** [comment]
感谢，幸苦了:-)
