### ISSUE TITLE
下到一半就不下了

### ISSUE THREAD

**Issue by 11SDA** [monkeyWie/proxyee-down#135]
### 相关截图
![image](https://user-images.githubusercontent.com/36325281/36060170-f1ceae2e-0e7e-11e8-86e1-01f57740aafb.png)

### 相关日志

[error.2018-02-10.zip](https://github.com/monkeyWie/proxyee-down/files/1713194/error.2018-02-10.zip)

**Comment by evrmji** [comment]
建议减少线程数，被百度云中断了连接。

**Comment by soylens** [comment]
@monkeyWie 请问批量下载打包的任务适用这种方法吗?

**Comment by monkeyWie** [comment]
@soylens 可以的，只要资源相同就可以刷新

**Comment by soylens** [comment]
@monkeyWie 每次打包会不会文件不同?像时间戳之类的

**Comment by soylens** [comment]
刷新批量下载会不会导致时间戳不同,文件会不会有问题

**Comment by monkeyWie** [comment]
@soylens 不会啊 文件还是一样的就行
