### ISSUE TITLE
如果以无扩展名的文件名保存下载任务，会导致解压失败并且文件丢失

### ISSUE THREAD

**Issue by justaaaaaaaaname** [monkeyWie/proxyee-down#136]
如果以**无扩展名**的文件名保存下载任务，由于默认是启动自动解压的，等到下载完毕后会提示“拒绝访问解压失败”，然后到保存的目录下一看，发现要下载的文件**已经变成了一个文件夹**，**空的**，辛辛苦苦下载的几个GB的文件就这样变成了文件夹。推测是编软件时**默认以为用户不会以无扩展名的文件名保存导致解压时文件夹名与无扩展名的文件名冲突**，导致文件丢失（被文件夹覆盖了）
PS.这个BUG很严重，**几个G瞬间化为乌有**······
### 相关日志  ERROR lee.study.down.mvc.controller.HttpDownController - unzip error:
java.io.FileNotFoundException: E:\9 (拒绝访问。)  我当时以“9”这个文件名保存，然后E盘只有一个 9 的空文件夹

**Comment by monkeyWie** [comment]
谢谢反馈，下个版本会进行修复

**Comment by monkeyWie** [comment]
2.3版本已修复
