### ISSUE TITLE
下载到49%就不动了，6.7G的一个文件

### ISSUE THREAD

**Issue by ttentau** [monkeyWie/proxyee-down#14]

**Comment by ttentau** [comment]
我下载了两次
这是文件地址。链接: https://pan.baidu.com/s/1cAsyp4 密码: f1st

**Comment by monkeyWie** [comment]
@ttentau 
里面分段都显示红色了吗？不动的话可以暂停在继续下载试试。

**Comment by ttentau** [comment]
@monkeyWie  有极少数分段显示红色的。下载小文件没问题，后来我租了个百度云账号。。。

**Comment by monkeyWie** [comment]
@ttentau 
先定性为bug，我找找原因

**Comment by zxMrlc** [comment]
我也是天天卡 一个点儿
![image](https://user-images.githubusercontent.com/24544360/34747976-772335b2-f5d5-11e7-96ac-551567ddb91e.png)

**Comment by monkeyWie** [comment]
@zxMrlc 
卡住之后暂停下再继续下载，看看能重新连接上不

**Comment by zxMrlc** [comment]
@monkeyWie  不行卡了两天了   我删除重下了两次都不行  现在是把文件分开下好点了  好像是大点就卡住
4G左右就没问题的

**Comment by monkeyWie** [comment]
@zxMrlc 
能把软件根目录下的log文件夹里的日志贴出来看看吗。

**Comment by zxMrlc** [comment]
@monkeyWie 

[error.2018-01-07.log](https://github.com/monkeyWie/proxyee-down/files/1617877/error.2018-01-07.log)
[error.2018-01-08.log](https://github.com/monkeyWie/proxyee-down/files/1617878/error.2018-01-08.log)
[error.2018-01-09.log](https://github.com/monkeyWie/proxyee-down/files/1617879/error.2018-01-09.log)
[error.2018-01-10.log](https://github.com/monkeyWie/proxyee-down/files/1617880/error.2018-01-10.log)

**Comment by zxMrlc** [comment]
为什么感觉像短板效应
![image](https://user-images.githubusercontent.com/24544360/34761025-11e78462-f61d-11e7-8f00-8133bcc279e7.png)
![image](https://user-images.githubusercontent.com/24544360/34761045-204b5b82-f61d-11e7-847d-d5dfcf9d5a83.png)

**Comment by monkeyWie** [comment]
百度云的话用批量下载，单文件容易遇到链接失效下载不动的问题
