### ISSUE TITLE
英文Windows托盘菜单显示小方块

### ISSUE THREAD

**Issue by syhan** [monkeyWie/proxyee-down#142]
### 相关截图：
![tray](https://user-images.githubusercontent.com/82010/36130753-7399f2d4-10a9-11e8-9724-537ce981106e.PNG)

### 相关日志

A quick fix has been adapted at https://github.com/monkeyWie/proxyee-down/pull/140

**Comment by ezsnipes** [comment]
Same happening for me. I guess it's because of the missing chinese fonts.
@monkeyWie Are  there any plans on adding english language support yet?

**Comment by monkeyWie** [comment]
乱码的问题下个版本会修复的

**Comment by monkeyWie** [comment]
@ezsnipes 
There is no support for English for the time being，but the problem will be fixed.

**Comment by monkeyWie** [comment]
2.3版本已修复乱码问题
