### ISSUE TITLE
使用固定的自签发证书是很危险的！

### ISSUE THREAD

**Issue by hyxxsfwy** [monkeyWie/proxyee-down#143]
不要使用固定的自签发 CA 证书，应当在每台机器上首次运行时生成一个。这个问题在当年 goagent 时代就被讨论过多次了，希望作者重视！

**Comment by monkeyWie** [comment]
嗯，有考虑过这个问题，下个版本还是自动生成CA证书吧

**Comment by monkeyWie** [comment]
在2.3版本之后已经是使用非固定CA证书了
