### ISSUE TITLE
小BUG和建议

### ISSUE THREAD

**Issue by AnzOOCH** [monkeyWie/proxyee-down#144]
系统：win10 家庭版 64
软件版本：2.11

创建新任务在选择下载目录时最好能够显示磁盘剩余空间，还有，如果能自动记忆上一次任务的下载目录就更好了。

BUG：使用Switchomega插件从其他代理模式（如系统代理）切换回127.0.0.1:9999时偶尔会出现这样的情况：百度云页面能够正常打开，但是单击下载按钮后，下载任务是通过浏览器自带下载或者其他下载工具开始的，尽管这个也能下载但是速度不如您的软件快。重启浏览器后恢复。

**Comment by justaaaaaaaaname** [comment]
@AnzOOCH 不太赞同 自动记忆上一次任务的下载目录 ，建议把这个功能做成可开关的，因为有时下载一些隐私的东西这个功能就不好了。（特别是公共电脑）

**Comment by AnzOOCH** [comment]
有道理，不过公共电脑。。。真的会用这个吗

**Comment by monkeyWie** [comment]
自动记忆上次下载目录功能已经有了呀
