### ISSUE TITLE
一些比较复杂的链接无法创建任务

### ISSUE THREAD

**Issue by justaaaaaaaaname** [monkeyWie/proxyee-down#145]
### 问题描述  如题,比如这样的下载链接
https://r2---sn-ogueln7r.googlevideo.com/videoplayback?dur=165.070&itag=22&pl=21&ip=46.4.85.237&key=cms1&source=youtube&id=o-AAJ5_XQdO3SqRVqNdwx54vPDU8MhSbW-C-NdanPAetBb&expire=1518735817&sparams=dur,ei,expire,id,initcwndbps,ip,ipbits,itag,lmt,mime,mip,mm,mn,ms,mv,pl,ratebypass,requiressl,source&mime=video%2Fmp4&signature=83EFB10861BB80C5466AB76D7DD1C0C6E7476489.232508ACF0E459B6F56163FCBABD7AA8C224774E&lmt=1518668518893036&c=WEB&ratebypass=yes&fvip=2&ipbits=0&requiressl=yes&ei=ab2FWqiwLMy3Weutk7gJ&title=%E8%A1%8C%E6%94%BF%E9%95%B7%E5%AE%98%E5%B4%94%E4%B8%96%E5%AE%89%E7%99%BC%E8%A1%A8%E6%88%8A%E6%88%8C%E5%B9%B4%E6%96%B0%E6%98%A5%E7%8D%BB%E8%BE%AD&mip=47.74.233.56&redirect_counter=1&cm2rm=sn-npoll7l&req_id=b664a68cb40aa3ee&cms_redirect=yes&mm=34&mn=sn-ogueln7r&ms=ltu&mt=1518713691&mv=u
这样的链接无法创建任务,会提示"格式不正确"
应该不是网络问题，因为我已经设置了二级代理到SS
### 操作系统(必要) Windows 7 旗舰版 64bit

**Comment by monkeyWie** [comment]
2.3已修复
