### ISSUE TITLE
建议新版（2.22以后的）增添一些功能

### ISSUE THREAD

**Issue by justaaaaaaaaname** [monkeyWie/proxyee-down#146]
如题，建议增添以下这些功能：
1.**几乎所有下载软件均支持在下载过程中或下载结束后查看任务的属性**（包括IDM也支持）， 
而最新版的2.22（下同）**无法支持**。这个功能很有必要，有时想复制某个任务的下载URL或查看任务的更多详细信息，却发现**只能查看任务的下载速度和各分段的进度**，无法找到更多有用的信息；

2.最新版创建百度云任务后，由于默认是启用自动解压的，有时下载过程中想取消自动解压，发现无法取消，几个G的文件就只能等解压完才能完成下载任务，**建议支持下载过程中取消自动解压**；

3.建议**增加对命令行下载的支持**，比如IDM就支持，这样就很方便用批处理；

4.建议支持**批量下载**；

5.建议在 创建任务 窗口创建完一个任务（即输入URL点击确定）后，窗口还在，能**持续**创建任务；

6.最新版 二级代理 设置关闭后再开启发现之前设置的参数全部丢失，建议将参数**设为关闭后还能记忆**，避免重复输入；

7.**强烈建议增添限速功能，避免占用过多宽带。**
### 操作系统(必要) Windows 7 旗舰版 64bit

**Comment by luaaaa** [comment]
https://github.com/luaaaa/video
