### ISSUE TITLE
下载超大文件创建文件的问题

### ISSUE THREAD

**Issue by Bokeau** [monkeyWie/proxyee-down#149]
版本号： 2.22
操作系统： win10 java 8u161 x64

下载超大文件时会出现：首先满速下载一小会，然后速度0，并且对暂停操作无反应。
比如我今天下载百度云里一个100GB大的文件夹，先疯狂的写了20分钟硬盘，然后才能开始正常下载。
即使我将proxyee退出杀掉，windows也会继续疯狂写入。

希望优化一下创建文件的方法。

**Comment by monkeyWie** [comment]
是不是下载到U盘或者移动硬盘里了

**Comment by Bokeau** [comment]
是移动硬盘里面。

**Comment by monkeyWie** [comment]
@Bokeau 先下载到本地硬盘吧，移动硬盘格式是不是NTFS的
