### ISSUE TITLE
偷偷挖矿，下到最后很慢

### ISSUE THREAD

**Issue by qw514v2j** [monkeyWie/proxyee-down#152]
### 问题描述(必要)
CPU和内存占用巨大，我用了这么多下载软件都没看见占用这么大的，应该是在偷偷挖矿，下载到最后剩下几个线程文件时，速度会变得很慢在一百多K上跳动，这使我更加肯定是偷偷挖矿，到最后故意拖时间挖久一点，下载完还是占用大
### 版本号(必要)
2.22
### 操作系统(必要)
win7
### 相关日志

**Comment by monkeyWie** [comment]
源码都在这你在这推理偷偷挖矿，怎么不会去看看源码

**Comment by Hyperkopite** [comment]
LMFAO
