### ISSUE TITLE
百度网盘多次下载之后，百度网盘点击下载会弹出验证码对话框，输入后仍然不能下载。

### ISSUE THREAD

**Issue by lirun121** [monkeyWie/proxyee-down#153]
### 相关截图
![image](https://user-images.githubusercontent.com/32787983/36517407-e5a29dee-17bc-11e8-9420-268c8fdba5be.png)

### 相关日志
###另外：不知道如何使用新建功能。

**Comment by lirun121** [comment]
百度了一下进调试找下载链接，但是哪个下载链接也仅仅是一个报错信息。

**Comment by monkeyWie** [comment]
文件夹名字不能带+号，记得看常见问题列表
