### ISSUE TITLE
一定要装JDK,不要单独装JRE,macOS用得太爽了

### ISSUE THREAD

**Issue by androidcn** [monkeyWie/proxyee-down#154]
一定要装JDK,不要单独装JRE,macOS用得太爽了

**Comment by androidcn** [comment]
启动 无法双击启动,,有点麻烦
必须命令行启动..
java -jar xxx.jar

**Comment by xsfone** [comment]
hello,我mac按照教程上的装好了以后，客户端可以启动，但不能获取下载地址，为什么？不是百度云但下载地址都可以。什么是JDK

**Comment by androidcn** [comment]
SwitchyOmega 必须安装这个，才能自动启动下载任务

**Comment by JerryCui** [comment]
按照安装步骤来的，装的也是jdk，但是运行不成功，托盘没有出现图标也没有任何安装提示。

**Comment by HongHaiyang** [comment]
我现在看 Mac 的安装教程没说需要安装 SwitchyOmega 呀，Mac 上点击启动成功了，但是点击下载软件没反应😂

**Comment by monkeyWie** [comment]
mac现在出了一键运行版的具体查看，https://github.com/monkeyWie/proxyee-down/blob/master/.guide/mac/read.md
