### ISSUE TITLE
占内存问题

### ISSUE THREAD

**Issue by maijz128** [monkeyWie/proxyee-down#155]
### 问题：java.exe 占内存问题
能否优化内存占用？
打开程序后，后台程序 java.exe 就占了 500,000K 以上；下载完任务后， 占到了 1,000,000K 以上。

### 相关截图
打开后
![default](https://user-images.githubusercontent.com/6248618/36627040-e8e50b10-1977-11e8-9aab-c53a8c21a927.png)

下载后
![default](https://user-images.githubusercontent.com/6248618/36627042-eb8d2578-1977-11e8-890d-95f4a8f138d0.png)

**Comment by monkeyWie** [comment]
2.3已经减小了内存的使用量
