### ISSUE TITLE
程序启动时自动设置系统代理的行为改成可选开关

### ISSUE THREAD

**Issue by kukki** [monkeyWie/proxyee-down#157]
### 问题描述(必要)
本机原本设置了系统代理, 它在启动或关闭Proxyee-down时会被强制取消.
即使我在托盘里`嗅探模式`设置为`关闭`. 依然有这个问题.

重现步骤:
1. 启动proxyee-down.exe
2. 等待几秒, 系统提示Proxyee-Down启动成功, 程序托盘出现
3. 右击程序托盘, 把`嗅探模式`设置为`关闭`.
![关闭嗅探模式](https://image.ibb.co/kbtKtH/2018_02_26_10_21_24.png)
4. 关闭Proxyee-Down程序
5. 把系统代理恢复正常为
    1. 系统代理为http://127.0.0.1:8080
    2. 取消自动配置脚本(如下图)
![正常代理设置](https://image.ibb.co/cEJPSc/2018_02_26_10_28_12_Local_Area_Network_LAN_Settings.png)
6. 启动proxyee-down.exe
7. 等待几秒, 系统提示Proxyee-Down启动成功, 程序托盘出现
8. 重新检查本地网络设置
9. 发现代理设置被修改
    1. `本地系统代理`设置被取消. 
    2. `自动配置脚本`被设置为`http://127.0.0.1:9000/res/pd.pac`
![代理设置被修改](https://image.ibb.co/hQZsDH/2018_02_26_10_21_48_Local_Area_Network_LAN_Settings.png)
10. 保持Proxyee-down运行状态
11. 把系统代理恢复正常为
    1. `本地代理`为http://127.0.0.1:8080
    2. 取消`自动配置脚本`(如下图1)
12. 关闭Proxyee-Down程序
13. 重新检查本地网络设置
14. 发现代理设置被修改, 状况与#9一致
    1. `本地系统代理`设置被取消. 
    2. `自动配置脚本`被设置为`http://127.0.0.1:9000/res/pd.pac`

期待:
1. 当`嗅探模式`设置为`关闭`时, 不强制修改`本地网络设置`里包括`代理服务器`的所有设置

### 版本号(必要)
2.22

### 操作系统(必要)
Windows 10 Pro

### 相关截图
![Proxy](https://image.ibb.co/caujsc/2018_02_25_10_04_18_Internet_Properties.png)

### 相关日志
日志文件为空文件

**Comment by monkeyWie** [comment]
托盘里可以设置的

**Comment by kukki** [comment]
不好意思, 我没有表达清楚. 
本机原本设置了系统代理, 它在启动或关闭Proxyee-down时会被强制取消.
即使我在托盘里`嗅探模式`设置为`关闭`. 依然有这个问题.

重现步骤:
1. 启动proxyee-down.exe
2. 等待几秒, 系统提示Proxyee-Down启动成功, 程序托盘出现
3. 右击程序托盘, 把`嗅探模式`设置为`关闭`.
![关闭嗅探模式](https://image.ibb.co/kbtKtH/2018_02_26_10_21_24.png)
4. 关闭Proxyee-Down程序
5. 把系统代理恢复正常为
    1. 系统代理为http://127.0.0.1:8080
    2. 取消自动配置脚本(如下图)
![正常代理设置](https://image.ibb.co/cEJPSc/2018_02_26_10_28_12_Local_Area_Network_LAN_Settings.png)
6. 启动proxyee-down.exe
7. 等待几秒, 系统提示Proxyee-Down启动成功, 程序托盘出现
8. 重新检查本地网络设置
9. 发现代理设置被修改
    1. `本地系统代理`设置被取消. 
    2. `自动配置脚本`被设置为`http://127.0.0.1:9000/res/pd.pac`
![代理设置被修改](https://image.ibb.co/hQZsDH/2018_02_26_10_21_48_Local_Area_Network_LAN_Settings.png)
10. 保持Proxyee-down运行状态
11. 把系统代理恢复正常为
    1. `本地代理`为http://127.0.0.1:8080
    2. 取消`自动配置脚本`(如下图1)
12. 关闭Proxyee-Down程序
13. 重新检查本地网络设置
14. 发现代理设置被修改, 状况与#9一致
    1. `本地系统代理`设置被取消. 
    2. `自动配置脚本`被设置为`http://127.0.0.1:9000/res/pd.pac`

期待:
1. 当`嗅探模式`设置为`关闭`时, 不强制修改`本地网络设置`里包括`代理服务器`的所有设置

**Comment by monkeyWie** [comment]
@kukki 知道你的意思了，下个版本会修复这个问题的

**Comment by monkeyWie** [comment]
2.32已修复
