### ISSUE TITLE
百度云解压无法解压已经下载好的ZIP文件

### ISSUE THREAD

**Issue by DamianRice** [monkeyWie/proxyee-down#158]
### 
![360 20180226135814128](https://user-images.githubusercontent.com/32694676/36655354-1d2e57ce-1afd-11e8-9123-fa2e8e6eda0e.jpg)

### 相关日志
[error.2018-02-26.log](https://github.com/monkeyWie/proxyee-down/files/1757371/error.2018-02-26.log)

**Comment by monkeyWie** [comment]
是勾选的单文件下载的吧？

**Comment by DamianRice** [comment]
@monkeyWie 对的，现在重新更新完以后下载了一遍，已经解决问题了，应该是网络传输的问题，谢谢您回复！
