### ISSUE TITLE
写入缓存功能

### ISSUE THREAD

**Issue by maijz128** [monkeyWie/proxyee-down#159]
### 问题描述：
当前版本是否有写入缓存功能？如果没有的话，下一个版本是否会加入此功能？

### 操作系统：Windows7 64bit

我的硬盘在嘎嘎作响...
![11](https://user-images.githubusercontent.com/6248618/36658786-1575a68a-1b0d-11e8-9526-5bbb4aabfa30.gif)

**Comment by monkeyWie** [comment]
写入缓存没有这个说法吧。

**Comment by maijz128** [comment]
不好意思，我可能用词不当。
我的意思是每个线程每次下载到数据就立即写入硬盘吗？没有缓存吗？

**Comment by monkeyWie** [comment]
不写入硬盘缓存在内存里多占资源啊。。
