### ISSUE TITLE
建议：可不可以通过浏览器插件的方式调用proxyee-down

### ISSUE THREAD

**Issue by wjk199511140034** [monkeyWie/proxyee-down#161]
改成类似idm那样，因为代理我是留给ss穿墙用的，每次启动proxyee-down都会把ie代理更改，如果关闭嗅探则需要手动新建任务，鱼与熊掌不可兼得ing。。。。

**Comment by monkeyWie** [comment]
自己弄个代理切换规则就好了啊

**Comment by wjk199511140034** [comment]
@monkeyWie 不是自启动切换规则的问题，我平时根本不用ie浏览器，但是stream和应用商店之类的程序都是使用ie代理设置的，我的ie配置是交给ss处理的，每次我打开proxyee-down都会使ie代理关闭(设置了关闭嗅探)，然后造成steam打不开，应用商店打开贼慢等诸多问题。。。
或者说ie上也有类似的代理管理插件？求指教啊，，，

**Comment by monkeyWie** [comment]
可以用chrome配合swich插件来下载，就不需要动ie了

**Comment by wjk199511140034** [comment]
@monkeyWie 我要说的不是这个啊！！！！天啊我快要崩溃了，
我简述一下问题，每次启动proxyee-down都会导致我的steam(一个游戏平台)打不开，每次启动proxyee-down都会导致我的win10应用商店变卡

**Comment by etjim** [comment]
@monkeyWie  此问题和这个问题类似[](https://github.com/monkeyWie/proxyee-down/issues/157)

**Comment by monkeyWie** [comment]
@wjk199511140034 设置proxyee-down的嗅探模式成关闭，然后启动不会再修改IE的代理设置啊

**Comment by monkeyWie** [comment]
2.32已修复，并添加对外接口提供调用下载https://github.com/monkeyWie/proxyee-down/blob/master/.guide/common/api/read.md
