### ISSUE TITLE
要下载的文件不能直接保存到本地磁盘下

### ISSUE THREAD

**Issue by etjim** [monkeyWie/proxyee-down#165]
### [相关截图]
![default](https://user-images.githubusercontent.com/31721939/36900565-b69cc8b4-1e5e-11e8-81b5-92d3e4ecdcfa.png)

### 相关日志

**Comment by beautifulword** [comment]
右击f盘，属性，安全，更改权限

**Comment by etjim** [comment]
@beautifulword 已经给当前用户设置完全控制权限还是不行，旧版本根本不需要设置权限。

**Comment by monkeyWie** [comment]
可以更新至2.32，BUG已修复

**Comment by etjim** [comment]
谢谢作者修复
