### ISSUE TITLE
快要下载完成速度变得异常慢

### ISSUE THREAD

**Issue by yongqingxie** [monkeyWie/proxyee-down#167]
### 相关截图:
![unnamed qq screenshot20180304104911](https://user-images.githubusercontent.com/24885976/36941594-fcdfe446-1f99-11e8-8cd1-d7b18b861c6f.png)

### 相关日志

**Comment by beautifulword** [comment]
因为多线程，话说你也在下ff15，还是86+g打包下载。。。。。网速真好

**Comment by monkeyWie** [comment]
因为总速度是所有分段汇总的，别的分段都下载完成了自然总速度就慢下来了

**Comment by yongqingxie** [comment]
@beautifulword 还行 下载速度平均 9MB/S

**Comment by yongqingxie** [comment]
@monkeyWie 好的 感谢解答
