### ISSUE TITLE
由于证书不被信任，火狐无法导入证书

### ISSUE THREAD

**Issue by cnDelbert** [monkeyWie/proxyee-down#169]
操作系统 Windows 10
版本 2.22
浏览器 Firefox 58.0.2 en-US

无法导入证书，提示 This is not a certificate authority certificate, so it can’t be imported into the certificate author

**Comment by monkeyWie** [comment]
新版本火狐证书有问题，先用别的浏览器吧

**Comment by kukki** [comment]
2.32 存在同样问题, 请问在问题修复之前, 有Workaround(临时解决方法)吗? 
例如能不能手动创建CA让FF和PD使用, 如果能, 怎样导入证书给PD?

**Comment by monkeyWie** [comment]
@kukki 新版本动态生成的证书没加CA扩展，火狐不认。。

**Comment by kukki** [comment]
我想应该是某些属性影响吧. 上面用OpenSSL生成出来的也没有CA扩展.

![cacert1](https://image.ibb.co/jqLLyS/2018_03_07_09_49_46_C_Users_jimmykoo_Applications_proxyee_down_ssl_ootb.png)
左边的是程序自带的, 右边的是openssl生成的

**Comment by monkeyWie** [comment]
2.33已修复
