### ISSUE TITLE
进程挂掉，重启后任务列表为空

### ISSUE THREAD

**Issue by 1132719438** [monkeyWie/proxyee-down#17]
进程异常挂掉
[hs_err_pid1220.log](https://github.com/monkeyWie/proxyee-down/files/1624988/hs_err_pid1220.log)

重新启动后任务列表被清空了，能恢复未完成的任务吗？
用的是windows 1.6.2版本

**Comment by monkeyWie** [comment]
@1132719438 
看看软件目录下的records.inf文件还在不在。

**Comment by monkeyWie** [comment]
@1132719438 
进程是怎么挂掉的，有什么异常操作吗。你电脑是多少G内存？

**Comment by 1132719438** [comment]
records.inf还在
内容解了一下
`Total task:	4
-------- begin ---------
id:	fa5a8e1e-ca62-485a-8801-6c33627985da
connections:	128
totalSize:	28565453398
supportRange:	true
downSize:	10025731454
startTime:	2018-01-11 21:46:19
lastTime:	2018-01-11 23:48:19
pauseTime:	1970-01-01 08:00:24
status:	1
--------- end ----------

-------- begin ---------
id:	f2868078-877a-4716-9a05-3b2ec55a9b6a
connections:	128
totalSize:	16320769359
supportRange:	true
downSize:	10005289649
startTime:	2018-01-11 21:48:06
lastTime:	2018-01-11 23:48:18
pauseTime:	1970-01-01 08:00:54
status:	1
--------- end ----------

-------- begin ---------
id:	f16c8508-b034-485a-a64b-211a58885fb9
connections:	128
totalSize:	26043802724
supportRange:	true
downSize:	1881019272
startTime:	2018-01-11 23:14:54
lastTime:	2018-01-11 23:48:18
pauseTime:	1970-01-01 08:00:00
status:	1
--------- end ----------

-------- begin ---------
id:	302ad949-36e0-404a-9016-d457d3dd88b9
connections:	128
totalSize:	40191963648
supportRange:	true
downSize:	0
startTime:	2018-01-11 23:48:22
lastTime:	1970-01-01 08:00:00
pauseTime:	1970-01-01 08:00:00
status:	1
--------- end ----------`

进程在凌晨自己挂掉了，这是日志
[hs_err_pid10600.log](https://github.com/monkeyWie/proxyee-down/files/1625141/hs_err_pid10600.log)

然后在中午启动了一下，发现四个任务只显示了两个，不一会进程又自己挂掉了，日志是hs_err_pid1220.log那个文件

然后再次启动，所有任务都没了，进程再没有挂掉

会是因为内存不够吗，电脑是8G内存，四个任务总共约102GB

**Comment by 1132719438** [comment]
records.inf第四个任务 downSize是0，但对应文件的inf文件里解出来downSize是32054847676，这是怎么回事

**Comment by monkeyWie** [comment]
@1132719438 
看看软件目录下里的log文件夹里的error日志，可能是异常崩溃导致records.inf文件写入不完整导致读取不了，所以任务显示不出来了。崩溃的原因估计和任务总大小有关，因为是用FileChannel map把文件映射到内存里写，这么大的还没有测试过。
