### ISSUE TITLE
2.32,2.33 在我的系统上都没有下载提示.

### ISSUE THREAD

**Issue by ramiua** [monkeyWie/proxyee-down#172]
### 问题描述(必要)

在百度页面上点击下载,不弹出下载页面
文件名不含+号.
使用firefox ,ie 都是如此

### 版本号(必要)
2.32,2.33
### 操作系统(必要)
windows 10 enterprise x64
version 1709
OS build 16299.248
安装了jre-8u161-windows-x64.exe
又在virtualbox上全新安装的系统式了一下,还是一样.

### 相关日志
/main/log文件夹里 有个error-2018xxxx.log文件,没有内容,0字节.

**Comment by monkeyWie** [comment]
是校内网吗？

**Comment by monkeyWie** [comment]
网盘页面里的proxyee-down标记出现了吗

**Comment by ramiua** [comment]
网页上有proxyee-down.
刚才式了一下,用ie有时候会弹出乱码提示,按ok之后显示一些英文和乱码网页,再关闭ie重新打开,网页又正常了,现在用ie可以下载了,
firefox还是不行,点击网页下载按钮没反应.

**Comment by monkeyWie** [comment]
firefox证书导入了吗，还有firefox建议配合插件来下载，具体看教程

**Comment by joshatt** [comment]
我也是这样, 这几天都不响应了. 以前挺好.........版本: 2.3,2.33.  win7x64.
现在就是批量下载还是挺正常的

**Comment by ramiua** [comment]
firefox 默认不能安装证书,需要取消勾选一个选项才能安装证书.之后就可以下载了,
用ie有时候不能下载.有时候可以,现在还没有找到规律.
另外,ie代理设置为127.0.0.1:9999时有时候打开pan.baidu.com会有乱码提示
![virtualbox_cnxulei9_08_03_2018_21_27_44](https://user-images.githubusercontent.com/28190337/37184630-472fd8c2-2377-11e8-8504-96acce4bfb2a.png)
点击ok后,
![virtualbox_cnxulei9_08_03_2018_21_27_58](https://user-images.githubusercontent.com/28190337/37184636-504ad25e-2377-11e8-82df-317b4651a11d.png)

**Comment by ramiua** [comment]
另外一个问题,多个进程下载的时候有的进程不动,点击暂停然后再开始也是不动.
![virtualbox_cnxulei9_09_03_2018_05_19_37](https://user-images.githubusercontent.com/28190337/37184734-e30030ee-2377-11e8-8975-ccfbf18ae081.png)
两个不动的,88G都白下载了.

**Comment by ramiua** [comment]
![virtualbox_cnxulei9_09_03_2018_09_03_35](https://user-images.githubusercontent.com/28190337/37184963-f6901bfa-2378-11e8-98f5-7f3461d1917b.png)

**Comment by monkeyWie** [comment]
@ramiua 可以刷新下载链接

**Comment by ramiua** [comment]
有些文件下载不了,用常规方式也下载不了,不知道为什么
https://pan.baidu.com/s/1ge74IsV?fid=20096930319559

**Comment by monkeyWie** [comment]
@ramiua 
百度云资源问题

**Comment by luaaaa** [comment]
https://github.com/luaaaa/video

**Comment by lisitodyb** [comment]
校内网不能用么，我前几天用2.2可以，更新后不会显示proxyee的标记了

**Comment by monkeyWie** [comment]
@lisitodyb 校内网的看常见问题列表第一个
https://github.com/monkeyWie/proxyee-down/blob/master/.guide/FAQ.md
