### ISSUE TITLE
希望能提高Mac下与科学上网软件的兼容性，谢谢

### ISSUE THREAD

**Issue by TTXSJie** [monkeyWie/proxyee-down#175]
### 问题描述(必要)
可以使用。但是会导致科学上网软件lantern失效，即使关掉proxyee-down也不行，必须重启才能恢复正常。
Note：最新的安装指导（Mac）中没有再要求安装SwitchyOmega插件，然而仍然使用该插件的功能才能下载，否则点击链接会打开度盘客户端。proxyee-down中的自动嗅探已打开
### 版本号(必要)
2.33 但是之前的2.22版本没有上述问题，中间的版本没用过。
### 操作系统(必要)
Mac
浏览器：Chrome
### 相关日志

**Comment by monkeyWie** [comment]
把嗅探模式设置成关闭，然后用SwitchyOmega插件来切换代理下载，这样就不会影响到lantern了

**Comment by TTXSJie** [comment]
可以使用了，谢谢您
