### ISSUE TITLE
任务卡死，尝试刷新链接失败。

### ISSUE THREAD

**Issue by TGhoul** [monkeyWie/proxyee-down#176]
### 问题描述(必要)
任务卡死在%1或%2，尝试刷新链接失败，下载相同任务无法呼出下载提示框，删除任务才可以新建下载任务，再次尝试还是卡在相同的地方，删除任务需要等待很长时间。
### 版本号(必要)
2.3.3 2.3.2
### 操作系统(必要)
win10
### 浏览器
chrome 64

**Comment by monkeyWie** [comment]
下载到移动硬盘还是u盘里了?

**Comment by TGhoul** [comment]
@monkeyWie 不支持移动硬盘吗？

**Comment by monkeyWie** [comment]
@TGhoul 移动硬盘的格式如果不是NTFS可能就会出现这个问题，最好是直接下载本地硬盘吧

**Comment by TGhoul** [comment]
@monkeyWie 我下固态里再试试吧，但是我的移动硬盘就是NTFS格式的。
