### ISSUE TITLE
ubuntu下安装需要java8以及openjfx

### ISSUE THREAD

**Issue by urugang** [monkeyWie/proxyee-down#177]
### 问题描述(必要)
使用java9+openjfx无法启动。  
安装下列软件后可以启动。建议linux安装说明里增加jfx和java配套的关系。
```
apt-get install openjdk-8-jdk  
apt-get install openjfx
```
### 版本号(必要)
2.3.4
### 操作系统(必要)
ubuntu 17.10
### 相关日志

**Comment by monkeyWie** [comment]
linux教程已更新

**Comment by ThinkSora** [comment]
18.04 2.52
安装好openjdk8和openjfx以后还是启动失败，而且看不到proxyee 的 banner
反而是直接下jre的话能看到banner但是依旧无法成功启动.

**Comment by monkeyWie** [comment]
@ThinkSora 看不到托盘可以访问http://127.0.0.1:26339

**Comment by ThinkSora** [comment]
@monkeyWie 通过浏览器能打开。不过我也发现，现在启动了虽然不会直接弹出界面，但是成功从度盘添加下载任务以后会自动打开主程序界面。

再次感谢大佬！
