### ISSUE TITLE
请问能不能将证书更新功能去掉或者加个开关

### ISSUE THREAD

**Issue by yipsama** [monkeyWie/proxyee-down#178]
我用的是Firefox
Firefox每天更新证书之后都需要重新导入证书，挺麻烦的。
请问能不能加个设置来控制是否每天更新证书呢？

谢谢

**Comment by monkeyWie** [comment]
每天更新证书？不需要啊

**Comment by yipsama** [comment]
我这里的ssl/ca.crt每次打开都会更新一次，然后firefox换成代理之后，就会上不了网。必须重新导入ca.crt

**Comment by monkeyWie** [comment]
什么版本啊

**Comment by yipsama** [comment]
最新版本

**Comment by monkeyWie** [comment]
操作系统呢，是不是没把证书安装到系统里

**Comment by yipsama** [comment]
MacOS，不知道为什么撞不到系统里面去

**Comment by monkeyWie** [comment]
手动安装证书
https://github.com/monkeyWie/proxyee-down/blob/master/.guide/common/ca/read.md

**Comment by yipsama** [comment]
我知道firefox可以装，但是以前旧版本是不用一直重新装的，现在每次开软件都要装一次

**Comment by monkeyWie** [comment]
@yipsama 把mac系统上证书装上，或者你看看你系统有没有装

**Comment by yipsama** [comment]
系统装上并信任了，但是Firefox还是不行，version Firefox 56

**Comment by monkeyWie** [comment]
系统和火狐都装上同一个证书也不行吗

**Comment by yipsama** [comment]
不行。。。

**Comment by monkeyWie** [comment]
启动的时候有提示证书安装失败吗

**Comment by yipsama** [comment]
没呢

**Comment by monkeyWie** [comment]
可以远程看看吗，我qq263397478

**Comment by monkeyWie** [comment]
新版本已经支持设置启动不检查证书了
