### ISSUE TITLE
99%就不能下载了

### ISSUE THREAD

**Issue by hsfxuebao** [monkeyWie/proxyee-down#179]
问题描述(必要)：下载文件的时候下载到95%，99%就不能下载了，重启，试了好多次还是不行
版本号(必要)：proxyee-down-2.33-windows-x64
操作系统(必要)：Win8

**Comment by monkeyWie** [comment]
看教程刷新链接

**Comment by ramiua** [comment]
按我的经验大部分时候刷新也没用,
不知道是软件的问题还是百度的问题.
![virtualbox](https://user-images.githubusercontent.com/28190337/37266770-809c8d26-25f7-11e8-9f7f-f44573d4d7f7.png)

**Comment by monkeyWie** [comment]
可以看看log，如果一直是401或者404，可能资源已经失效了

**Comment by tribody** [comment]
同遇到这个问题，下载了三四次，都是99%挂掉。
版本号：proxyee-down-2.34-windows-x64
操作系统：win10专业版1607
@monkeyWie 另外想问下作者，没下完的可能取部分资源吗？感谢您的分享~

**Comment by hsfxuebao** [comment]
可以的，就是在1%的那一部分的东西就没有了

**Comment by tribody** [comment]
@hsfxuebao 具体怎么操作啊？

**Comment by hsfxuebao** [comment]
@tribody 直接解压就可以，我下载的是压缩包的形式的，解压就可以，没有下载完的那一部分呢就会出现解压错误，然后忽略这个错误就可以

**Comment by tribody** [comment]
@hsfxuebao 好的，谢谢了~

**Comment by monkeyWie** [comment]
99%的问题最近我也发现了，目前分析是百度云那边的问题，要等好久才能下完

**Comment by tribody** [comment]
@monkeyWie 换了你最新的版本，直接显示的是一个叉，状态是“失败”
![image](https://user-images.githubusercontent.com/6322069/37444872-1697a492-284f-11e8-8b77-cd6ec98bd0f7.png)

**Comment by monkeyWie** [comment]
百度云的问题，刷新任务链接试试

**Comment by tribody** [comment]
@monkeyWie 还是没有用，我分文件夹下载吧。。。谢谢回复

**Comment by tribody** [comment]
@monkeyWie 刚才退出重开了一下可用了，谢谢！

**Comment by monkeyWie** [comment]
参考https://github.com/monkeyWie/proxyee-down/issues/246#issuecomment-378516262
