### ISSUE TITLE
启动后页面报错

### ISSUE THREAD

**Issue by zhiincom** [monkeyWie/proxyee-down#18]
> Whitelabel Error Page
> 
> This application has no explicit mapping for /error, so you are seeing this as a fallback.
> 
> Sun Jan 14 22:52:51 CST 2018
> There was an unexpected error (type=Not Found, status=404).
> No message available

请问这是什么原因呢？

**Comment by monkeyWie** [comment]
@zhiincom 
前端页面需要编译,需要node.js环境
```
cd proxyee-down/view
npm install
npm run build
```
