### ISSUE TITLE
百度不能搜索

### ISSUE THREAD

**Issue by Blackwalk** [monkeyWie/proxyee-down#181]
### 相关截图  
![2018-03-15_004909](https://user-images.githubusercontent.com/13019792/37417247-bc9f9f1c-27ea-11e8-8b43-5dfba759feda.png)

### 相关日志
[error.2018-03-13.log](https://github.com/monkeyWie/proxyee-down/files/1812099/error.2018-03-13.log)

**Comment by monkeyWie** [comment]
把你的代理设置贴出来看看

**Comment by monkeyWie** [comment]
https://github.com/monkeyWie/proxyee-down/issues/246#issuecomment-378516262
