### ISSUE TITLE
进度条超出100%

### ISSUE THREAD

**Issue by Alienware18** [monkeyWie/proxyee-down#182]
进度条超出100% 问题描述(必要)
2.35 版本号(必要)
Win10 16299.309操作系统(必要)
![default](https://user-images.githubusercontent.com/32356999/37419887-6b2a0d6a-27f0-11e8-8751-e33e521c8605.png)
实际为重新下载了

**Comment by monkeyWie** [comment]
有重现步骤吗

**Comment by comhuhuan** [comment]
有很多专业的测试    程序越来越完善了





发自网易邮箱大师
在2018年03月15日 09:19，monkeyWie 写道：

有重现步骤吗

**Comment by Alienware18** [comment]
理论上是开了两个Proxyee,用一号proxyee删除了正在下载的文件(我好像是99%的时候删的)，并使用二号proxyee继续刚被一号proxyee删除的文件(因为第一个proxyee删了文件后第二个proxyee并不不会同步)。就会出现超出100%

**Comment by monkeyWie** [comment]
2.5已修复
