### ISSUE TITLE
磁盘空间不足, 请修改路径

### ISSUE THREAD

**Issue by fozoto** [monkeyWie/proxyee-down#189]
### 问题描述
   对磁盘剩余空间判断有bug
   一直file.getParentFile()拿到了ubuntu的根目录/, 单独分区的.
![image](https://user-images.githubusercontent.com/34918133/37562432-e48b0560-2aa2-11e8-927c-fcf46ae04120.png)

![image](https://user-images.githubusercontent.com/34918133/37562430-d874621c-2aa2-11e8-891b-522e1934e9ab.png)

   测试如下:
     
![image](https://user-images.githubusercontent.com/34918133/37562441-39b8bde8-2aa3-11e8-92ea-d9e38c7c346f.png)

![image](https://user-images.githubusercontent.com/34918133/37562443-42e6f7ea-2aa3-11e8-80f7-462159403488.png)

   只能自己打包玩了

### 相关截图
   
![image](https://user-images.githubusercontent.com/34918133/37562426-b6c91fea-2aa2-11e8-80f8-e1470a197938.png)

![image](https://user-images.githubusercontent.com/34918133/37562407-397c0048-2aa2-11e8-8cf2-11f40a837bb1.png)

### 相关日志
   日志文件是空的

**Comment by monkeyWie** [comment]
谢谢反馈，2.41已经修复
