### ISSUE TITLE
批量下载，韩文文件名乱码

### ISSUE THREAD

**Issue by 1132719438** [monkeyWie/proxyee-down#19]
测试https://pan.baidu.com/s/1eUlK51K

使用自带解压工具解压后韩文文件名乱码，使用Bandizip并把代码页设为简体中文后不会乱码

**Comment by monkeyWie** [comment]
@1132719438 
代码页设置是哪里啊？

**Comment by 1132719438** [comment]
![image](https://user-images.githubusercontent.com/10138791/35079444-7fc4ebe8-fc42-11e7-92e3-a5f91f4c7bc1.png)

**Comment by 1132719438** [comment]
@monkeyWie 经过确认使用**GB18030**编码可以解决乱码，你能不能修改后测试一下

**Comment by monkeyWie** [comment]
@1132719438  好的，我试试看

**Comment by monkeyWie** [comment]
@1132719438 
已经更新了。
