### ISSUE TITLE
会导致ss翻墙失效, 必须关了这个软件重开ss才行. 

### ISSUE THREAD

**Issue by menghun8** [monkeyWie/proxyee-down#191]
### 问题描述(必要)
会导致ss翻墙失效, 必须关了这个软件重开ss才能翻墙. 
### 版本号(必要)
2.35
### 操作系统(必要)
Windows 10 教育版

**Comment by monkeyWie** [comment]
可以把嗅探模式关闭，然后配合插件设置下载的代理
