### ISSUE TITLE
点击下载后无反应

### ISSUE THREAD

**Issue by skhe** [monkeyWie/proxyee-down#193]
### 问题描述(必要)
点击下载后无反应，文件夹，单个文件都无反应。关闭软件后，可下载单个文件。
### 版本号(必要)
2.35
### 操作系统(必要)
win10  chrome
### 相关截图
![](http://ww1.sinaimg.cn/large/005PneI2gy1fplbvgs5vyj30zf0owgp1.jpg)
### 相关日志
相关日志为空

**Comment by wlhdgm** [comment]
同样的问题，21号晚上似乎还好用，22号早上就不行了

**Comment by skhe** [comment]
是不是百度更新了？

**Comment by monkeyWie** [comment]
今天确实不行了，不知道是百度抽风还是调整了策略。现在正在看

**Comment by LoveAlwaysYoung** [comment]
同样问题，无法下载

**Comment by 007twenty** [comment]
加油 兄弟你最棒

**Comment by zhaiziweilove** [comment]
我也是这个问题，研究了好久还是没发现问题，还以为自己电脑有问题哈哈哈，加油

**Comment by monkeyWie** [comment]
2.36已经修复了百度云不能弹下载的问题。

**Comment by joshatt** [comment]
233没反应. 升级了236, 还是没反应

**Comment by skhe** [comment]
我这边可以正常下载了。感谢开发者。 @monkeyWie

**Comment by Exculibar7** [comment]
百度修改策略了，油猴那边已阵亡，这边更新后能用了，感谢~

**Comment by monkeyWie** [comment]
2.4可以更新了，修复了一些百度云相关的bug

**Comment by joshatt** [comment]
@monkeyWie 2.4非常好用. 感谢!!!
