### ISSUE TITLE
无法弹出下载页面

### ISSUE THREAD

**Issue by amostang** [monkeyWie/proxyee-down#194]
问题描述
我在百度云页面按下载无法弹出proxyee down页面,我安装了证书，SwitchyOmega也直接导入了文件，也切换至pd自动转换

版本号
2.36
操作系统
win 10 google chrome
相关截图
![image](https://user-images.githubusercontent.com/37657584/37765883-6092ffae-2e00-11e8-9fea-6537c9c7fc3d.png)

相关日志
none

**Comment by 120809** [comment]
总是弹出 百度BaiduyunquanjiaProtocol, 还是无法连结至proxy

版本号
2.36
操作系统
win 7 
google chrome 版本 65.0.3325.181

**Comment by JerryCui** [comment]
switchy 切换proxy down代理后，pan.baidu.com打不开了。

**Comment by monkeyWie** [comment]
升级到2.4
