### ISSUE TITLE
提示file does not exist

### ISSUE THREAD

**Issue by 1132719438** [monkeyWie/proxyee-down#199]
### 问题描述(必要)
下载文件夹时提示{"error_code":31066,"error_msg":"file does not exist","request_id":1910805047347283661}
链接：https://pan.baidu.com/s/1KWPOT7UZk2UWboURFQS_yQ
### 版本号(必要)
2.4
### 操作系统(必要)
Windows X64
### 相关日志

**Comment by monkeyWie** [comment]
文件名夹名字不能带+号
