### ISSUE TITLE
如何参与项目？

### ISSUE THREAD

**Issue by konanzheng** [monkeyWie/proxyee-down#2]
想帮忙的话，如何参与进来

**Comment by monkeyWie** [comment]
@konanzheng 可以fork一份，然后提交pr，欢迎加入~

**Comment by konanzheng** [comment]
我先参与问题回复，和熟悉代码吧，等熟悉了之后再贡献代码

**Comment by p0we7** [comment]
想知道mac上面怎么编译出二进制文件? 
还是说现在的源码只支持windows吗?

**Comment by monkeyWie** [comment]
@p0we7  编译成jar包运行就行

**Comment by p0we7** [comment]
@monkeyWie 想编译免java运行环境的.

**Comment by GGFocus** [comment]
我也想贡献一份力，学习一下
