### ISSUE TITLE
下载本来就包含有压缩包的文件夹后，文件夹内的压缩包解压报错的问题。

### ISSUE THREAD

**Issue by geek4d** [monkeyWie/proxyee-down#20]
下载文件如下
https://pan.baidu.com/s/1pMNfNQj
三个文件夹均可以正常下载并形成一个单个的ZIP压缩文件，该压缩文件可以用软件内部的解压工具解压到磁盘上，但是解压出来的文件夹中原有的比如RAR格式的压缩包，直接解压RAR软件会报错，用PD内部的解压工具会也会提示服务器错误之类的WEB弹窗报错。

**Comment by monkeyWie** [comment]
2.1版本已修复文件下载损坏问题

**Comment by geek4d** [comment]
已对之前下载的文件进行重新下载测试，确认该问题已修复，作者辛苦了！
