### ISSUE TITLE
目录下文件数量如果超过100,应该怎样下载?

### ISSUE THREAD

**Issue by ramiua** [monkeyWie/proxyee-down#200]
### 问题描述(必要)
目录下文件数量如果超过100,下载下来只有100个文件.
### 版本号(必要)
2.4
### 操作系统(必要)
windows10
### 相关日志

**Comment by monkeyWie** [comment]
分开下吧，这是百度的限制

**Comment by ramiua** [comment]
怎样分?,网页上显示的就不全

**Comment by monkeyWie** [comment]
怎么可能显示不全，要不就是分页了

**Comment by ramiua** [comment]
一个目录下面最多显示100个文件,
![screenshot-2018-3-25 _ -](https://user-images.githubusercontent.com/28190337/37870354-aa7b0b18-3006-11e8-97b9-370e218b7768.png)
