### ISSUE TITLE
SwitchyOmega插件设置不成功，不能获取连接

### ISSUE THREAD

**Issue by guopengxun** [monkeyWie/proxyee-down#202]
### 相关截图 
![image](https://user-images.githubusercontent.com/34209071/37872561-aec45162-303c-11e8-8ea2-34cc83e4ac90.png)
![image](https://user-images.githubusercontent.com/34209071/37872563-b99fe4b6-303c-11e8-846b-6c5212eb2e7e.png)

### 相关日志

**Comment by monkeyWie** [comment]
什么不成功？
