### ISSUE TITLE
软件启动后，百度云网页打不开

### ISSUE THREAD

**Issue by rwzhao** [monkeyWie/proxyee-down#204]
### 相关日志

**Comment by Pleiadesvii** [comment]
同样遇到这个问题
1. 版本号
    + 2.4
2. 操作系统
    + win10 1703

**Comment by monkeyWie** [comment]
提示什么，截个图

**Comment by DanielWLam** [comment]
+1

**Comment by Pleiadesvii** [comment]
@monkeyWie 

![image](https://user-images.githubusercontent.com/23145965/37875528-5b550756-3073-11e8-8e11-376d0f5ef95d.png)

**Comment by monkeyWie** [comment]
看起来像是软件没有启动啊，托盘出现了吗

**Comment by tafice** [comment]
尝试以管理员权限启动

**Comment by tomoya92** [comment]
我也碰到了这个问题，只要软件启动了，百度去就打不开了，chrome，ie都试过，全都打不开

版本：2.42

**Comment by 14SHIKE** [comment]
尝试删除原有的软件解压文件（如果没有正在进行的任务）
从软件压缩包里重新解压新的
打开软件提示启动成功后，查看浏览器网盘页面能否打开

**Comment by monkeyWie** [comment]
更新最新的2.42吧

**Comment by tomoya92** [comment]
问题还在，出现了这个界面 
![image](https://user-images.githubusercontent.com/6915570/38125177-3a2c30a4-341a-11e8-93c3-142c1f9d3cc6.png)
感觉是证书的问题

**Comment by monkeyWie** [comment]
@tomoya92 证书问题看教程里的手动安装证书步骤
