### ISSUE TITLE
proxyee-down运行不报错，但无法下载

### ISSUE THREAD

**Issue by bj1507** [monkeyWie/proxyee-down#206]
### 问题描述(必要)
运行没有报错，但访问127.0.0.1:9999 没响应，打开百度云盘也下载不了文件
### 版本号(必要)
proxyee-down-2.41
### 操作系统(必要)
ubuntu 16.04
JAVA 1.8.0
### 相关截图

![2018-03-26 15-26-53](https://user-images.githubusercontent.com/37793427/37892758-733e81ce-310b-11e8-94be-7d76be0e7904.png)

![2018-03-26 15-27-45](https://user-images.githubusercontent.com/37793427/37892779-918de908-310b-11e8-8f95-5274a2734dbe.png)

![2018-03-26 15-27-57](https://user-images.githubusercontent.com/37793427/37892785-95fc01b4-310b-11e8-86c2-c9810eedf94b.png)

![2018-03-26 15-29-45](https://user-images.githubusercontent.com/37793427/37892789-9b9ffcba-310b-11e8-89a3-cc27ebc9aed4.png)

### 相关日志

**Comment by monkeyWie** [comment]
直接运行这个https://github.com/monkeyWie/proxyee-down/blob/master/start

**Comment by bj1507** [comment]
加参数-Dfile.encoding=GBK 运行不起来,无提示，无报错。
改成-Dfile.encoding=UTF-8 后能运行，但一样打不开127.0.0.1:9999

**Comment by monkeyWie** [comment]
为什么要打开127.0.0.1:9999

**Comment by bj1507** [comment]
谢谢回复，就是按最新的教程来的。
托盘出现了的，也提示启动成功。但访问127.0.0.1:9999安装证书打不开。
用SwitchyOmega设置好访问百度，页面显示不正常，也无法下载，就像截图这样。

**Comment by monkeyWie** [comment]
教程里没有说要访问127.0.0.1:9999啊，你是什么版本

**Comment by 14SHIKE** [comment]
https://github.com/monkeyWie/proxyee-down/blob/master/.guide/linux/read.md
原来的证书地址127.0.0.1：9999应该不能打开了
证书更改为随机证书
这个教程需要修改（我没有测试证书随机后的版本，猜测是这样）

**Comment by monkeyWie** [comment]
右键托盘进入证书目录就可以找到证书了

**Comment by bj1507** [comment]
右键拖盘证书目录打不开，但在目标文件下的确看到了此证书文件,导入致chrome，并更改为信任后，操作正常，测试速度很快，谢谢大神的软件。
