### ISSUE TITLE
mac下会导致ss无法正常使用

### ISSUE THREAD

**Issue by foxzld** [monkeyWie/proxyee-down#207]
### 问题描述(必要)
mac下在开启该软件后会导致ss无法正常使用，关闭后需手动重新启动SS，尝试使用SwitchyOmega插件来规避这一问题，但由于mac下的ss软件（ssx-ng）是接手系统代理，并默认设置为pac自动模式，你这里给出的SwitchyOmega的pd自动切换规则是非百度云相关内容使用直接连接模式，与ss软件冲突，实测会影响浏览器中翻墙的使用，不知道有没有什么好方法
### 版本号(必要)
2.4.1
### 操作系统(必要)
Mac OS
### 相关日志

**Comment by foxzld** [comment]
虽然使用默认的模式，下载完成后手动开关一下ss就ok，也不算太麻烦，不过总觉得如果能解决这方面问题会更好一些

**Comment by monkeyWie** [comment]
关闭嗅探模式就好，然后设置SwitchyOmega

**Comment by foxzld** [comment]
就是关闭嗅探然后设置SwitchyOmega出现的上述问题

**Comment by foxzld** [comment]
实测在我的环境下SwitchyOmega 需要设置为系统代理模式才能正常使用ss上网，但SwitchyOmega的规则貌似不能设置为非百度云的页面走系统代理模式，而只能选择『『直接连接』』的模式

**Comment by foxzld** [comment]
ok了，自己发现一种取巧的方法来规避这一问题，在SwitchyOmega下新建一个代理服务器的情景模式，设置为sock5；127.0.0.1；1086（ssx-ng的默认监听设置），然后在pd自动切换情景模式中把『默认情景模式』改成刚刚新建的这个情景模式，实测不影响ss且不影响下载

**Comment by foxzld** [comment]
不对，这样设置百度云的网页打不开了。。。汗。。。

**Comment by monkeyWie** [comment]
你可以默认设置SS的pac，百度单独走pd的代理啊

**Comment by monkeyWie** [comment]
![image](https://user-images.githubusercontent.com/13160176/37919468-8f383e42-3156-11e8-94e8-ca3c9d7ce96d.png)

**Comment by Wonderdch** [comment]
有种简单的方法，只保留 *proxyee-down下载* 情景模式，在需要下载百度云文件时切换到该模式，平时都用 *系统代理*。

**Comment by foxzld** [comment]
@Wonderdch  如果这样还不如每次手动开关一下ss。毕竟mac上也就是手动点两下鼠标。还不需要多装一个浏览器插件

**Comment by foxzld** [comment]
@monkeyWie  还是不折腾这么麻烦了，毕竟手动开关ss也不麻烦，下载的时候全速下载上网也受影响
