### ISSUE TITLE
源码该怎么阅读

### ISSUE THREAD

**Issue by JQiMeng** [monkeyWie/proxyee-down#209]
求教，想学习一下，但是不知道入口文件是哪个。各位帮忙分析一下代码结构

**Comment by monkeyWie** [comment]
入口在https://github.com/monkeyWie/proxyee-down/blob/master/ui/src/main/java/lee/study/down/gui/HttpDownApplication.java

**Comment by tomoya92** [comment]
大量的反射，看着真累 😂
