### ISSUE TITLE
选中全部文件打包后无法下载（没有速度）

### ISSUE THREAD

**Issue by man2018** [monkeyWie/proxyee-down#211]
### 问题描述(必要)
勾选百度云网盘里面的全部文件和文件夹，进行打包下载时
### 版本号(必要)
proxyee-down 2.41
### 操作系统(必要)
mac osx 10.13.3 64位 14年中期macbook pro
### 相关截图
![proxyee-down](https://user-images.githubusercontent.com/18020785/37941201-982e9200-319f-11e8-888f-062342c2159c.jpg)

### 相关日志
无

**Comment by monkeyWie** [comment]
速度截图呢

**Comment by man2018** [comment]
@monkeyWie 现在可以了亲，感谢了
![keyile](https://user-images.githubusercontent.com/18020785/37941658-dd41b8b6-31a1-11e8-8a8e-babd30c35b70.jpg)
