### ISSUE TITLE
任务批量管理

### ISSUE THREAD

**Issue by SpaceEggs** [monkeyWie/proxyee-down#212]
### 问题描述(必要)

列表模式很多人都说了就不提了。
另外希望增加任务批量管理功能，批量删除，批量下载这些功能。
其他都很好用

### 版本号(必要)

2.4.1

### 操作系统(必要)

Windows 10 x64

### 相关日志

**Comment by 14SHIKE** [comment]
1.任务批量删除
2.任务顺序下载
这两个功能十分期待

**Comment by monkeyWie** [comment]
2.5已支持
