### ISSUE TITLE
下载任务只有四五个分段在下载 

### ISSUE THREAD

**Issue by QHYSC** [monkeyWie/proxyee-down#217]
### 相关日志

**Comment by ramiua** [comment]
下载速度慢,而且经常变红停止,很多到99%就不动了,刷新也没用
![df](https://user-images.githubusercontent.com/28190337/38026400-8593903a-32be-11e8-924e-6fc0cacda702.png)

**Comment by k122333** [comment]
我的也是这样，只有四五个分段在下载，下载完那几个分段后就完全没速度，然后变红说失败，今天才这样的

**Comment by monkeyWie** [comment]
把日志上传看看

**Comment by ramiua** [comment]
error.2018.3.28.log   105M
error.2018.3.27.log   1.05G
记事本强制关了

**Comment by QHYSC** [comment]
[Uploading error.2018-03-28.log…]()
[Uploading error.2018-03-28.log…]()

**Comment by QHYSC** [comment]
[Uploading error.2018-03-28.log…]()

**Comment by 14SHIKE** [comment]
你可以尝试只下载一个任务或者暂停别的任务
不要同时进行
然后刷新链接试试
应该会有效果

**Comment by ramiua** [comment]
![sdfa](https://user-images.githubusercontent.com/28190337/38035966-2dc77028-32d8-11e8-86bd-f38b8e99205c.png)
经常有这样的提示

**Comment by ramiua** [comment]
![3fs](https://user-images.githubusercontent.com/28190337/38036204-c6cfb122-32d8-11e8-9dc4-24ee0a43f113.png)

**Comment by monkeyWie** [comment]
可以更新到2.42，具体原因看这里https://github.com/monkeyWie/proxyee-down#2018-03-29更新
