### ISSUE TITLE
无法浏览百度网盘

### ISSUE THREAD

**Issue by git-wanglei** [monkeyWie/proxyee-down#220]
### 问题描述(必要)
下载时显示没有选中文件，升级版本到2.42后依然提示没有选中文件，并且在重启软件后无法打开百度网盘，页面显示如下信息：
pan.baidu.com 意外终止了连接。
ERR_INCOMPLETE_CHUNKED_ENCODING
### 版本号(必要)
2.42
### 操作系统(必要)
win10 64位 ltsb2016
浏览器chrome 65.0.3325.181
### 相关日志

**Comment by 14SHIKE** [comment]
2.42版本刚发出来就撤掉了，有bug        
等作者上传新的2.42版本

**Comment by monkeyWie** [comment]
需要更新最新的2.42，昨天上传的那个版本有问题
