### ISSUE TITLE
如何下载？

### ISSUE THREAD

**Issue by VCDVD** [monkeyWie/proxyee-down#223]
![image](https://user-images.githubusercontent.com/32630138/38069432-e0aac29c-3348-11e8-9b1f-731dd2f1bef9.png)
按提示进入下载页面，并没有所说的“根据操作系统的位数选择对应proxyee-down-x.xx-windows-xxx.zip文件进行下载”内容，只看到Assets源码链接。
![image](https://user-images.githubusercontent.com/32630138/38069481-34f33e9c-3349-11e8-81f5-719fcef7f55b.png)
难道大伙都是懂源码、会开发编译软件的程序猿吗？就不能提供做好的可执行程序文件，照顾一下非IT专业群体？

**Comment by monkeyWie** [comment]
这里下载 https://github.com/monkeyWie/proxyee-down#下载
