### ISSUE TITLE
ARM版本无法运行，无任何报错提示

### ISSUE THREAD

**Issue by mouyuemoyu** [monkeyWie/proxyee-down#224]
OrangePi，ARM CPU，安装的debian 9.3，安装java后依旧无法运行，无任何报错提示
版本：2.41
系统：Linux orangepiplus 3.4.39 #22 SMP PREEMPT Sun May 3 11:15:34 HKT 2015 armv7l GNU/Linux
截图：无
日志：无

**Comment by monkeyWie** [comment]
怎么运行的，运行完之后的截图看看

**Comment by mouyuemoyu** [comment]
![_20180330140743](https://user-images.githubusercontent.com/16871470/38126522-c09664d0-3423-11e8-9068-4c821c60d2f3.png)

**Comment by monkeyWie** [comment]
看看main目录里有log没

**Comment by mouyuemoyu** [comment]
发现了，是没有图形界面，导致无法启动，建议后面加入服务端，类似aria，方便远程调用下载。

**Comment by monkeyWie** [comment]
没安装javafx吧
