### ISSUE TITLE
ubuntu18.04 启动成功了 但是在浏览器输入 http://127.0.0.1:9999，无响应

### ISSUE THREAD

**Issue by qincg** [monkeyWie/proxyee-down#225]
### 问题描述(必要)
ubuntu18.04 启动成功了 但是在浏览器输入 http://127.0.0.1:9999 ,无法连接，且日志目录生成了一个文件
### 版本号(必要)
2.43
### 操作系统(必要)
ubuntu 18.04
### 相关截图
![default](https://user-images.githubusercontent.com/29474459/38092000-ada60626-3399-11e8-82f1-2c0967a204f9.png)

### 相关日志
有日志文件，但是无内容

**Comment by 14SHIKE** [comment]
注意：
为了安全，改成随机证书后，这个地址127.0.0.1：9999就不能打开了
右键托盘进入证书目录就可以找到证书了，或者直接进入软件所在目录/main/ssl里查看

**Comment by monkeyWie** [comment]
参考最新的linux安装教程https://github.com/monkeyWie/proxyee-down/blob/master/.guide/linux/read.md
