### ISSUE TITLE
希望窗口大小可以固定下来

### ISSUE THREAD

**Issue by tomoya92** [monkeyWie/proxyee-down#228]
### 问题描述(必要)

每次打开都基本是全屏的，建议给窗口大小的一半宽高然后居中显示会比较好

另外建议上一次调整的窗口大小能写个配置文件，下次打开的时候直接读配置文件里的大小位置显示就好了

### 相关日志

**Comment by monkeyWie** [comment]
2.43支持保存窗口位置啊
