### ISSUE TITLE
貌似带版权的影音文件无法下载了

### ISSUE THREAD

**Issue by nickcarter8317** [monkeyWie/proxyee-down#229]
前几天还可以，今天试了一下，无论CHROME和火狐都无法下载了，有这回事吗？
![qq 20180330150230](https://user-images.githubusercontent.com/13479039/38128108-c974918c-342b-11e8-8e33-124fdaa59cdd.jpg)
点击下载就弹出这个。以前是不会弹这个框框的
星球大战老电影，无法分享的。
![qq 20180330150705](https://user-images.githubusercontent.com/13479039/38128183-1c5cafec-342c-11e8-994b-82f6fc9348a1.jpg)

去找了一个今天才上传到度盘的一个电影文件就没什么问题
![qq 20180330150416](https://user-images.githubusercontent.com/13479039/38128200-2dce77a6-342c-11e8-8197-2a08f73514c1.jpg)
难道是百度更改了机制吗？

**Comment by monkeyWie** [comment]
把链接提供下

**Comment by monkeyWie** [comment]
已修复
