### ISSUE TITLE
2.43版本下载的文件会损坏，解压不了

### ISSUE THREAD

**Issue by huf754123** [monkeyWie/proxyee-down#230]
### 相关日志

**Comment by monkeyWie** [comment]
你是在哪下载的新版本？

**Comment by Poiob** [comment]
WIN10  2.43同问题+1
从onedrive下的版本
百度云多个文件下载的压缩包失败
zip格式的都提示错误，只有一个音频的压缩包幸免
唯一的一个rar没事

**Comment by monkeyWie** [comment]
@Poiob 可以提供下载链接和下载选择的文件吗

**Comment by Poiob** [comment]
文件夹里有三个PDF小文件
链接: https://pan.baidu.com/s/1ejrzuIC38tULPY3zdccCTQ 密码: i24i   
这个是稍微大点的游戏包
链接: https://pan.baidu.com/s/1cvBq1dK2sQfbrUmZmXPd5A 密码: i528

**Comment by victoryLV** [comment]
我的问题也是这样，版本和楼主相同，下载的文件全部显示损坏，用下载器的解压缩也是出现问题

**Comment by zeta911** [comment]
压缩文件损坏，并且在用官方教程之后进行SwitchyOmega切换之后网页出现“未加载资源——加载失败的资源”，并显示网页未连接到互联网，是我的操作不对吗？

**Comment by 14SHIKE** [comment]
现在发现一个问题
2.41后的X86新版本的合并问题没有优化好，操作系统是32的要注意，批量下载后会损坏
其他的解压损坏问题，建议参考教程：批量下载尽量分段数不超过64，而且尽量不勾选文件夹

**Comment by monkeyWie** [comment]
损坏的都是用的x86版本吗？

**Comment by 14SHIKE** [comment]
2.41版本后的X86批量下载解压失败，文件损坏
X64的解压失败问题，我个人还没有遇到
另外有些人下载时下载进度超过100%
x64-2.43-86G-批量下载（含文件夹），退出软件后左侧百度云工具解压失败

**Comment by monkeyWie** [comment]
2.44已修复x86上的问题
