### ISSUE TITLE
怎么下载迅雷的链接或者一些常见的种子链接呢

### ISSUE THREAD

**Issue by 0x00xw** [monkeyWie/proxyee-down#234]
### 问题描述(必要)
新建迅雷等常见工具链接，提示格式错误，
### 版本号(必要)
最新
### 操作系统(必要)
windows10 x64
### 相关截图
![image](https://user-images.githubusercontent.com/19531560/38161588-546170de-3504-11e8-849d-43c670b3cfa3.png)

### 相关日志

**Comment by monkeyWie** [comment]
先用百度离线下载好再通过百度云下
