### ISSUE TITLE
点击下载按钮后出现错误代码

### ISSUE THREAD

**Issue by dhx2261** [monkeyWie/proxyee-down#238]
### 相关日志

百度云页面点击下载按钮后跳转网页，然后出现错误代码，无法调用proxyee
{"error_code":31426,"error_msg":"hotlinking forbidden , hitcode:113","request_id":2118091242055206821}
错误代码网页地址：
https://d.pcs.baidu.com/file/52e158373a6182354310f7b059fea27b?fid=1731566104-250528-557009517508727&time=1522626504&rt=sh&sign=FDTAERVY-DCb740ccc5511e5e8fedcff06b081203-ou5nLcyRcTrZR7JG7s83COqpsDc%3D&expires=8h&chkv=1&chkbd=0&chkpc=et&dp-logid=2118091242055206821&dp-callid=0&r=283616242

**Comment by 14SHIKE** [comment]
你应该是分享链接下载
注意：
尽量分享文件夹，而不是直接分享文件
有些时候网盘会提示热门资源无法下载

**Comment by monkeyWie** [comment]
这个意思是资源被禁了

**Comment by JasonKhew96** [comment]
保存到自己的网盘就可以下载了
