### ISSUE TITLE
跟新版本后速度过慢

### ISSUE THREAD

**Issue by heyun1989** [monkeyWie/proxyee-down#241]
### 
![default](https://user-images.githubusercontent.com/38007948/38200289-53e5fd5a-36c6-11e8-9eb2-3f999986be81.jpg)

### 相关日志

**Comment by heyun1989** [comment]
不好意思打扰了，追加一下问题。现在新的下载项目经常出现页面不见了，需要多次反复刷新。然后目前所有项目下载速度都变成了0
![2](https://user-images.githubusercontent.com/38007948/38201136-aecb3318-36c9-11e8-9586-9f995a66e2d5.jpg)

**Comment by monkeyWie** [comment]
看更新日志，百度限制了批量下载的并发数，建议设置在64以下

**Comment by heyun1989** [comment]
好的尝试一下，感谢回复。还有就是经常不能设置分段。win7是32位的。

**Comment by heyun1989** [comment]
还有就是点击下载经常出现如下画面，要不断反复刷新偶尔会成功。
![3](https://user-images.githubusercontent.com/38007948/38248595-7f59ea9a-377b-11e8-8ea0-6232d618eb75.jpg)

**Comment by monkeyWie** [comment]
这个就是百度云的限制，过一段时间下载就好
