### ISSUE TITLE
Chrome 65.0.3325.181 点击插件后直接跳转到Github页面

### ISSUE THREAD

**Issue by ThinkSora** [monkeyWie/proxyee-down#242]
### 相关日志

安装加载完成进入云盘界面后，点击proxyee-down按钮自动跳转到github主页面了，无法加载下载任务。
Proxyee-down 2.44
OS：Win10 64-bit 16299.334
日志文件为空

![ieproxy-screenshot](https://user-images.githubusercontent.com/6876189/38207951-7e44cd2c-367d-11e8-8ef8-6e023c62719e.png)

![-screenshot](https://user-images.githubusercontent.com/6876189/38207749-dcffe230-367c-11e8-8d4d-c4091b5e07fb.png)

![logfile-screenshot](https://user-images.githubusercontent.com/6876189/38207729-c6a64420-367c-11e8-9b47-58a987617aa3.png)

**Comment by monkeyWie** [comment]
选择文件点下载按钮就好，这个只是提示插件加载成功的作用
