### ISSUE TITLE
下载链接经常出错，分段64依然速度为0

### ISSUE THREAD

**Issue by heyun1989** [monkeyWie/proxyee-down#244]
### 
![3](https://user-images.githubusercontent.com/38007948/38249169-5b5a6406-377d-11e8-8f60-153dc7a1e401.jpg)

### 相关日志

**Comment by 14SHIKE** [comment]
解决方法：关闭已打开的网盘页面，重新进入个人网盘或者分享链接，下载时勾选上面的下载按钮
速度问题：建议分享链接下载
目前2.44
单文件下载不限速（分段数可根据自己网络拉到最大）
多文件下载（批量下载）建议分段数64以下，而且建议不勾选文件夹（因为速度不稳定）
其他速度问题请刷新链接！

**Comment by heyun1989** [comment]
感谢回复！部分文件已经下载完成。
根据要求重新设置之后其中一个文件出现新的问题：99%之后无法继续。
等待超过一个小时，已经删除重新下载三四次依然不行，不知是否是文件本身问题还是2.44软件版本兼容问题。
![4](https://user-images.githubusercontent.com/38007948/38257405-c245a26a-3792-11e8-9402-affc66001898.jpg)

**Comment by heyun1989** [comment]
![4](https://user-images.githubusercontent.com/38007948/38259294-372be946-3797-11e8-8fce-dd5184f827e5.jpg)
现在不知道是不是网络的问题我连99%截图都不能发了orz|||||，链接的话是这个：
http://pan.baidu.com/s/1dDg6JhJ 
登陆码aswg

**Comment by 14SHIKE** [comment]
qdcache03.链接开头的都有这儿问题，今天才发现
尝试分享链接下载
感谢反馈

**Comment by monkeyWie** [comment]
可以复制出链接，把链接前面的内容替换成d11.baidupcs.com或者yqall02.baidupcs.com，新建任务进行刷新任务下载

**Comment by 14SHIKE** [comment]
nbcache03.链接开头的，有这个问题吗？
遇到一个这个链接开头10kb限速，最后也是不动，刷新链接无效，不知道能不能替换开头链接刷新

**Comment by heyun1989** [comment]
感谢回复，之后下载尝试替换。

**Comment by hooboor** [comment]
你们到底是怎么下载的？为什么会一直出现问题？我除了一次系统宕机外，没有出现过下载不了的情况出现！！！再说一次，使用EX-百度云盘插件。

**Comment by hooboor** [comment]
https://www.baidupcs.com/rest/2.0/pcs/file?method=batchdownload&app_id=250528&zipcontent=%7B%22fs_id%22%3A%5B%22431188204472970%22%5D%7D&sign=DCb740ccc5511e5e8fedcff06b081203:v5SLFWu3ABVcFK3Q2FES8s4Mb%2B4%3D&uid=606326040&time=1523764678&dp-logid=2400424442382481425&dp-callid=0&vuk=1935854481&from_uk=606326040&zipname=%E3%80%90%E6%96%87%E4%BB%B6%E3%80%91%E4%B8%8D%E6%80%9D%E8%AE%AE%E6%B8%B8%E6%88%8F.OVA3.%E6%B0%B8%E5%85%89%E4%BC%A0.Fushigi.Yuugi.DVDRip.2Audio.HALFCD-NORM.yule.zip.zip
https://www.baidupcs.com/rest/2.0/pcs/file?method=batchdownload&app_id=250528&zipcontent=%7B%22fs_id%22%3A%5B%221040259256254202%22%5D%7D&sign=DCb740ccc5511e5e8fedcff06b081203:HvQJ0Urg6GkRTRphv92NjrEjGAs%3D&uid=606326040&time=1523764678&dp-logid=2400424445335644888&dp-callid=0&vuk=1935854481&from_uk=606326040&zipname=%E3%80%90%E6%96%87%E4%BB%B6%E3%80%91%E4%B8%8D%E6%80%9D%E8%AE%AE%E6%B8%B8%E6%88%8F.OVA2.%E5%BB%B6%E7%BB%AD%E7%AF%87.Fushigi.Yuugi.DVDRip.2Audio.HALFCD-NORM.yule.zip.zip
https://www.baidupcs.com/rest/2.0/pcs/file?method=batchdownload&app_id=250528&zipcontent=%7B%22fs_id%22%3A%5B%22289188331071399%22%5D%7D&sign=DCb740ccc5511e5e8fedcff06b081203:w%2FGdwzmuh%2BCR%2Bxh95POL3dA4kBo%3D&uid=606326040&time=1523764678&dp-logid=2400424452262770915&dp-callid=0&vuk=1935854481&from_uk=606326040&zipname=%E3%80%90%E6%96%87%E4%BB%B6%E3%80%91%E4%B8%8D%E6%80%9D%E8%AE%AE%E6%B8%B8%E6%88%8F.OVA1.%E5%90%8E%E7%AF%87.Fushigi.Yuugi.DVDRip.2Audio.HALFCD-NORM.yule.zip.zip

试试我给你的链接

**Comment by blackyang** [comment]
> 可以复制出链接，把链接前面的内容替换成d11.baidupcs.com或者yqall02.baidupcs.com，新建任务进行刷新任务下载

今天测试d11.baidupcs.com开头还是有问题，但是yqall02.baidupcs.com可以
