### ISSUE TITLE
cent browser 不能关联启动proxyee-down

### ISSUE THREAD

**Issue by sylph520** [monkeyWie/proxyee-down#245]
### 问题描述(必要)
cent browser 使用SwitchyOmega或百度云嗅探 都不能关联启动proxyee-down的web端或GUI
### 版本号(必要)
v2.44
### 操作系统(必要)
windows, cent browser版本 3.2.4.23（正式版本） （32 位） (Chromium 64.0.3282.140)
### 相关日志

**Comment by sylph520** [comment]
应该不是重启的问题， 好像是直接被cent browser接管了 2333

**Comment by 14SHIKE** [comment]
代理问题，你可以使用别的浏览器测试一下
之前有个例子：拨号上网，QQ浏览器，没有proxyeedown标记，点击下载被浏览器接管
问题是代理没有设置好
