### ISSUE TITLE
下载百度云文件时卡99%

### ISSUE THREAD

**Issue by jscpc** [monkeyWie/proxyee-down#246]
### 相关日志

**Comment by monkeyWie** [comment]
谢谢反馈

**Comment by jscpc** [comment]
不是自己的网盘。是别人分享的链接。并不是所有的链接都是这样。只有https://qdcache03.这样开头的。下载到99%后不动。但是从https://qdcache00.或者https://qdcache01.这样开头的链接。就能正常下载。目前我还没下载过文件夹。所以不知道文件夹是不是也有这个问题。

**Comment by monkeyWie** [comment]
可以复制出链接，把链接前面的内容替换成d11.baidupcs.com或者yqall02.baidupcs.com，新建任务进行刷新任务下载

**Comment by yun2673436976** [comment]
@monkeyWie 作者你好，我看到很多人下载到95% 99%都停止，解决方法：在百度云里选择你要下载的文件，创建任务后，替换链接刷新链接后，不要马上点击下载，先退出帐号，再点击下载，就可以解决，本人亲测，请把这方法写进帮助文档，感谢作者开发这软件破解百度云。

**Comment by monkeyWie** [comment]
@yun2673436976 截图之后直接粘贴进来就好，网页播放器不支持的

**Comment by YLaido** [comment]
试了上面的方法还是不行，有一个分段卡在70%，多次刷新无果。文件大小15G

**Comment by mashangzhao** [comment]
我今天也遇到了99%的问题。
思路跟作者差不多。
最后的解决方案，是根据油猴脚本，拿到下载链接。然后新建任务，软件认出了同一个资源，好像是刷新，然后任务列表的下拉框选择99%停止下载的那个，最后就好了，100%。
https://github.com/monkeyWie/proxyee-down/blob/master/.guide/common/refresh/read.md

**Comment by ixiusama** [comment]
我用了作者提供的方法，它新建了一个新的下载并命名为xxxx（1）.xxx

**Comment by ixiusama** [comment]
![snipaste20180509_021847.png](https://i.loli.net/2018/05/09/5af1ea29237fe.png)
尝试过作者的方法还是不行 程序重新创建了一个新的任务

**Comment by monkeyWie** [comment]
@ixiusama 你开了自动下载吧？

**Comment by ixiusama** [comment]
@monkeyWie 嗅探模式是开启的，刷新任务要关闭嗅探模式么？ 装了一个程序推荐的油猴脚本。

**Comment by ixiusama** [comment]
我傻逼了 在`设置`里面吧`自动下载`关闭了以后就可以了

**Comment by xrandx** [comment]
替换链接刷新也没用，还是停在99%，最后一个分段没速度

**Comment by ZengX2017** [comment]
有一个15.66G的一直卡99%，不知道是什么情况。
1. 我用油猴的脚本替换刷新过任务，还是卡九
2. 我用下载替换刷新过任务，还是卡九
3. 其余任务中，完成下载的最大为11.39G。不知道是不是文件大小导致的
4. 截图如下：
![image](https://user-images.githubusercontent.com/29659882/40785702-d99b2b86-651b-11e8-9b15-2a8894d599bb.png)

操作系统：Win10，64位。
使用proxyee-down版本：2.54

**Comment by yzh7271** [comment]
下载到百分之90多时，下载停止，上面提到方法都用了，还是没有反应。

**Comment by blueskywindystar** [comment]
@yun2673436976我也遇到了卡死再99的问题，刷新链接还是不行，按照你的方法，推出百度云账号再下载，就可以了，感谢

**Comment by lovechiyu** [comment]
卡在百分之96动不了了,进分段详情是看到第一段无法下载成功,一直是百分之0

**Comment by monkeyWie** [comment]
@inwine 是用下载器自带的解压工具解压的吗？

**Comment by SWaiter** [comment]
同样遇到这个问题，怎么解决
![Uploading image.png…]()

**Comment by nezhastudio** [comment]
蛋疼，下了一天，最后不行了，卡住了，重新下也不行。

**Comment by feixia5712** [comment]
> 蛋疼，下了一天，最后不行了，卡住了，重新下也不行。

窝已经不用他了，用这个好用IDM
