### ISSUE TITLE
出现这个报错讯息 无法下载

### ISSUE THREAD

**Issue by a5kgly** [monkeyWie/proxyee-down#247]
出现这个报错讯息 无法下载

版本2.44

{"error_code":31034,"error_msg":"pcs refuse service","request_id":9076650960502860410}

**Comment by 14SHIKE** [comment]
重新进入分享链接或者个人网盘，点击上面的下载按钮
或者重启浏览器后进入网盘
应该有效

**Comment by monkeyWie** [comment]
这是百度检测到频繁请求，然后下载的时候就会这样，可以等一会或者把要下载的文件分享出来，然后退出帐号下载
