### ISSUE TITLE
在自己的网盘里下载就会这样，是最新版本

### ISSUE THREAD

**Issue by feixia5712** [monkeyWie/proxyee-down#249]
### 相关日志
![image](https://user-images.githubusercontent.com/12670758/38291664-4fdc2768-3813-11e8-9982-b96b0254f947.png)

**Comment by 14SHIKE** [comment]
问题246有群友说明
qdcache03.开头的链接，下载到最后容易死链
你也是在个人网盘内下载的吗？

**Comment by feixia5712** [comment]
是啊，是我自己的网盘里面直接点击下载

**Comment by 14SHIKE** [comment]
先分享链接下载吧

**Comment by feixia5712** [comment]
嗯，等下我试试

**Comment by 14SHIKE** [comment]
不要登陆，直接隐私窗口打开分享链接就行

**Comment by hooboor** [comment]
下载到99%不是卡，而是只有一个段在下载而已（默认是32个），一个段的下载速度也就30、40k
