### ISSUE TITLE
Failed Resource 是什么情况

### ISSUE THREAD

**Issue by 2ndTorpSquad** [monkeyWie/proxyee-down#25]
![image](https://user-images.githubusercontent.com/35653748/35192816-1706b9ac-fe67-11e7-8fa7-b85a30db64d5.png)
![image](https://user-images.githubusercontent.com/35653748/35192817-1ff474f0-fe67-11e7-8d25-4629b94861b6.png)
按下载的话就会出 “文件太大” 的信息

**Comment by monkeyWie** [comment]
文件太大的提示在哪啊？

**Comment by 2ndTorpSquad** [comment]
@monkeyWie 卸载，重启，安装后问题不见了。应该是走眼看漏了某个步骤吧。
