### ISSUE TITLE
打开软件没有反应

### ISSUE THREAD

**Issue by liuwenlang** [monkeyWie/proxyee-down#252]
<h2>问题描述</h2>
打开软件没有反应
<h2>版本号</h2>
2.44
<h2>操作系统</h2>
Deepin(linux)
<h2>相关截图</h2>
<img src = "https://user-images.githubusercontent.com/33903129/38356955-d018b8ca-38f3-11e8-96b6-835fa88e245f.png">
<h2>相关日志</h2>
main文件夹下没有任何日志

**Comment by monkeyWie** [comment]
需要安装javafx

**Comment by liuwenlang** [comment]
问题已经解决，把openjdk卸载掉，重新装个其他的jdk就好了
