### ISSUE TITLE
下载百度云单个文件到99%停止不动，替换链接刷新依旧如此！

### ISSUE THREAD

**Issue by dis-xcl** [monkeyWie/proxyee-down#254]
**问题描述：自己网盘或他人分享链接下载单个文件到99%速度降为0就不动了，等候一小时依旧如此。其他分段都已完成，只剩下1-2个分段停住不动。地址是以d11.baidupcs.com开头的链接，复制出链接又替换为yqall02.baidupcs.com，新建任务进行刷新任务下载，还是不行，依旧在99%无反应。**

**版本号：2.44**

**操作系统：Windows7 64位**

**Comment by mengyyy** [comment]
我用其他能刷新下载链接的下载工具下完了

**Comment by jihongboo** [comment]
我也是

**Comment by ted423** [comment]
感觉问题在于99%那几段不会重新去下载

**Comment by ted423** [comment]
![image](https://user-images.githubusercontent.com/7042766/38556000-b6411252-3cfa-11e8-9e8b-a5497ea6289b.png)
还好能解压一部份文件

**Comment by zhangchao-git** [comment]
我也是有一段下载到98%， 0k/s

**Comment by liabco** [comment]
顶，我也遇到了这个问题

**Comment by falltree** [comment]
同样的问题，自己网盘下载，1.17G大小的文件，卡住了99%。再次点击下载，会弹出发现可能是相同任务，是否选择任务刷新下载，然后再下拉框内选择该任务，确定，之后还是无反应。重复几次仍然这样。

**Comment by jihongboo** [comment]
可以复制出链接，把链接前面的内容替换成d11.baidupcs.com或者yqall02.baidupcs.com，新建任务进行刷新任务下载，如果识别出的任务名是403.html的话，把替换后的地址复制到浏览器里打开去下载.
这个是开发者提供的方法,我本人试过可以.

**Comment by monkeyWie** [comment]
参考https://github.com/monkeyWie/proxyee-down/issues/246#issuecomment-378516262
