### ISSUE TITLE
下载一个20g的文件夹，完成之后解压一直报错，如图

### ISSUE THREAD

**Issue by 458722227** [monkeyWie/proxyee-down#266]
### [相关截图](
<img width="570" alt="wx20180411-150032 2x" src="https://user-images.githubusercontent.com/17487565/38601325-b65772e6-3d99-11e8-893c-be9b136455ca.png">
)
### 相关日志

**Comment by monkeyWie** [comment]
是下载到移动硬盘里了吗？

**Comment by 458722227** [comment]
没有，有可能是文件夹的原因，我最后进去全选视频下载就ok了，很好用
