### ISSUE TITLE
与Chrome浏览器谷歌访问助手插件冲突

### ISSUE THREAD

**Issue by hk519** [monkeyWie/proxyee-down#267]
### 问题描述
与Chrome浏览器谷歌访问助手插件冲突，网盘标签栏不显示proxyee-down字样，下载不能调用proxyee-down，暂停插件后可用。
### 版本号
2.44
Chrome版本 64.0.3282.186
插件版本2.3.0
### 操作系统
Windows 10 v1709

**Comment by 14SHIKE** [comment]
你可以参考教程-常见问题第一条，使用插件切换
或者
创建任务后，右键电脑右下角软件图标，关闭嗅探

**Comment by monkeyWie** [comment]
只能关闭谷歌访问插件下载了
