### ISSUE TITLE
文件名编码太长了，选项看不见了

### ISSUE THREAD

**Issue by wpapp** [monkeyWie/proxyee-down#269]
### 问题描述(必要)
文件名编码太长了，选项看不见了，底部滚动条拉到最左边，还是看不到。没法删。
### 版本号(必要)
2.44
### 操作系统(必要)
win10
### 相关截图
![151532](https://user-images.githubusercontent.com/2141609/38662047-964dc4d8-3e65-11e8-8536-6244b084f027.png)

### 相关日志

**Comment by 14SHIKE** [comment]
如果只有这一个任务
你可以重新解压软件压缩包，删掉旧的
或者
删除软件解压文件main里面的.records.inf

**Comment by monkeyWie** [comment]
可以更新到2.5
