### ISSUE TITLE
百度网盘屏蔽了程序，一直该页无法显示

### ISSUE THREAD

**Issue by heyun1989** [monkeyWie/proxyee-down#270]
貌似是从昨天开始的。加载了这个软件，百度网盘相关页面就一直无法显示，关闭这个软件就能打开网页。分享保存到自己的网盘也是如此，一打开软件就连自己网盘页面都无法打开了。
2.44
win7 32位
### 相关日志

**Comment by monkeyWie** [comment]
升级到2.44

**Comment by heyun1989** [comment]
我是下载了2.44相关之后复制粘贴到原有文件夹的。还有就是打开这个之后CPU占用率特别高基本处于80%+到90%+，请问是电脑配置问题么？

**Comment by 14SHIKE** [comment]
你需要下载2.44X86压缩包并解压
删除原来的解压文件（如果没有任务）

**Comment by heyun1989** [comment]
现在还有任务，所以是只能等待下载好了以后再重新解压么？
Ps：依然是打不开网页，之前因为出错某个20G的文件卡在70%，于是除了不停刷新直到开出网页为止都没有其他办法了么？

**Comment by Lingzy** [comment]
也遇到这个问题了，打开软件后百度云盘网页无法打开，关闭后可以打开，下载最新版2.44，win10 64位

**Comment by hooboor** [comment]
不管有没有proxyee插件都可以使用proxyee进行下载，需要安装greasyfork插件，并安装“ex-百度云盘”脚本，选择“复制压缩链接”，即可。

**Comment by wujianbotju** [comment]
Mac下打不开网页+1，应该是https证书的问题

**Comment by monkeyWie** [comment]
打不开网页的可以关闭嗅探模式，然后参考这个教程用插件设置代理https://github.com/monkeyWie/proxyee-down/blob/master/.guide/common/switchy/read.md

**Comment by heyun1989** [comment]
好的谢谢！我尝试一下。

**Comment by heyun1989** [comment]
用插件代理的话原来下载一半的会受影响么？还是要重新开始下载？

**Comment by monkeyWie** [comment]
不影响下载

**Comment by heyun1989** [comment]
谢谢！尝试中……
