### ISSUE TITLE
非常感谢开发者！！

### ISSUE THREAD

**Issue by uuuuuup1080** [monkeyWie/proxyee-down#271]
MAC很好使，非常非常感谢开发者，就是习惯用chrome，要下载就要用Safari才可以使用，不知道MAC的chrome可否直接使用？还是需要得怎么设置，想请教一下具体操作，不过Safari能用就行啦，🙏感谢作者

**Comment by monkeyWie** [comment]
chrome有用swichy插件吗？

**Comment by imdong** [comment]
https://chrome.google.com/webstore/detail/proxy-switchyomega/padekgcemlokbadohgkifijomclgjgif  这个么?

**Comment by monkeyWie** [comment]
你装了这个插件的话就看教程里这个插件的配置步骤

**Comment by uuuuuup1080** [comment]
再次表示感谢作者大大！！
