### ISSUE TITLE
无法下载文件

### ISSUE THREAD

**Issue by Shyky** [monkeyWie/proxyee-down#272]
![image](https://user-images.githubusercontent.com/10667245/38720002-267b9794-3f27-11e8-9239-aabae87ff2b8.png)

### 相关日志

**Comment by monkeyWie** [comment]
google的需要配合二级代理fq下载

**Comment by Shyky** [comment]
怎么操作

**Comment by hooboor** [comment]
已经在http://www.android-studio.org/网站测试过
1、当完全不使用代理时，http://www.android-studio.org/网站可以访问，但上图的链接根本不能访问，也就是说不管用什么方法也无法下载。
2、当打开谷歌助手时，使用chrome自带下载插件就可以直接下载，但是proxyee-down确实不行。
3、当使用fq软件后，都可以进行正常下载。
综上，作者说的没错！

**Comment by monkeyWie** [comment]
下载器设置页面里的二级代理，填写你fq的代理ip和端口
