### ISSUE TITLE
下载压缩文件完成时解压后的文件夹是空的！

### ISSUE THREAD

**Issue by Shyky** [monkeyWie/proxyee-down#273]
![image](https://user-images.githubusercontent.com/10667245/38720232-054709b8-3f28-11e8-8274-f7ab394dd80b.png)
![image](https://user-images.githubusercontent.com/10667245/38720241-12bd488c-3f28-11e8-85ac-d77dd9404541.png)

### 相关日志

**Comment by 14SHIKE** [comment]
看起来你下载的任务是单个压缩包，那用普通解压工具解压就行

**Comment by Shyky** [comment]
那这个功能有啥用

**Comment by Shyky** [comment]
一个跟多个实现起来不是一样
