### ISSUE TITLE
如何手动解压下载的zi p

### ISSUE THREAD

**Issue by foxzld** [monkeyWie/proxyee-down#274]
-->
### 相关日志

**Comment by 14SHIKE** [comment]
自动解压，可以在创建下载任务选择解压路径
![image](https://user-images.githubusercontent.com/37872513/38728125-91975026-3f41-11e8-8481-a50aa9c35b79.png)
手动解压，可以在软件左侧工具解压
![image](https://user-images.githubusercontent.com/37872513/38728187-c10e378e-3f41-11e8-9872-22f0e0d531a4.png)

**Comment by foxzld** [comment]
是mac系统，文件移动到移动硬盘后软件自带的解压无法读取移动硬盘的文件 @14SHIKE

**Comment by 14SHIKE** [comment]
你可以尝试使用旧版本，比如2.1

**Comment by monkeyWie** [comment]
可以手动输入解压路径

**Comment by foxzld** [comment]
手动输入移动硬盘文件的绝对路径及解压路径均提示不存在

**Comment by monkeyWie** [comment]
截个图看看路径怎么填的

**Comment by hooboor** [comment]
试着使用命令进行解压

**Comment by monkeyWie** [comment]
@foxzld mac的移动硬盘目录不是很懂，你能在终端里pwd看看吗

**Comment by foxzld** [comment]
![xnip2018-04-105_21-59-05](https://user-images.githubusercontent.com/5397159/38779237-3d57a30e-40f8-11e8-94d5-f172c96dcd6c.jpg)
这样子

**Comment by monkeyWie** [comment]
@foxzld 不介意的话可以加我q远程调适下
