### ISSUE TITLE
显卡GPU占用高，特别是现存占用特别多。。。

### ISSUE THREAD

**Issue by fgq1021** [monkeyWie/proxyee-down#275]
### 
这显存用的这么多，感觉像是在挖矿哎
![image](https://user-images.githubusercontent.com/18521107/38722169-9eb6c47e-3f2f-11e8-9551-6907fcf79674.png)

### 相关日志

**Comment by 14SHIKE** [comment]
你是第一个提出显存占用比较高的
看能不能复现
可以重新解压软件压缩包，下载测试显存占用情况
内存占用一般500M左右，这个已经做了限制，如果没有必要，分段数不要太高
