### ISSUE TITLE
程序存在bug！

### ISSUE THREAD

**Issue by hooboor** [monkeyWie/proxyee-down#276]
### 问题描述(必要)：
1、当文件没有下载完成，然后删除下载文件，再重新进行刚才的任务下载，会出现任务进度超过100%的情况。
2、上面情况是系统宕机导致任务中断而采取的动作，原因是，proxyee任务界面不能出来，一直在加载，就只有一个小圈在转动。我删除配置文件，后启动程序正常，然后关闭程序又恢复了配置文件，再进行上面的下载操作。
### 相关截图
![screenshot 1](https://user-images.githubusercontent.com/3361746/38763779-89b4bcba-3fd5-11e8-824b-23f70b109e03.png)

### 相关日志
日志没有保留

**Comment by 14SHIKE** [comment]
为什么不更新呢？
2.3→2.44
更新日志https://github.com/monkeyWie/proxyee-down/releases
下载地址https://github.com/monkeyWie/proxyee-down

**Comment by hooboor** [comment]
更新了怕是这个问题还存在啊。

**Comment by monkeyWie** [comment]
谢谢反馈，我会测试下这个问题的

**Comment by hooboor** [comment]
本机测试环境
win10 x64
java 1.8.0_40 x64
node.js 8.11.1 x64
maven 3.5.3
想再补充下，我测试发现使用java1.8.0_40不能正常运行程序，在任务栏的界面根本不能弹出！而且程序好像会挂死。我试着使用你包中提供的jre1.8.0_162就可以，后来我下载安装java 1.8.0_162，程序也可正常运行。在此给出反馈。

**Comment by monkeyWie** [comment]
@hooboor 你是自己编译的？

**Comment by monkeyWie** [comment]
这个问题不大，估计是没有javafx吧

**Comment by hooboor** [comment]
linux安装后出现警告信息处理方法

Apr 16, 2018 5:10:19 PM java.util.prefs.FileSystemPreferences syncWorld
WARNING: Couldn't flush system prefs: java.util.prefs.BackingStoreException: Couldn't get file lock.

1、linux系统安装方法按照作者给出的方法进行操作

2、查看文件信息
test@test-PC:~/proxyee-down-2.44$ ls -lh
total 64K
drwxr-xr-x 5 test test 4.0K Apr 16 16:40 main
-rwxr-xr-x 1 test test 58K Apr 2 16:02 proxyee-down.jar

3、执行程序时，会报一堆警告：
WARNING: Could not lock System prefs. Unix error code 0.
Apr 16, 2018 5:09:49 PM java.util.prefs.FileSystemPreferences syncWorld
WARNING: Couldn't flush system prefs: java.util.prefs.BackingStoreException: Couldn't get file lock.
Apr 16, 2018 5:10:19 PM java.util.prefs.FileSystemPreferences checkLockFile0ErrorCode
WARNING: Could not lock System prefs. Unix error code 0.
Apr 16, 2018 5:10:19 PM java.util.prefs.FileSystemPreferences syncWorld
WARNING: Couldn't flush system prefs: java.util.prefs.BackingStoreException: Couldn't get file lock.
但这并不影响程序运行。

4、出现上面的告警， 如果程序界面不能显示，请删除用户目录下的.java隐藏目录（注意java前面有个“.”号），再重新运行程序。

5、如果想不出现告警信息，请以root用户执行下面操作：
chown -R user:user /etc/.java/
chown -R user:user /etc/.java/.systemPrefs/

请参考：
http://fan.iteye.com/blog/798649
https://stackoverflow.com/questions/23960451/java-system-preferences-under-different-users-in-linux
https://docs.oracle.com/cd/E19920-01/820-5584/ahsaz/index.html(id:4719600)
http://www-01.ibm.com/support/docview.wss?uid=swg21515420

**Comment by monkeyWie** [comment]
2.5已修复进度超100%进度的问题
