### ISSUE TITLE
部分网盘资源无法下载！

### ISSUE THREAD

**Issue by EricTao2** [monkeyWie/proxyee-down#277]
### 
![_20180415020140](https://user-images.githubusercontent.com/37654992/38771191-36a06656-4051-11e8-97e6-97af27fd3f11.png)

### 日志文件里没有任何信息，特地重下了客户端确认了没有任何日志信息。

**Comment by hooboor** [comment]
你说的文件数量多是多少？是否超过1000、2000？对于普通用户，百度单次下载文件数量也是有限制的，这不能说明是下载程序的问题。

**Comment by EricTao2** [comment]
1400个文件，但是百度网盘客户端是可以下载的，应该是文件数量过多，我确认了分开可以下载，但还是希望修复下，这样下载大文件会很麻烦。

**Comment by monkeyWie** [comment]
对于批量下载来说，这个限制是百度的不能超过500个文件好像，网盘客户端下载实际上是分成1400个单文件下载
