### ISSUE TITLE
可以修改浏览器模式的默认浏览器吗

### ISSUE THREAD

**Issue by ivae09** [monkeyWie/proxyee-down#282]
### 问题描述(必要)
首先感谢作者的辛勤付出，目前 mac 下唯一能用的百度加速下载了。。。其他的都失效了。

目前环境是这样，因为使用了 ssr+surge 控制代理，直接把规则写在了 surge 里面（就不用再下个扩展控制代理切换了），所以没法使用全网模式，不过也就下载百度盘的时候用这个，平时用 firefox+aria2（webui控制）解决普通文件下载，使用基本没问题。（主要这个 java 吃内存也有点太恐怖，看了下，日常1g内存占用，不想他常驻。）

但现在有点小个问题需要解决。使用 gui 模式的话貌似多桌面不能切换。
举个例子，我的 mac 分了三个虚拟桌面1、2、3，平时主打 Firefox 在桌面1，但是启动 proxyee 它会自动跳到桌面2，不知道咋回事，然后 dock 栏设置分配给1桌面，分配无或者分配所有桌面都无法实现一个功能就是点击 dock 栏跳出界面，必须右上角点击显示才会出现（这个应该跟 java 程序有关），我用得另一个 java 程序也是这样，。

GUI 模式下东西的时候基本就这个流程，百度盘点击下载，右上角图标显示，然后再去切换到桌面 x，（或者需要手动把 gui拖到比如我的桌面1，然后点击确定才可以）是不是有点蛋疼。
所以我想到的解决办法就是使用浏览器 UI，而且我觉得这样更方便啊，浏览器都一直开着的吧。点击下载，就自动弹出个新标签管理多方便。。。看了下，这个应该跟 aria2差不多，其实就是个 webui 来控制下载。

但我现在的痛点就是，我不用 safari 啊（主要是扩展太少，还有其他原因，最终选择了长久 firefox），来管理下载还要新开一个 safari 的进程，有点不爽啊。。。所以我想怎样可以设置使用默认浏览器打开这个 webui 控制界面呢？要怎么实现，还是要不作者加入这个选项功能？
### 版本号(必要)
2.44的版本，自己编译的，因为修改了菜单栏图标~~（原作有点太大了，在 mac 下比其他图标大了一丢丢，强迫症自己改了），另外自己封装了一个 app 用来启动，解决要命令输入 root 密码的痛点，现在配合 alfred 启动也很爽快，当然也可以开机自启。
### 操作系统(必要)
macOS 10.13.4
### 相关日志

Bug 暂时没咋遇见，下载百度盘基本能跑满速，已经解决了最大的问题了。

再次感谢作者开发这么好的软件~~

**Comment by 14SHIKE** [comment]
①ui问题
浏览器ui模式显示会自动跳转到默认浏览器的
mac应该也是吧
你可以把火狐设置为默认浏览器，这样就可以webui来下载了
②内存占用问题
可以尝试在教程里OneDrive链接下载压缩包解压，内存已经被限制600M了（2.31版本-更新日志https://github.com/monkeyWie/proxyee-down/releases）
另外，封装的快速启动app很不错，可以建议作者添加这个功能

**Comment by ivae09** [comment]
照理说，也肯定应该是调用默认浏览器的啊。
但是 mac 上就不行，只能调用 safari（因为是写的 java 跨平台的，估计作者没注意这点，反正 mac 上是不行的）。我主打 Firefox 肯定是默认浏览器的啊，当然默认设置成 chrome 也不行的，还是调用 safari。

封装的 app 挺简单的，其实就是一条自动输入的带 root 密码的脚本而已。

**Comment by monkeyWie** [comment]
UI模式是浏览器的时候应该是调用系统默认浏览器打开的，估计是MAC上的问题。然后内存高的问题你可以在封装app的时候java命令行参数里指定最大堆内存。参考https://github.com/monkeyWie/proxyee-down/blob/master/start

**Comment by monkeyWie** [comment]
刚刚在mac测试了下，设置了默认浏览器的话是默认调用默认浏览器打开的
![image](https://user-images.githubusercontent.com/13160176/38909731-763c6360-42f8-11e8-8e2e-d30332061e0e.png)

**Comment by ivae09** [comment]
感谢作者的回复，我这边刚才各种测试，肯定是默认浏览器设置了 Firefox 的，但还是会调用 Safari，设置默认成 Chrome，Opera 甚至 Vivaldi （平时要开发测试兼容性，浏览器比较多😄~~）都不行，总之只会调用 Safari。有点蒙圈，不知道是什么情况。
想了想，以为是代理的问题，把所有的代理软件关闭，还是不行。。。
又想了想是不是自己编译的问题，下了你的版本还是不行。。。~
暂时真想不出是为什么了。。。个案吗哈哈。。。
后续我再想想有可能是哪的问题吧，有啥情况随时报告~

**Comment by monkeyWie** [comment]
可能是个案吧~~

**Comment by DoubleWoodH** [comment]
这个软件真的很牛逼，下载速度比 Aria2 还快不少！特别喜欢！不过也是同样的问题，我这边 mac 上的默认浏览器是 Chrome，使用浏览器方式打开还是直接就到 Safari 了
![image](https://user-images.githubusercontent.com/20528848/40524284-557ef058-600c-11e8-830e-8d80b5ce218b.png)
这是怎么原因呢？
