### ISSUE TITLE
一个软件优化的建议。

### ISSUE THREAD

**Issue by talkingbeast** [monkeyWie/proxyee-down#284]
### 问题描述(必要)
  1.希望软件下载文件夹的时候，可以获取文件夹的名称自动命名，而不是统一命名成pack.zip，这个问题在连续下载多个文件夹的时候很麻烦，命名没有意义，只有下载完成才知道到底是啥文件；
  2.需要多次下载文件夹失败的情况，看教程提示重新刷新资源，但是实际情况是很多时候下载的百度云资源是有访问密码的，添加好资源以后就关闭页面等软件下载了，现在下载失败你让我去找原来的资源连接，我很可能找不到了，加上第一个问题，下载的资源从名称上看不出来有用信息，建议软件下载的时候，把原百度云连接附上，这样失败了才好想办法。遇到很多次大文件下载失败的问题了，没辙。
 3.增加失败重试的设置；
  不知道我是不是要求太多了，作者麻烦看下。
### 版本号(必要)
2.41
### 操作系统(必要)
 win专业版 64bit
### 相关截图
![proxydown fail screenshot](https://user-images.githubusercontent.com/17403867/38918134-5c1d341a-431f-11e8-93dc-d61c1af3ff67.png)

### 相关日志
无

**Comment by monkeyWie** [comment]
更新软件吧，这个bug已经修复了
