### ISSUE TITLE
请求新功能

### ISSUE THREAD

**Issue by 380480425** [monkeyWie/proxyee-down#285]
### 问题描述(必要)
希望能增加，点击下载后自动开始下载，提升用户体验，感谢@！
### 相关日志

**Comment by 380480425** [comment]
感谢您提供2.53新的体验，非常棒！但如果能再加以改进，会更加完美，感谢！[https://github.com/monkeyWie/proxyee-down/issues/342](url)

**Comment by monkeyWie** [comment]
@380480425 不客气~ 有好的想法和建议我会加进来的

**Comment by 380480425** [comment]
@monkeyWie 感谢提供点击下载自动开始，去除了烦锁的操作，提升了用户下载体验。如果能增加下载完成后播放提示音，或者弹出提示窗口（右下角）会更加完美。因为，有些时候会出现下载到99%时停止住，光看文件夹里的文件不能确定是否完整。只有软件提示后，才可以放心的操作。避免了再次打开软件窗口确定是否下载完成100%.感谢！
