### ISSUE TITLE
v2.5问题反馈

### ISSUE THREAD

**Issue by hooboor** [monkeyWie/proxyee-down#287]
### 问题描述(必要)
1、希望下载列表名称调整为左对齐
2、在下载列表选择一个已经完成的下载文件，然后点继续任务，进度条会变成蓝色，点暂停时，进度条会变为灰色，进度为100%，实际上不会下载文件（除非删了刚下载的文件，才会重新下载），但是，后面的”打开下载目录”变为“开始（暂停）"了，如果关闭程序重新打开，操作那里会恢复显示为“删除”和“打开下载目录”。这块可能需要再添加点判断条件或者添加重复下载功能。
3、希望添加鼠标右键或中建粘贴功能
4、希望程序开始启动为前台模式。
### 相关日志

**Comment by monkeyWie** [comment]
谢谢反馈，还有前台模式是什么？

**Comment by hooboor** [comment]
软件每次会启动到任务栏右下角，每次要点图标-->显示才出来。

**Comment by 789cn** [comment]
响应速度特别慢，超过40个文件以上好想只能下载20个左右。
打开软件好想需要一分钟左右才能打开界面，也有可能是我下载列表数量优点多。
Operating System: Windows 10 专业版 64-bit (10.0, Build 16299) (16299.rs3_release.170928-1534)

**Comment by monkeyWie** [comment]
@789cn 建议不要同时下载这么多，后期肯定会做最大同时下载任务数限制的

**Comment by monkeyWie** [comment]
看了下左对齐好像更丑，第二点和第三点在2.51已经可以了，关于第四点之前一直是打开就弹出页面的，后来有人建议不要弹才取消的。。

**Comment by hooboor** [comment]
@monkeyWie 哦，那就先这样吧，反正这也不是特么重要的。
