### ISSUE TITLE
自动解压那里能否跟据后缀自动判断一下？

### ISSUE THREAD

**Issue by ted423** [monkeyWie/proxyee-down#288]
下个MP4也有自动解压感觉有点奇怪啊。

个人倒是倾向于能提供一个默认关闭自动解压的设置，个人不是很喜欢用自动解压

**Comment by wpapp** [comment]
能不能设置默认不解压？？？我每次都得选择一次，累啊。

**Comment by monkeyWie** [comment]
自动解压本身就有检测的，和后缀名没关系用字节码检测的只在检测到百度云zip文件时才自动解压，其他文件就算勾了也不会解压

**Comment by ted423** [comment]
好吧，强迫症还是会去点那么一下................

**Comment by monkeyWie** [comment]
我可能要把名字改成智能解压就好点吧 - -

**Comment by ted423** [comment]
其实改成默认不开的，需要开的去点一下，说不定就好了。。。

**Comment by monkeyWie** [comment]
因为很多人下载百度云，如果是批量下载会发现普通解压工具解压报错，所以才默认解压的。
参见：https://github.com/monkeyWie/proxyee-down#百度云解压工具

**Comment by ted423** [comment]
这我倒是不清楚，因为我还比较少用批量下载，超过4G更是基本不会从百度云下
