### ISSUE TITLE
关闭软件后无法使用IDM下载

### ISSUE THREAD

**Issue by mearz** [monkeyWie/proxyee-down#289]
### 相关日志

**Comment by ted423** [comment]
1.下什么文件....
2.检测你的代理设置

**Comment by monkeyWie** [comment]
没有任何关系

**Comment by mearz** [comment]
但确实就是这样 下载网页上的视频 以前用idm可以直接下 现在不行了 要打开软件

**Comment by mearz** [comment]
是代理的问题吗 之前下了SwitchyOmega 后来卸载了 软件可以正常使用

**Comment by ted423** [comment]
我感觉你不大理解代理工作原理哈。你关掉了这个软件，但是你代理还在工作，还是把下载的网址导到了你的代理服务器（也就是proxyee-down）上，但由于你的代理（也就是proxyee-down）关了，自然就不通了。
但这个跟proxyee-down本身没有关系，你要用，只要你取消你的代理里的规则就好。

**Comment by mearz** [comment]
那请问一下代理规则怎么改呀？

**Comment by ted423** [comment]
你在那个扩展图标上右键，然后点选项，里面应该是有引导的。自己研究一下吧。
https://github.com/FelisCatus/SwitchyOmega/wiki

**Comment by monkeyWie** [comment]
最简单的就是把代理插件成直接链接
