### ISSUE TITLE
证书无法安装（版本1.5|环境Win7sp1X86）

### ISSUE THREAD

**Issue by Dave12138** [monkeyWie/proxyee-down#29]
https://www.dropbox.com/s/jc1se6au774n7l5/bug%EF%BC%9F.gif?dl=0
链接: https://pan.baidu.com/s/1dGl6EPF 密码: bugs
操作如图
但是还是证书错误，点开证书也和没导入的界面一样

**Comment by monkeyWie** [comment]
@Dave12138 图片打不开
2.1版本已经更新，支持32位操作系统了

**Comment by Dave12138** [comment]
....可是2.1的下载页面还没更新啊QAQ
