### ISSUE TITLE
静默状态下总是弹出下载界面

### ISSUE THREAD

**Issue by Lan-megumi** [monkeyWie/proxyee-down#291]
### 问题描述(必要)
RT
今天突然出现的，之前我用的2.43版本也有类似问题
大概情况是挂机下载的时候突然弹出下载提示，文件名都是些 listArticle.do 、5.0.3.js这类文件
都大小未知、不支持分段。我用的嗅探模式是百度云的，浏览器用chrome没有加Proxy SwitchyOmega
点了取消后没多久有弹出来一个
不知道是自己校园网问题还是什么，上传被吃满了
有解决办法么

### 版本号(必要)
2.5
### 操作系统(必要)
win10 64位
### 相关日志

**Comment by monkeyWie** [comment]
把打开的网址发下

**Comment by Lan-megumi** [comment]
谷歌浏览器
浏览器诶呦打开网址，直接弹出来下载提示

**Comment by monkeyWie** [comment]
下载一个看看，然后把任务详情里的下载地址提供下

**Comment by huliang999** [comment]
我也遇到了这个问题，现在根本没法用一直弹出下载窗口
刚开始是下载各种josn文件，
后来就开始下载病毒，狂弹出窗口，跟中病毒似的

**Comment by huliang999** [comment]
@monkeyWie 弹出每个文件都是不一样的，我随便提供几个，然后弹出频率也不同
infosearch.json （这个文件出现次数最多） 
http://m.amap.com/service/valueadded/infosearch.json?poiid=B0FFHWYGZ2&cms_ver=6&uuid=ca5f4799-c854-4d4b-b1d3-372a5b29d04d

0-20.html  
http://c.m.163.com/nc/subscribe/list/T1516760167481/all/0-20.html

listArticle.do 
http://hj.pcauto.com.cn/article/listArticle.do?authorId=3757115

com.hybt.railtravel.1802221023.apk http://appdl.hicloud.com/dl/appdl/application/apk/62/62d3fec085ce4fe4a53129a8203b4d72/com.hybt.railtravel.1802221023.apk?sign=mw@mw1524227694885

弹出规律是这样的，
1除了第一个文件每次都有，其他文件每次打开软件都是会变化的，并且这些文件会一直重复弹出
2 一开始是只弹出 .json .do 这种文件，弹出频率较低，选择下载是没有速度的，也就是下载不下来。
3 一段时间之后开始弹出若干APK文件，这些文件是可以下载的，下载的文件查过是没毒的。然后弹出频率开始变高，最高一秒连续弹出几个窗口。

**Comment by 14SHIKE** [comment]
huliang999
你应该是设置错误了，如果你真的嗅探百度云，就不会出现上述问题
经过测试，嗅探全网，会出现你提到的问题：但是，嗅探百度云，并没有出现上述问题
如果你使用插件，请用pd自动切换（看教程）或者电脑右下角-右键软件图标-嗅探百度云

**Comment by huliang999** [comment]
@14SHIKE 关键是我选择的就是嗅探百度云，而且我还尝试过关闭嗅探，依旧出现问题，我没有使用任何插件，就只是双击应用程序。。。

**Comment by hooboor** [comment]
@huliang999 方便的话，留个qq，我远程给你看下，看能不能帮你解决

**Comment by monkeyWie** [comment]
把你ie的代理设置截图看看

**Comment by huliang999** [comment]
@monkeyWie  IE代理设置应该没问题吧
![snipaste_2018-04-22_15-38-50](https://user-images.githubusercontent.com/38585525/39092599-1d83ff68-4644-11e8-948c-2ca7d91b3161.png)

**Comment by monkeyWie** [comment]
把代理都关了看看还会不会弹下载任务，按理说百度云嗅探模式只针对baidu域名的请求啊

**Comment by huliang999** [comment]
@monkeyWie 关闭所有代理，软件嗅探模式选择关闭，依旧弹出

**Comment by monkeyWie** [comment]
不打开浏览器也会出现吗？是不是你有运行别的软件，然后用了下载器的代理导致下载器嗅探到了下载请求

**Comment by huliang999** [comment]
@monkeyWie 电脑重启，关闭除杀毒软件之外的所有程序，关闭浏览器所有插件。打开软件，依旧弹出，真是搞不明白为什么。 看进程也没有可疑的东西。

**Comment by monkeyWie** [comment]
你是不是手机上设置了这个代理啊？

**Comment by lxfly2000** [comment]
弹下载框是不是老版本IE的下载框？如果是的话这可能是Win10的bug，我这里用Adobe creative cloud 的时候也有这种情况

**Comment by monkeyWie** [comment]
换个代理端口下载就好。
