### ISSUE TITLE
一个 Bug，一个建议。

### ISSUE THREAD

**Issue by tlerbao** [monkeyWie/proxyee-down#294]
### 问题描述(必要)
 > Bug：工具的 Tab 会重复 add，如下图。

![1](https://user-images.githubusercontent.com/20442232/39080086-630ff8ba-455a-11e8-8bd9-ac5ebadc3182.png)

> 建议：能不能换个图标或优化一下，强迫症有点受不鸟。毛边的都。

![2](https://user-images.githubusercontent.com/20442232/39080091-73ef1b98-455a-11e8-9751-1e97220717d9.png)
### 版本号(必要)：

2.5

### 操作系统(必要)：

Win10

**Comment by monkeyWie** [comment]
https://github.com/monkeyWie/proxyee-down/issues/299
