### ISSUE TITLE
使用后，无法打开百度云相关网页

### ISSUE THREAD

**Issue by JiataoWen** [monkeyWie/proxyee-down#296]
运行了程序后，就没有办法链接上百度云的下载页面
浏览器用的是chrome， 不知道有没有人出现我在这个情况

**Comment by MicroH** [comment]
我遇到了相同的情况，打开软件后，百度云网页无法打开

**Comment by MicroH** [comment]
已解决：
右键软件图标，嗅探模式-->全网，重新打开网页，OK

**Comment by monkeyWie** [comment]
只下百度云的话建议就切百度云嗅探

**Comment by HJacco** [comment]
调整嗅探模式也没用

**Comment by HJacco** [comment]
![qq 20180422182825](https://user-images.githubusercontent.com/11569147/39095654-841d5616-4676-11e8-8fe5-497fbad668cc.png)

**Comment by HJacco** [comment]
日志文件是空的

**Comment by monkeyWie** [comment]
@HJacco  看看常见问题第一个

**Comment by AcquireKnown** [comment]
软件运行之后，谷歌能够正常刷新百度云，但是火狐却是死活都出不来页面，不知道是什么原因，证书也已经重新安装了

**Comment by 14SHIKE** [comment]
可以把证书都删掉，win+r，certmgr.msc，受信任的根证书颁发机构，proxyeeroot
删掉后，删掉旧的软件解压文件，重新解压压缩包
火狐导入证书，注意别忘了勾选
