### ISSUE TITLE
No menu on Debian 9 with Gnome

### ISSUE THREAD

**Issue by jinyu121** [monkeyWie/proxyee-down#297]
### 问题描述(必要)
After startup, the icon at notice bar is blank. Only a Tip box tells you that the proxyee-down is up. After closing this box, I can do nothing. I click the Icon with left and right button, no menu shown.
So now, I can not switch on/off the sniffer mode, or do what you said in the tutorial. 

I set the proxy to localhost:9999 on Chrome by SwitchOmega, it shows `no data received`, means the proxy is down.

I do not want to add CA.......

### 版本号(必要)
2.5

### 操作系统(必要)
Debian GNU/Linux 9 (stretch) x64
Gnome 3.22.2

### 相关截图
![2018-04-22 10-00-24](https://user-images.githubusercontent.com/7346324/39090567-d296e9c2-4614-11e8-84b8-f29e3f9066b9.png)

### 相关日志
The log file(`main/log/error.2018-04-22.log`) is empty.... 

---

Well, I modified the config.ini, change snifMode to 0. It seems that the proxy worked, but the UI in BaiduCloud crashed, without adding CA. I do not want to add that. While the ProxyeeDown UI and menu still can not show.

**Comment by monkeyWie** [comment]
安装了javafx吗？如果gui不行的话可以修改config.inf的uiModel为2，即浏览器模式。还有sniffModel为3时是关闭嗅探

**Comment by jinyu121** [comment]
@monkeyWie 
openjdk-8-jre: 8u162-b12-1~deb9u1
openjfx: 8u111-b14-1
所以是安装有javafx的，uiModel=2依然不行。

sniffMode=3百度盘的UI依然全乱，勾选东西下载就提示这个东西

![2018-04-22 15-33-29](https://user-images.githubusercontent.com/7346324/39092538-940475de-4642-11e8-9b2d-d89e44f6ce5e.png)

**Comment by monkeyWie** [comment]
证书没安装吧？https://github.com/monkeyWie/proxyee-down/blob/master/.guide/common/ca/read.md

**Comment by monkeyWie** [comment]
linux上嗅探模式其实并不没有什么用，至在mac和Windows上生效

**Comment by hooboor** [comment]
@jinyu121 @monkeyWie 

测试环境：
Debian 9.4 x64
oracle jdk1.8.0_171 x64

经过测试，这种情况可能是gnome本身问题导致，这个网络上有讨论，有兴趣的可以搜索javaEmbeddedFrame gnome。
1、在gnome环境（v2、v3都进行了测试），在程序执行时，在gnome桌面只会出现javaEmbeddedFrame以及托盘黑图标（而且不能显示真正的图标），javaEmbeddedFrame（空白界面）可以鼠标右键最大、最小、不能关闭（没有任何菜单界面及菜单选项）只能ctrl+c强制关闭；托盘黑图标不能进行任何操作。
2、在LXDE、Cinnamon环境上进行了测试，程序界面完全可以显示（没有进行下载功能测试）。

**Comment by monkeyWie** [comment]
看看chrome的network选项，是不是有什么资源加载失败了

**Comment by hooboor** [comment]
@monkeyWie 在gnome环境，ui界面和浏览器界面都不能显示。
