### ISSUE TITLE
一个疑问

### ISSUE THREAD

**Issue by TooYoungTooSimp** [monkeyWie/proxyee-down#298]
### 问题描述(必要)
请问`proxyee-down.jar`和`main/proxyee-down-core.jar`这两个文件有何区别？  
用`java -jar`运行后效果看起来完全相同。
`proxyee-down.jar`多做了哪些操作呢？
### 版本号(必要)
2.5
### 操作系统(必要)
Windows 10 16299.371

**Comment by monkeyWie** [comment]
主要是做在线升级
