### ISSUE TITLE
每次点击“工具”都会多出一个工具选项卡

### ISSUE THREAD

**Issue by NagaseYami** [monkeyWie/proxyee-down#299]
与其说是一个BUG，倒不如说这是不是一个失误。
因为其他的选项卡（任务，设置，关于，打赏）若已存在的话是不会新建一个选项卡的，唯独“工具”是每次点击都会新建一个选项卡。觉得有点奇怪，就来汇报一下。
**如果作者本来就打算做成这种样式的话，那就是我的误解了，请直接关闭这个Issues。**

姑且按照格式提交一下
版本号 
2.5
操作系统 
win7 SP1
截图
![gif](https://user-images.githubusercontent.com/23649435/39092184-ca1b3324-4642-11e8-854f-cd43b57dcd62.gif)
由于不是bug，所以log文件里啥都没有。

**Comment by monkeyWie** [comment]
确实特意这样的。
