### ISSUE TITLE
编译失败

### ISSUE THREAD

**Issue by wanwanpp** [monkeyWie/proxyee-down#3]
npm run install运行不走呢

**Comment by monkeyWie** [comment]
有异常日志吗

**Comment by wanwanpp** [comment]
npm ERR! missing script: install

**Comment by akillcool** [comment]
Same issue.
![image](https://user-images.githubusercontent.com/9277617/33924710-3bc56356-e012-11e7-97b0-39e93edb6471.png)

**Comment by akillcool** [comment]
still have error after updated my nodejs version:
![image](https://user-images.githubusercontent.com/9277617/33925505-114d2bce-e015-11e7-822b-55bde5899bb1.png)

and here is the log file again:
```
0 info it worked if it ends with ok
1 verbose cli [ '/usr/bin/node', '/usr/bin/npm', 'run', 'install' ]
2 info using npm@5.5.1
3 info using node@v8.9.3
4 verbose stack Error: missing script: install
4 verbose stack     at run (/usr/lib/node_modules/npm/lib/run-script.js:151:19)
4 verbose stack     at /usr/lib/node_modules/npm/lib/run-script.js:61:5
4 verbose stack     at /usr/lib/node_modules/npm/node_modules/read-package-json/read-json.js:115:5
4 verbose stack     at /usr/lib/node_modules/npm/node_modules/read-package-json/read-json.js:402:5
4 verbose stack     at checkBinReferences_ (/usr/lib/node_modules/npm/node_modules/read-package-json/read-json.js:357:45)
4 verbose stack     at final (/usr/lib/node_modules/npm/node_modules/read-package-json/read-json.js:400:3)
4 verbose stack     at then (/usr/lib/node_modules/npm/node_modules/read-package-json/read-json.js:160:5)
4 verbose stack     at /usr/lib/node_modules/npm/node_modules/read-package-json/read-json.js:280:12
4 verbose stack     at /usr/lib/node_modules/npm/node_modules/graceful-fs/graceful-fs.js:78:16
4 verbose stack     at FSReqWrap.readFileAfterClose [as oncomplete] (fs.js:511:3)
5 verbose cwd /home/koi/Apps/proxyee-down/view
6 verbose Linux 4.10.0-42-generic
7 verbose argv "/usr/bin/node" "/usr/bin/npm" "run" "install"
8 verbose node v8.9.3
9 verbose npm  v5.5.1
10 error missing script: install
11 verbose exit [ 1, true ]
```

**Comment by monkeyWie** [comment]
@wanwanpp @akillcool 
试下 **npm install**

**Comment by akillcool** [comment]
使用npm install没有问题，npm run build也成功了，然后返回根目录执行mvn clean package报错如下：
![image](https://user-images.githubusercontent.com/9277617/33927663-1b2f95ce-e01e-11e7-9ee3-40a1a3710421.png)

**Comment by monkeyWie** [comment]
@akillcool 
因为这个项目是依赖[proxyee](https://github.com/monkeyWie/proxyee)代理服务器核心，还没有把包上传到maven中央仓库，所以还需要自己本地install一下
```
git clone https://github.com/monkeyWie/proxyee.git
cd proxyee
mvn clean install
```

**Comment by akillcool** [comment]
@monkeyWie 感谢！
编译没有问题了，Windows上面跑也没有问题，但是在ElementaryOS Loki上（基于Ubuntu 16.04）安装证书却出了问题。

分别尝试了在Chrome中安装证书和直接在系统中安装，但是并没有效果。

**Comment by monkeyWie** [comment]
@akillcool 
你是怎么在Ubantu上安装证书的呢
我刚刚查了下,不知道你是不是这样安装的，我自己电脑上的CentOS测试过是可以用的
```
cp ca.crt /usr/local/share/ca-certificates/proxyee-root.crt 
update-ca-certificates
```

**Comment by akillcool** [comment]
@monkeyWie 是这样安装的
![image](https://user-images.githubusercontent.com/9277617/33938930-35bb349a-e044-11e7-854f-bf033d246d68.png)

我还尝试了在Chrome中导入证书
![image](https://user-images.githubusercontent.com/9277617/33938775-9f4e88cc-e043-11e7-9240-19344a9e6204.png)

**Comment by monkeyWie** [comment]
@akillcool 
明天到公司我装个虚拟机看看吧

**Comment by akillcool** [comment]
@monkeyWie 非常感谢！
如果可以的话，也请尝试一下ElementaryOS～
https://sgp1.dl.elementary.io/download/MTUxMzE2OTE4NQ==/elementaryos-0.4.1-stable.20170814.iso

**Comment by monkeyWie** [comment]
@akillcool 
就是在下ElementaryOS，祭出自己的下载器去下载然而它不支持分段下载！慢慢下吧，有进展了就告诉你

**Comment by monkeyWie** [comment]
突然想起了百度可以下载磁力链接啊，还是起飞了 哈哈
![image](https://user-images.githubusercontent.com/13160176/33940233-2f2ebdcc-e049-11e7-8c78-edd7ee74d144.png)

**Comment by akillcool** [comment]
@monkeyWie 666

**Comment by monkeyWie** [comment]
@akillcool 
终于定位到问题了！已修复，详见：https://github.com/monkeyWie/proxyee/commit/e494913057fc65316965b213aaf27cf80233f01a

把proxyee重新pull再打个本地包吧

**Comment by akillcool** [comment]
@monkeyWie 666
给大佬疯狂打call～
