### ISSUE TITLE
多层文件夹下载出错

### ISSUE THREAD

**Issue by loopbless** [monkeyWie/proxyee-down#304]
### 
![image](https://user-images.githubusercontent.com/16011400/39163045-3953b7de-47ab-11e8-98c3-f04f4088742e.png)

### 
[error.2018-04-24.log](https://github.com/monkeyWie/proxyee-down/files/1940651/error.2018-04-24.log)

**Comment by hooboor** [comment]
@loopbless 
能发下链接吗？我想测试以下。

**Comment by monkeyWie** [comment]
分享出去下载试试

**Comment by loopbless** [comment]
文件数量有限制吗？最大可以包含多大，我刚才看了一下，我刚才下载的文件是3000多个

**Comment by monkeyWie** [comment]
@loopbless 最大好像是500吧，具体我也没试过

**Comment by loopbless** [comment]
@monkeyWie 这个可以解决吗？

**Comment by monkeyWie** [comment]
@loopbless 这是百度服务器的限制，解决不了 分批下载吧
