### ISSUE TITLE
开启代理之后，百度的验证码刷新不出

### ISSUE THREAD

**Issue by homever** [monkeyWie/proxyee-down#310]
有什么解决办法么？

![image](https://user-images.githubusercontent.com/3777914/39223589-77c2843a-4875-11e8-94ae-e17a51993caa.png)

**Comment by homever** [comment]
代理就跟manual 一样
![image](https://user-images.githubusercontent.com/3777914/39304517-82f5c570-498c-11e8-8b4f-034e99bcf4ff.png)

另外，百度的验证码网址，应该也被ProxyeeDown代理了，这难道是打不开的原因？
https://pan.baidu.com/genimage?**********

**Comment by monkeyWie** [comment]
我测试过验证码是可以正常加载的，可能和你的网络环境有关吧。有没有翻墙然后用的什么宽带呢？

**Comment by 14SHIKE** [comment]
可能是你使用别的网盘下载脚本了，试试关掉

**Comment by wpapp** [comment]
火狐有个插件：[哔度娘网盘](https://addons.mozilla.org/zh-CN/firefox/addon/%E5%93%94%E5%BA%A6%E5%A8%98%E7%BD%91%E7%9B%98/)
下载文件夹或者多个文件的压缩包，pack.zip
然后手动添加到proxyee-down下载，速度3MB左右。
我下过超过10GB的文件，7MB左右，似乎文件越大，下载速度越快。

**Comment by homever** [comment]
@14SHIKE 多谢，是我很早之前添加的一个百度盘script...已经找到缘由。
@monkeyWie 谢谢dev
