### ISSUE TITLE
Ubuntu下chrom不能添加证书，firefox下载时报错

### ISSUE THREAD

**Issue by appleren** [monkeyWie/proxyee-down#312]
### 版本号(必要)
Firefox Nightly
61.0a1(2018-04-25)(64-bit)
### 操作系统(必要)
ubuntu 14.04
### 相关截图
![screenshot from 2018-04-26 14 42 38](https://user-images.githubusercontent.com/13266832/39289846-383725d2-4960-11e8-8ad1-7868ad4e2744.png)
![screenshot from 2018-04-26 14 43 05](https://user-images.githubusercontent.com/13266832/39289847-39136614-4960-11e8-8cfa-3632988e78f3.png)
### 相关日志
没有生成日志文件

**Comment by appleren** [comment]
发现是要下载的文件夹里文件太多，超过1000个的问题。能不能增加点功能，如果文件太多，则自动分批下载？

**Comment by monkeyWie** [comment]
这个是百度云的限制，参考https://github.com/monkeyWie/proxyee-down/issues/304
