### ISSUE TITLE
求问proxyee-down客户端ui使用什么技术

### ISSUE THREAD

**Issue by PentonBin** [monkeyWie/proxyee-down#313]
### 问题描述(必要)
求问proxyee-down客户端ui使用什么技术

### 版本号(必要)
2.51

### 操作系统(必要)
Ubuntu（这不重要）

### 相关截图
无

### 相关日志
无

**Comment by PentonBin** [comment]
希望得到指导，谢谢～

**Comment by ted423** [comment]
不是java么

**Comment by wangpeiyong** [comment]
gui+vue吧

**Comment by monkeyWie** [comment]
前端是用vue.js写的，gui只是内嵌了个浏览器访问而已

**Comment by PentonBin** [comment]
谢谢
