### ISSUE TITLE
高分屏托盘菜单字体太小, 最大同时下载数, 自动解压设置

### ISSUE THREAD

**Issue by WanderMax** [monkeyWie/proxyee-down#314]
### 问题描述(必要) 
1. 高分屏托盘菜单字体太小, 见截图
2. 增加最大同时下载数设置
3. 自动解压可以自定义关闭, 每次下载压缩包分卷都谁自动把自动解压打开
### 版本号(必要) 
2.51
### 操作系统(必要) 
Win10 1709
### 相关截图 
![20180426195213](https://user-images.githubusercontent.com/15909056/39304327-e981f652-498b-11e8-8f9f-e09abf439dd9.png)
### 相关日志 
NA

**Comment by monkeyWie** [comment]
关于解压的问题看这个https://github.com/monkeyWie/proxyee-down/issues/288
字体的话先将就用吧，对高分屏的字体大小处理也没有经验
