### ISSUE TITLE
突然无法打开所有网页

### ISSUE THREAD

**Issue by wjk199511140034** [monkeyWie/proxyee-down#316]
### 操作系统 win 10 1703
打开proxyee-down软件（默认端口9999），设置浏览器代理为127.0.0.1:9999，
然后就打不开所有网页了，三种嗅探模式都试了全都不行
重启软件，重启浏览器，重启电脑全都试过，问题100%重现
。
这个设置我一直没变过，以前一直是这么用proxyee-down，大概有一个多月了，今天突然出现这个问题，很无解，现在只能通过油猴脚本获取下载链接了，十分麻烦
日志文件我也打开看了，空白的.。证书也导入了，我用的是chrome内核的浏览器不是火狐
求大佬给分析分析，我实在是想不出来为什么了。。。

**Comment by monkeyWie** [comment]
浏览器打不开的界面截图看看

**Comment by wjk199511140034** [comment]
@monkeyWie 
![default](https://user-images.githubusercontent.com/12637627/39390834-0a2d2eb6-4acd-11e8-9f4c-2e270e4276f9.PNG)

**Comment by hooboor** [comment]
为什么要设置浏览器代理为127.0.0.1:xxxx？你这样设置网当然上不去了。

**Comment by wjk199511140034** [comment]
哎，找到问题所在了，昨天插件更新了，代理莫名其妙变成了socks5，改回http就好，，，
