### ISSUE TITLE
文件快下完时突然中断，无法继续

### ISSUE THREAD

**Issue by FQFQzzy** [monkeyWie/proxyee-down#317]
### [error.2018-04-27.log](https://github.com/monkeyWie/proxyee-down/files/1956489/error.2018-04-27.log)

![default](https://user-images.githubusercontent.com/13757220/39382525-0df24dae-4a66-11e8-9379-ed8012fc7611.PNG)

**Comment by monkeyWie** [comment]
参考https://github.com/monkeyWie/proxyee-down/issues/246#issuecomment-378516262
