### ISSUE TITLE
二级代理对下载无效

### ISSUE THREAD

**Issue by zhongfly** [monkeyWie/proxyee-down#320]
### 问题描述(必要)
二级代理无效，设置代理并保存后，代理并未生效，下载不经过代理，而是直接连接
### 版本号(必要)
2.52（2.5及之后版本均存在此问题）
### 操作系统(必要)
windows7

**Comment by monkeyWie** [comment]
我刚刚测试了下2.52版本下并没有发现你说的问题。
![image](https://user-images.githubusercontent.com/13160176/39397581-2f245a16-4b34-11e8-8934-e86425469cf5.png)

![image](https://user-images.githubusercontent.com/13160176/39397574-181b6260-4b34-11e8-8b22-cf7811b9d523.png)

**Comment by zhongfly** [comment]
我的测试环境为proxyee-down（设置二级代理127.0.0.1:1083）＞ss本地代理＞ipv6连接

断开ipv4后，网页全部走ss代理，能正常打开，但proxyee-down无法下载，网页（走poxyee-down代理）无法打开
连接ipv4后，proxyee-down可以下载，ss无进出流量
