### ISSUE TITLE
百度云点击下载就提示发生错误

### ISSUE THREAD

**Issue by liMfan** [monkeyWie/proxyee-down#324]
### 相关截图
![snipaste_2018-04-28_23-02-47](https://user-images.githubusercontent.com/35243533/39402706-8fe26072-4b99-11e8-95d3-0fd8bcade526.png)
![snipaste_2018-04-28_23-02-58](https://user-images.githubusercontent.com/35243533/39402707-91816c20-4b99-11e8-81a0-b286b9cdedde.png)
![snipaste_2018-04-28_23-03-07](https://user-images.githubusercontent.com/35243533/39402708-92891618-4b99-11e8-98c5-22dcbee0cb8a.png)

### 相关日志

**Comment by 14SHIKE** [comment]
看这里https://github.com/monkeyWie/proxyee-down/blob/master/.guide/common/switchy/read.md
插件使用教程

**Comment by liMfan** [comment]
不是因为文件夹文件太多了,另一台电脑就可以下载

**Comment by liMfan** [comment]
对的 因为文件夹文件太多,总共有400多个g,我进去单独选择一个90g左右的下载就没问题了

**Comment by monkeyWie** [comment]
文件太多了百度云会有限制，进去分批下载吧
