### ISSUE TITLE
新版本下被限速

### ISSUE THREAD

**Issue by tsktfn** [monkeyWie/proxyee-down#329]
### 问题描述(必要)
之前一直用的是2.21版本，3月初的时候是可以达到10M的峰值，到4月以后峰值一般只有3M了，由于有时候有下载一部分以后不开始新的分段下载的问题，曾尝试更新到2.44版本，结果峰值只有300kb了，又换回了2.21使用速度快的旧版本，今天尝试了2.52版本后峰值依然只有300kb左右。根据常见问题，分段尝试过32-128，速度没有太大区别，下载内容是视频集，应该也符合了多内容打包下载的要求，但是新版本下速度依然很慢。
### 版本号(必要)
2.21   2.44   2.52
### 操作系统(必要)
W10家庭中文版
### 相关截图
![image](https://user-images.githubusercontent.com/38458198/39462961-c538ef7a-4d47-11e8-97ed-5d6ae3ba23f3.png)

### 相关日志
[error.2018-05-01.log](https://github.com/monkeyWie/proxyee-down/files/1963089/error.2018-05-01.log)

**Comment by tsktfn** [comment]
尝试结果速度并没有提高。

**Comment by hooboor** [comment]
@tsktfn 
我使用2.44、2.50、2.51没出现过你这样的情况

**Comment by Kevinhhy** [comment]
2.52版本  同样出现被限速问题

**Comment by VainAnts** [comment]
我之前用旧版本速度也很快，昨天更新到新版本之后，下载速度被百度服务器限速10k/s。

**Comment by monkeyWie** [comment]
参考https://github.com/monkeyWie/proxyee-down/issues/323
