### ISSUE TITLE
手动添加任务，下载地址 非默认80端口提示超时

### ISSUE THREAD

**Issue by yoyo1001** [monkeyWie/proxyee-down#341]
2.5.3
手动添加任务，下载地址 非默认80端口提示超时

**Comment by monkeyWie** [comment]
地址能提供下吗，是http还是https的？

**Comment by yoyo1001** [comment]
您好，我遇到的是http的，给您两个下载地址供测试
http://dx3.wishdown.com:16808/soft/99dianwan2013_sdytuiguang.zip
http://wz.7edown.com:808/green/sanyezlzs.rar

**Comment by monkeyWie** [comment]
确实是个bug，等新版本修复下吧

**Comment by monkeyWie** [comment]
2.54已修复这个问题
