### ISSUE TITLE
百度云大文件下载，断点重传功能失效

### ISSUE THREAD

**Issue by cuijinquan** [monkeyWie/proxyee-down#347]
### 相关日志

版本号：2.53 
操作系统：WIN10
问题描述:
    百度云打包下载60G文件，下载了二天，下载到99%还差一点就下载完成了，突然断电，重新来电后，开电脑proxyee-down重新自动启动，然后下载的这个60G文件进度变成了0，点下载，就重新从0开始下载，断点功能失效，晕死。

**Comment by ted423** [comment]
目测突然断电造成了文件损坏

**Comment by monkeyWie** [comment]
支持断点下载的，估计是断电导致记录文件没写完整
