### ISSUE TITLE
解压提示完成后，又点了一次确定，貌似是继续解压了？是重新覆盖了吗？

### ISSUE THREAD

**Issue by binext** [monkeyWie/proxyee-down#35]
1. 
    2.03，解压提示完成后，没注意又点到了确定，然后又进入解压的状态了，不知这样操作是会覆盖之前解压的还是？建议进行更改，或者完成后清空解压文件和解压目录，或者做成任务列表，显示解压完成的任务。
2. 
    现在云解压看不到进度状态，不知能否有办法实现？

**Comment by monkeyWie** [comment]
@binext 
解压的进度下个版本会做的
还有现在已经更新2.1了，最好更新到2.1版本也修复了一些百度云解压的bug

**Comment by binext** [comment]
@monkeyWie  THX，刚更新了2.1了。 
发现设置完默认分段数保存后，退出再运行，又恢复成16了。

**Comment by monkeyWie** [comment]
@binext 
谢谢反馈，以修复会再下个版本中更新
