### ISSUE TITLE
能否在“下载详情”中增加文件名称

### ISSUE THREAD

**Issue by brucewangcn** [monkeyWie/proxyee-down#350]
### 问题描述(必要)
批量下载中有个文件下载失败，能否在“下载详情”中显示文件名称，便于个别处理
### 版本号(必要)
2.52
### 操作系统(必要)
win7 64位

### 相关截图
![default](https://user-images.githubusercontent.com/39020077/39670298-f1d69ba2-50f0-11e8-931a-e217430a6055.PNG)

### 相关日志

**Comment by ted423** [comment]
这个下载的是zip文件的分段，不是单独的文件
