### ISSUE TITLE
Linux下希望能够实现headless运行服务

### ISSUE THREAD

**Issue by meoow** [monkeyWie/proxyee-down#351]
### 问题描述(必要)

在通过ssh连接服务器，在命令行运行

```sh
jre1.8.0_171/bin/java -jar proxyee-down/proxyee-down.jar
```

等待大约1秒后，会返回交互，命令的返回值为0，终端没有任何文本输出。

log文件夹下，未产生任何日志文件。

从Oracle下载的JRE 8和源里的OpenJDK 9都试了，同样地问题。

我觉得是不是因为我没有运行桌面环境的缘故？如果是的话我希望能有headless运行方式，这样作为一个提供网络服务的工具更合理些。

### 版本号(必要)

2.52

### 操作系统(必要)

Ubuntu 16.04.4 LTS 4.13.0-39-generic x86_64

默认为multi-user.target，无X服务运行

**Comment by monkeyWie** [comment]
headless现在还不支持
