### ISSUE TITLE
下载页面打不开

### ISSUE THREAD

**Issue by waterlogithub** [monkeyWie/proxyee-down#36]
v2.1 32位版本，已安装证书、打开软件，switchyomega插件切换到proxydown情景模式，但下载页面打不开。为什么呢？

![001](https://user-images.githubusercontent.com/22746557/35279004-b4abe7b0-0086-11e8-8729-225f19b7413d.PNG)

>
![pd](https://user-images.githubusercontent.com/22746557/35279239-6ebbadac-0087-11e8-9a66-c679bc4a3543.PNG)

>
![11](https://user-images.githubusercontent.com/22746557/35278954-8f935bb6-0086-11e8-8fa8-dae487b67b60.png)

**Comment by monkeyWie** [comment]
是不是更新了版本。按crlt+f5刷新下，之前的旧版本页面有做缓存。

**Comment by waterlogithub** [comment]
@monkeyWie 现在可以嘞，谢谢你！
