### ISSUE TITLE
下载速度显示有误？

### ISSUE THREAD

**Issue by 1357310795** [monkeyWie/proxyee-down#367]
### 问题描述(必要)
软件里显示下载速度与360显示相差过大
### 版本号(必要)
2.53
### 操作系统(必要)
win7 x64
### 相关截图
![qq 20180511172558](https://user-images.githubusercontent.com/35869804/39917819-49bc027c-5541-11e8-86ee-1419bd00a021.png)
### 相关日志
[error.2018-05-11 - 副本.zip](https://github.com/monkeyWie/proxyee-down/files/1994761/error.2018-05-11.-.zip)

**Comment by monkeyWie** [comment]
以下载器的为准就好了
