### ISSUE TITLE
Error 31426

### ISSUE THREAD

**Issue by alexanderpak307** [monkeyWie/proxyee-down#370]
### 问题描述(必要)
点击下载按钮之后在新的页面提示{"error_code":31426,"error_msg":"hotlinking forbidden , hitcode:113","request_id":8836380322809864659}
### 版本号(必要)
2.53
### 操作系统(必要)
Windows 7
### 相关截图
<img width="960" alt="2" src="https://user-images.githubusercontent.com/39229481/39963330-ed1cfec6-569a-11e8-9daa-4b3187c1c2b7.png">
### 相关日志
None

**Comment by ted423** [comment]
装脚本了么？

**Comment by alexanderpak307** [comment]
问题已解决，初步认为是文件名问题。
