### ISSUE TITLE
2.53版本不能通过switchyomega代理百度云，原因是没有本地端口

### ISSUE THREAD

**Issue by kamo2020** [monkeyWie/proxyee-down#371]
### 问题描述(必要)
通过教程设置了switchyomega来代理百度云，几种方法都试过了，比如设置自动切换规则、直接全局代理，自定义端口，都没法打开百度云网页。后来发现是没有本地端口，我换了旧的版本2.51，则可以正常使用。
### 版本号(必要)
2.53
### 操作系统(必要)
windows10 1803
### 相关截图
![default](https://user-images.githubusercontent.com/33853879/39975722-e229fadc-5762-11e8-9791-6bc0c5819506.png)
这个图是2.51版本的，在性能监视器里能看到软件的端口，如果是2.53则没有这个端口。
### 相关日志

**Comment by monkeyWie** [comment]
代理端口是9999啊，你看看是不是被占用了

**Comment by kamo2020** [comment]
我知道默认的是9999，我也怕端口占用才改的9923,switchyomega里也改了。

我刚才重新下载了2.53版本试了试，不知道为啥正常了，侦听端口那里也有了。

但是我在另一台电脑上试了下，第一次启动没有9999端口,和我之前碰到的问题一样，也没有日志输出。安装证书后重新启动了一下，又正常了(难道是因为证书的问题吗)。

然后我把电脑里安装的证书删了，启动了一下，没有9999端口，安装后又有了9999端口。

http://ww1.sinaimg.cn/large/6762c771ly1fre6chzwtlj20x00kvq94.jpg
http://ww1.sinaimg.cn/large/6762c771ly1fre6ctin57j20wa0klagd.jpg
不能传图了

看来是因为第一次启动没有安装证书导致的问题。

总之我现在使用没什么问题了，不好意思了。

**Comment by monkeyWie** [comment]
好吧 没问题就行
