### ISSUE TITLE
批量下载文件顺序有问题

### ISSUE THREAD

**Issue by blank-hudson** [monkeyWie/proxyee-down#372]
问题描述
在这个地址 ：https://pan.baidu.com/s/1nv1zhUh 密码: r96r ，批量下载了一些电视剧，用在线预览打开其中一集，视频内容和下载之后相同文件名的视频不一样。。。
我删除了全部文件又重新下载了一整季，这一次跟上次下载到的又不一样
版本号
2.53
操作系统
windows10 1803

**Comment by monkeyWie** [comment]
用什么软件解压的？

**Comment by blank-hudson** [comment]
没解压，选择了若干个文件直接批量创建的任务。。。
因为软件没有最大下载任务数量的限制，所以我每次只创建6个任务。。发现只有同时创建的这一组文件之间会相互混淆。。。

**Comment by monkeyWie** [comment]
批量下载用的px那个插件吗？

**Comment by blank-hudson** [comment]
是的，https://github.com/lihaoyun6/px-baiduyunpan 这个插件，0.10.6版本

**Comment by monkeyWie** [comment]
这个插件可能有bug，把名字弄错了
