### ISSUE TITLE
Mac用户的请求

### ISSUE THREAD

**Issue by max-yeah** [monkeyWie/proxyee-down#38]
Mac配置的时候，下载好proxyee和java的相关内容，安装好证书了。软件界面可以在Safari标签页打开。
但是在浏览器下载的时候仍然无法使proxyee-down响应，希望能出一个Mac配置教程
感谢啦

**Comment by TifosiRay** [comment]
@max-yeah 我弄好了 只要用switchyomega代理百度云盘就可以

**Comment by monkeyWie** [comment]
@max-yeah mac的教程群里有文档，你这个情况是因为没有切换代理

**Comment by monkeyWie** [comment]
mac教程已更新，https://github.com/monkeyWie/proxyee-down/blob/master/.guide/mac/read.md

**Comment by max-yeah** [comment]
@monkeyWie @TifosiRay 谢谢🙏！我已经成功配置好了
