### ISSUE TITLE
能否支持部署到局域网内其他机器上

### ISSUE THREAD

**Issue by yuiopt** [monkeyWie/proxyee-down#381]
是否支持本机浏览器SwitchyOmega+ 局域网内其他机器ProxyeeDown，想让Proxyee单独运行在一台linux机器上做下载服务，在同网段的mac和windows上都能通过SwitchyOmeg添加下载任务，是否可以这样配置？

**Comment by monkeyWie** [comment]
可以的，把代理设置好就行。还有要把ui模式调成浏览器

**Comment by yuiopt** [comment]
@monkeyWie 在纯命令行模式的centos下面好像运行不起来，要如何配置？
