### ISSUE TITLE
mac下jdk配置在哪？

### ISSUE THREAD

**Issue by kiok1210** [monkeyWie/proxyee-down#384]
jre配置在哪？
提示
sudo: ./jre1.8.0_162/Contents/Home/bin/java: command not found

**Comment by kiok1210** [comment]
在onedriver 下了2.5.4，里面自带，可以了

**Comment by kiok1210** [comment]
可以在start启动文件中修改

**Comment by monkeyWie** [comment]
mac已经打包好了，直接运行就行
