### ISSUE TITLE
求救!下載遊戲壓縮檔有五個被合成一個，下載好解壓縮卻又變成原本五個壓縮檔70G，到最後變成要解壓縮兩次才可以，

### ISSUE THREAD

**Issue by zaq931298** [monkeyWie/proxyee-down#386]
求救!下載遊戲壓縮檔70G有五個被合成一個，下載好解壓縮卻又變成原本五個壓縮檔，到最後變成要解壓縮兩次才可以.......到最後空間不夠.........總共變成需要210G的空間..                                                                                        版本號2.54   WIN10  64位元

**Comment by hooboor** [comment]
@zaq931298 你可以先解压合成的压缩档为五个压缩档，然后删除那个合成的压缩档，然后再解压5个压缩档，这样可以节省70G空间。

**Comment by monkeyWie** [comment]
是这样的，百度云批量下载就会打包成一个zip文件
