### ISSUE TITLE
配套的链接获取脚本基本失效

### ISSUE THREAD

**Issue by sage1717** [monkeyWie/proxyee-down#388]
### 17134.48
救命SOS

**Comment by chengchunkit** [comment]
遇到这种情况的原因是提供者的网盘被封，限制分享下载功能，这时只需将文件保存到自己的网盘下，在自己的网盘里下载即可；如果自己的账号被限速了，只须将文件再次分享，退出账后，在分享链接里进行下载，下载速度会有所提升。

**Comment by hooboor** [comment]
显示未知文件.xx，那是根本就没有获取到正确的下载地址。建议不要使用直接下载，可以使用压缩链接地址。

**Comment by monkeyWie** [comment]
是自己网盘的资源下载的话是要带cookie才行，所以最好是用浏览器触发下载然后被proxyee-down嗅探到就行
