### ISSUE TITLE
求助 128线程速度依然很慢

### ISSUE THREAD

**Issue by zwkcwn** [monkeyWie/proxyee-down#39]
按照使用教程安装的
并且也是分享出来退出账号再下载的文件
速度只有不到100k
[https://imgsa.baidu.com/forum/w%3D580/sign=e51c9cfbb8de9c82a665f9875c8080d2/204fd8afa40f4bfb8ca9e696084f78f0f6361840.jpg](url)

**Comment by monkeyWie** [comment]
没有合并下载吧，看看常见问题列表4
https://github.com/monkeyWie/proxyee-down/blob/master/README.md

**Comment by Redundant-K** [comment]
可以试试分段数50-70,我在这个分段数里面满速.
