### ISSUE TITLE
服务器异常

### ISSUE THREAD

**Issue by xigrug** [monkeyWie/proxyee-down#390]
问题
下载总是提示这个服务器异常，文件名自动识别为未知文件.XXX. 另外QQ群都满了
版本号(必要)
2.54
操作系统(必要)
win10 64位 教育版

**Comment by monkeyWie** [comment]
下载在浏览器里点，不是用分享的链接来创建下载任务

**Comment by xigrug** [comment]
但是我在浏览器点，会跳出百度云的软件！要卸载百度云才可以么，proxyee-down识别不出来

**Comment by monkeyWie** [comment]
看FAQ第一个问题
