### ISSUE TITLE
消耗CPU严重

### ISSUE THREAD

**Issue by Koy-Ren** [monkeyWie/proxyee-down#4]
* 运行的时候消耗CPU严重啊，windows平台。有什么原因吗？
* 启动后直接从5%到50%，温度直接80度。

![snipaste_2017-12-13_14-13-50](https://user-images.githubusercontent.com/30454927/33924390-d840b0fc-e010-11e7-94db-6a76a5d3a597.png)

**Comment by monkeyWie** [comment]
@Koy-Ren 
感谢反馈，是有线程空轮询的bug现在已经修复了
