### ISSUE TITLE
建议：能否增加“绕过文件保存/上传的数量限制”这样的功能

### ISSUE THREAD

**Issue by tillchen** [monkeyWie/proxyee-down#402]
首先感谢开发者！辛苦了！

建议如题，能否增加“绕过文件保存/上传的数量限制”这样的功能？如果可以增加，此项目就可完全代替会员的全部功能了。

谢谢！

**Comment by monkeyWie** [comment]
没明白“绕过文件保存/上传的数量限制”是什么意思

**Comment by tillchen** [comment]
@monkeyWie 抱歉没有写明白，我是指非会员一次性保存或上传大量文件（具体的限制数额忘记了，应是500或1000）时，会提示开通会员才可以一次性保存或上传。

**Comment by monkeyWie** [comment]
好吧 不过这个既然叫下载器肯定是只做下载不做上传的
