### ISSUE TITLE
关于下载分卷解压包的问题

### ISSUE THREAD

**Issue by wtfgfw1984** [monkeyWie/proxyee-down#43]
**首先感谢作者**
本人小白一个 基本什么都不懂 靠教程苟活

今天下载了几个分卷解压包，用了proxyeedown的合并文件功能，下载完后用了百度云解压工具
之后解压分卷，发现解压完后的文件都打不开，一开始以为软件的问题，导致文件损坏，后来折腾了一下发现是路径的问题，和软件没关系，只需将文件拖到其他地方就行，望有同样问题的小白同学周知
 
再次感谢作者

**Comment by monkeyWie** [comment]
谢谢反馈~
