### ISSUE TITLE
操作还是有点繁琐了

### ISSUE THREAD

**Issue by fanleung** [monkeyWie/proxyee-down#44]

**Comment by monkeyWie** [comment]
比如说哪里呢？

**Comment by zhongfly** [comment]
@monkeyWie 能否提供switch omega的自动切换规则，免得每次下载都需要从常用的自动切换模式(出墙代理)手动切换到 下载的代理模式上…
如果有规则，就只需要添加规则到自动切换模式中，让百度云下载自动启用本地的下载代理

**Comment by jc654123** [comment]
可以右键快速切换缓解一下

**Comment by monkeyWie** [comment]
@zhongfly 
软件设置里支持二级代理，你可以把墙的代理设置在二级代理里，然后再把墙的自动切换规则配置到下载器的情景模式里就行了

**Comment by monkeyWie** [comment]
@jc654123 
你指的是切换什么呢

**Comment by waterlogithub** [comment]
@monkeyWie 设置二级代理后，变成用浏览器下载，速度10+k...
![default](https://user-images.githubusercontent.com/22746557/35478665-3723821c-041e-11e8-8e8e-fa42d3009626.PNG)

**Comment by monkeyWie** [comment]
@waterlogithub 
应该是下载的时候走了二级代理了，以后会支持二级代理的自动切换规则
