### ISSUE TITLE
不会用

### ISSUE THREAD

**Issue by konanzheng** [monkeyWie/proxyee-down#5]
编译通过了，也启动了 但是 怎么下载啊，没有使用说明啊

**Comment by monkeyWie** [comment]
参考下https://segmentfault.com/a/1190000012345156

**Comment by akillcool** [comment]
@konanzheng 启动之后把代理设置好，在百度云里面点下载会自动跳转的。

**Comment by konanzheng** [comment]
浏览器代理工具会冲突吗？我用的chrome 浏览器，SwitchyOmega 插件。现在还是没反应

**Comment by akillcool** [comment]
@konanzheng 不会，我在Windows上用的也是Chrome+SwitchyOmega，没有任何问题。

**Comment by konanzheng** [comment]
@akillcool 我的是ubuntu ,证书也安装了。代理设置了127.0.0.1 9999



我把浏览器代理插件停用之后浏览器已经不能正常访问网页了。百度云下载按钮点击报错，应该是页面资源加载不正常

![Uploading 选区_002.png…]()

**Comment by konanzheng** [comment]
最新情况，我在switchOmega代理规则增加了 *.baidupcs.com  匹配规则 走127.0.0.1 9999 就可以了。但是怎么取消下载啊？暂停 继续之类的按钮 也没有啊

**Comment by monkeyWie** [comment]
看看下你的浏览器设置代理服务器有没有取消掉。

**Comment by monkeyWie** [comment]
@konanzheng 现在暂停功能还没做呢，新版本已经支持持久化功能了，你可以直接关掉程序，下次再打开的时候会接着下载的

**Comment by akillcool** [comment]
@konanzheng 你的证书是怎么安装的？我用ElementaryOS安装证书之后并没有啥用。。。
我在Chrome和系统上都安装了证书。

**Comment by konanzheng** [comment]
@akillcool 双击。。。。。

**Comment by monkeyWie** [comment]
@akillcool  老哥，我现在在弄ElementaryOS,公司电脑卡成狗啊，等我看看怎么安装证书

**Comment by konanzheng** [comment]
我有个想法不知道对不对啊，既然是通过代理感知下载路径的就肯定能做到手动给下载路径和远程给下载路径
所以是不是可以有下面这些功能
1. 支持局域网专门的下载机运行proxyee-down 做成服务 ,其他机器不用分别运行
1. 其他手机端、web端进行远程任务管理，增加，暂停，删除之类的

**Comment by monkeyWie** [comment]
@konanzheng 
其实现在就支持你说的第一点，关于第二点的话后期会考虑进去的，谢谢你给的建议。

**Comment by akillcool** [comment]
@konanzheng 我用SwitchyOmega给proxyee-down单独设置了一条规则，现在可以使用了。
@monkeyWie 证书应该是已经生效了。
但是全局代理打开https的链接都会有问题，后期是不是考虑支持https？

**Comment by monkeyWie** [comment]
@akillcool 是支持https的，应该是证书的问题，我现在家把ElementaryOS装下，今天在公司忙着修复bug了

**Comment by akillcool** [comment]
@monkeyWie 辛苦啦！
全局代理只在elementaryOS上面有问题，Windows上没有问题。

**Comment by TGhoul** [comment]
@monkeyWie 
![image](https://user-images.githubusercontent.com/14310807/34024386-c4cd66e4-e184-11e7-9d34-0fc447e08971.png)

连接超时:io.netty.channel.AbstractChannel$AnnotatedConnectException: Connection timed out: no further information: history.google.com/7
4.125.203.102:443
设置好代理后，点击下载就报错，和SS有冲突？我关闭了SS也报错。

**Comment by monkeyWie** [comment]
@TGhoul 
这些报错信息都是正常的，连接超时的都是被墙了的网站。
点击下载报错你是指控制台还是浏览器呢？和SS不冲突的，不过SS别设置成全局代理模式。

**Comment by TGhoul** [comment]
@monkeyWie 控制台报错，不是被墙的网站，我是下载百度云上的资源。点击下载跳转之后就直接报404了。
![image](https://user-images.githubusercontent.com/14310807/34024647-54ca8a50-e186-11e7-8e29-2f827da72c66.png)
我这样设置代理是正确的吗？

**Comment by monkeyWie** [comment]
先把自动配置脚本关了，然后能提供下404页面的的过程图片吗

**Comment by zizaipai** [comment]
浏览器兼容问题比较大

**Comment by TGhoul** [comment]
@monkeyWie 这是点击下载404的截图
![image](https://user-images.githubusercontent.com/14310807/34025213-9d182e68-e189-11e7-9610-b36ba363371b.png)

**Comment by zizaipai** [comment]
这又是啥情况啊？
![qq 20171215111028](https://user-images.githubusercontent.com/5186916/34025277-ed4b8c22-e189-11e7-9e69-c350d5e6abc3.png)

**Comment by zizaipai** [comment]
这又是啥问题啊？
![qq 20171215112213](https://user-images.githubusercontent.com/5186916/34025351-5451ce90-e18a-11e7-81ef-2fd7fc943f53.png)

**Comment by monkeyWie** [comment]
@TGhoul 
你是自己编译的版本吗？看起来这个版本有问题
这是最新的release版本你可以用这个试试
https://github.com/monkeyWie/proxyee-down/releases/tag/1.2

**Comment by zizaipai** [comment]
@monkeyWie   最新的Release版本

**Comment by TGhoul** [comment]
@monkeyWie 最新版的1.2release正常可以使用，非常感谢！很奇怪我是直接clone你的项目编译的，为什么和你的最新版release不一样？你没有提交最新的代码吗？作者可以解答一下吗？谢谢

**Comment by Koy-Ren** [comment]
@TGhoul 是不是没有编译node项目？我上回也是没编译node直接打版本就会出现这个问题

**Comment by monkeyWie** [comment]
@TGhoul 
可能是刚好你编译完后我才发的release吧。一般我发release的时候代码都会同步成最新的

**Comment by monkeyWie** [comment]
@zizaipai 
1.2版本的吗?能不能试着重现下这个bug，然后描述下过程是怎样的

**Comment by snaker95** [comment]
其他下载可以直接使用, 但是百度网盘下载还是不行, 求教怎么设置吗?

**Comment by snaker95** [comment]
服务报错, 提示dos不可用
![image](https://user-images.githubusercontent.com/19548096/34429427-e2c8ba7c-ec92-11e7-9a1e-19383033cffc.png)

**Comment by monkeyWie** [comment]
@snaker95 你是什么操作系统呢

**Comment by snaker95** [comment]
@monkeyWie 我的是macPro

**Comment by monkeyWie** [comment]
@snaker95 最新版已经支持mac了
