### ISSUE TITLE
在百度云网页看不到proxyee-down字样

### ISSUE THREAD

**Issue by joshatt** [monkeyWie/proxyee-down#50]
"在2.02+版本中，下载器配置正确之后，打开百度云页面会有如下提示"
我是chrome浏览器........一开始我用的2.03, 刚刚升级到2.1, 都没有看到上述字样. 我都是直接点击下载, 如果文件比较大, 会提示安装云管家, 我还得借助直链脚本才能激活proxyee-down

**Comment by monkeyWie** [comment]
代理没设置好

**Comment by joshatt** [comment]
但是下载挺正常啊. 代理哪一项?

**Comment by monkeyWie** [comment]
@joshatt 看教程里的设置

**Comment by monkeyWie** [comment]
你把浏览器的代理服务器设置好了，刷新页面就会加载了

**Comment by joshatt** [comment]
发现这个字样和下载无关,就是主页链接.....所以这个问题可以忽略了 hehe
发现字样能否显示有两个条件都要满足: 1是代理必须直接用这个,不能用条件跳转. 2是必须禁用tampermonkey,只禁用其中的脚本都不行

**Comment by monkeyWie** [comment]
谢谢反馈。
