### ISSUE TITLE
文件解压问题

### ISSUE THREAD

**Issue by mroctopus1997** [monkeyWie/proxyee-down#60]
合并下载，文件大小17.9G（其中有压缩包有密码），解压过程出现服务器异常之类的问题。

**Comment by monkeyWie** [comment]
请提供下软件版本号，和安装目录/main/log里的日志

**Comment by dafaWang** [comment]
@mroctopus1997 我也碰到过相同问题,我这里是因为磁盘容量不足

**Comment by davidx2014** [comment]
下载文件夹自动合并了，7-zip打开提示头部错误，有时也会直接说无法作为压缩文件打开，今早有一个文件下载回来打开直接导致系统假死，恢复过来说是I/O错误
系统win7 sp1 64bit，软件版本2.11
log文件里有很多条这样的记录：java.io.IOException: An existing connection was forcibly closed by the remote host

**Comment by monkeyWie** [comment]
@davidx2014 
用下载器里的百度云解压工具解压

**Comment by davidx2014** [comment]
可以了谢谢dalao
