### ISSUE TITLE
无法触发下载问题

### ISSUE THREAD

**Issue by chenzhuangzhu** [monkeyWie/proxyee-down#61]
在网吧下载后，证书也不用安，就能用。
但是回到家后，我下载了以后，无法触发，根据提示安装了证书以后，下载百度云的东西，为什么还是无法触发下载？

**Comment by chenzhuangzhu** [comment]
我又在虚拟机里试了下，百度网盘页面出现了prxy-down选项卡可以使用。
然后我又回到本机以后，再关闭了360以后，点击软件运行，再次安装证书，谷歌浏览器可以使用，而百度浏览器显示您的连接并不安全

**Comment by monkeyWie** [comment]
重启下百度浏览器试试看
