### ISSUE TITLE
老哥,右击图标时文字显示为框框.

### ISSUE THREAD

**Issue by Redundant-K** [monkeyWie/proxyee-down#65]
如图.
![20180127191759](https://user-images.githubusercontent.com/35866705/35471473-d3ea7bb0-0396-11e8-971e-af343902692e.png)

**Comment by monkeyWie** [comment]
是不是你系统的字符编码有换过？

**Comment by Redundant-K** [comment]
打扰了,确实是字符编码的问题,已解决,谢谢!
