### ISSUE TITLE
请问能否默认关闭全局代理？

### ISSUE THREAD

**Issue by beautifulword** [monkeyWie/proxyee-down#68]
每次打开软件都要手动关闭，有点麻烦。谢谢开发者。

**Comment by monkeyWie** [comment]
你可以在托盘那设置关闭全局代理，还有你版本号是多少？2.1的设置记录有问题，2.11修复了

**Comment by beautifulword** [comment]
今天刚更新到2.11，还没用。我晚上回去试试。谢谢开发者。

**Comment by beautifulword** [comment]
已经解决了，谢谢开发者

**Comment by beautifulword** [comment]
对了，请问能不能在下载时阻止电脑自动休眠？

**Comment by monkeyWie** [comment]
@beautifulword 
阻止休眠功能没有，你可以用系统设置不休眠吧

**Comment by monkeyWie** [comment]
@beautifulword 
嗯，以后会加上下载完自动关机功能的。这样你把休眠关了然后关掉显示器下载就好了

**Comment by a147022899** [comment]
你可以用SwitchyOmega的情景模式
这个可以下载

[百度网盘dlSwitchyOmega代理设置.zip](https://github.com/monkeyWie/proxyee-down/files/1686040/dlSwitchyOmega.zip)

**Comment by 25890** [comment]
因为我是用surge的，但是一旦浏览器用了SwitchyOmega的情景模式，会导致代理失效。请问是否可以提供surge的规则，用来代替SwitchyOmega的
