### ISSUE TITLE
请问一下有考虑加入限制下载速度的功能吗

### ISSUE THREAD

**Issue by jianchi89** [monkeyWie/proxyee-down#71]
哎 虽然有了破解就已经很不错了 但出了就肯定有很多问题要来的 比如下个版本制作者你更不更新xxxx啊 之类的问题 虽然加入限制下载速度可能对很多人有帮助吧 毕竟我上次下个东西 要1个小时然后我就去看了一个小时的电视emm 手机也没用de 网速占满了很卡 哎 可惜不是人人都100兆了 要是当年100兆打折的时候我入了该多好 嘛 撇开别的不谈 毕竟这只是我这人的想法 说不定其他人不这么认为 并且这种东西加限速应该也很难的吧 放心 不加也没啥关系 毕竟可能大家都是这样想的 有个破解就不错了

**Comment by jianchi89** [comment]
而且这个似乎是先让那些需要网的先加载 已经足够了 谢谢制作者 哎

**Comment by jc654123** [comment]
把链接数调少点不要那么贪婪，一口吃不成个胖子

**Comment by monkeyWie** [comment]
后期会考虑做限速功能的~
