### ISSUE TITLE
貌似 失效了

### ISSUE THREAD

**Issue by Lagranmoon** [monkeyWie/proxyee-down#73]
`Request URL: https://www.baidupcs.com/rest/2.0/pcs/file?method=batchdownload&app_id=250528&zipcontent=%7B%22fs_id%22%3A%5B1031145667592886%5D%7D&sign=DCb740ccc5511e5e8fedcff06b081203:WslQlQrww39L77co3QP%2BrDzpq5o%3D&uid=1637749257&time=1517369294&dp-logid=683676765285647896&dp-callid=0&vuk=1637749257&zipname=BAT%E5%A4%A7%E7%89%9B%20%E5%B8%A6%E4%BD%A0%E6%B7%B1%E5%BA%A6%E5%89%96%E6%9E%90Android%2010%E5%A4%A7%E5%BC%80%E6%BA%90%E6%A1%86%E6%9E%B6%2B.zip
Request Method: GET
Status Code: 400 Bad Request
Remote Address: 127.0.0.1:9999
Referrer Policy: no-referrer-when-downgrade
`
```json
{"error_code":31062,"error_msg":"file name is invalid","request_id":683676765285647896}
```

**Comment by monkeyWie** [comment]
改下文件名试试

**Comment by Lagranmoon** [comment]
没试了，不知道可不可以，开了个会员，最近百度查的太严了，最后感谢你为此做出的贡献啦

**Comment by monkeyWie** [comment]
@Lagranmoon 
没有失效的，群里的人用的好好的。
