### ISSUE TITLE
脚本更新失败，Firefox最新版

### ISSUE THREAD

**Issue by whthend** [monkeyWie/proxyee-down#74]
注册/更新范围为‘https://pan.baidu.com/disk/home’的 ServiceWorker 失败：脚本‘https://pan.baidu.com/disk/serviceworker.js’的 Content-Type‘text/html’不当。内容类型必须为‘text/javascript’、‘application/x-javascript’或‘application/javascript’。

**Comment by monkeyWie** [comment]
这个和下载器无关
