### ISSUE TITLE
弹不出提示框

### ISSUE THREAD

**Issue by jc654123** [monkeyWie/proxyee-down#75]
测试网址https://pan.baidu.com/s/1d5VUl4 密码: FULI

**Comment by jc654123** [comment]
怎么样都不行，可能。。。

**Comment by monkeyWie** [comment]
刚刚测试没问题，你确定代理设置好了吗，不行就存自己网盘再下载
![image](https://user-images.githubusercontent.com/13160176/35554659-7f354a44-05d7-11e8-9528-37d0819ada88.png)

**Comment by liangxyz** [comment]
我也是弹不出下载框，使用的是百分浏览器。百度页面有软件的网址
![snipaste_2018-02-02_21-17-18](https://user-images.githubusercontent.com/8108927/35735123-8052585c-085e-11e8-9d03-77db7bd3e310.png)

**Comment by liangxyz** [comment]
同时测试关闭软件，百度盘就打不开了。开启软件，百度盘可以打开，证明流量走的是软件的代理。当时就是不能弹出下载框

**Comment by monkeyWie** [comment]
弹不出下载框的参考常见问题列表11

**Comment by monkeyWie** [comment]
@jc654123 
不下载的时候可以把代理切回直连，代理只是嗅探下载请求用的。
