### ISSUE TITLE
写个创建任务的页面把

### ISSUE THREAD

**Issue by liupeng110** [monkeyWie/proxyee-down#76]
下载根本就不提示

**Comment by liupeng110** [comment]
http://127.0.0.1:9000/#/tasks   万年不变 暂无下载任务

**Comment by monkeyWie** [comment]
你不去下载哪来的任务。。

**Comment by liupeng110** [comment]
@monkeyWie  我是用油猴拿到 文件夹下载连接之后 在浏览器地址栏  回车  下载  调用的浏览器自带的  直接就是另存为那种！

**Comment by liupeng110** [comment]
@monkeyWie    我知道来提bug就不知道 在浏览器下载下？

**Comment by liupeng110** [comment]
@monkeyWie  下载器依赖浏览器弄的有点不科学啊

**Comment by monkeyWie** [comment]
@liupeng110

**Comment by jackila** [comment]
@liupeng110 你可以尝试一下 全局模式 IE浏览器 在浏览器中打开百度云盘网页，下载内容。
