### ISSUE TITLE
Chrome 显示不安全

### ISSUE THREAD

**Issue by jiyidelirin** [monkeyWie/proxyee-down#77]
前几天还用的好好的，今天突然出现这样的情况。对不起我算是电脑白痴 /w\

一开始是这样的
![qq 20180131001347](https://user-images.githubusercontent.com/20991183/35578249-76aab69c-061e-11e8-99b5-71cd4cc91d16.png)

按了下载后没反应但出现了这个
![qq 20180131001431](https://user-images.githubusercontent.com/20991183/35578354-cfbe90a0-061e-11e8-924d-ceadd3107a06.png)
![qq 20180131001456](https://user-images.githubusercontent.com/20991183/35578361-d43b7c7e-061e-11e8-9896-12e634cf540d.png)

加载了后就变成这样了 /.\
![qq 20180131001601](https://user-images.githubusercontent.com/20991183/35578399-e89614f4-061e-11e8-9f97-96f16b91fe99.png)

是我的防毒软件问题吗？还是我无意中调错了什么设定？我重新安装了证书再重启还是一样 /.\....

**Comment by monkeyWie** [comment]
@jiyidelirin 
把证书删了再重装下试试看，那个不安全的脚本提示不用管

**Comment by jiyidelirin** [comment]
@monkeyWie 
还是不行诶，和昨天一样。
你看看这有没有帮助？我加载了不安全脚本后再点下载出现的。
![qq 20180131132739](https://user-images.githubusercontent.com/20991183/35606521-a1a3aeb4-068a-11e8-9546-a29c4221edb1.png)
![qq 20180131132800](https://user-images.githubusercontent.com/20991183/35606524-a6530b4e-068a-11e8-8d25-14a0841e63de.png)

**Comment by monkeyWie** [comment]
![image](https://user-images.githubusercontent.com/13160176/35606830-0e2eebc4-068c-11e8-80e0-4b2f408e1624.png)
把这个tab里的信息也截图看看

**Comment by jiyidelirin** [comment]
@monkeyWie 
![qq 20180131145213](https://user-images.githubusercontent.com/20991183/35608945-5f9d5806-0696-11e8-9e75-720dd4501231.png)

**Comment by monkeyWie** [comment]
@jiyidelirin 
![image](https://user-images.githubusercontent.com/13160176/35613686-c837e3d4-06a7-11e8-8cee-ea46d04aa505.png)
这个怎么是http请求，这个链接是复制下出来

**Comment by jiyidelirin** [comment]
@monkeyWie 
嗯，我不清楚诶。我点下载就出现这
![image](https://user-images.githubusercontent.com/20991183/35616288-c9301b50-06af-11e8-8377-7a699fa84909.png)
![image](https://user-images.githubusercontent.com/20991183/35616317-def28a86-06af-11e8-9089-fd4d8f0d687c.png)

**Comment by monkeyWie** [comment]
保存到自己网盘下载就好
