### ISSUE TITLE
Mac下2.11版本执行出错

### ISSUE THREAD

**Issue by zsakvo** [monkeyWie/proxyee-down#78]
MacOS10.13.3  Java version "1.8.0_151"  执行后如图
<img width="1160" alt="snipaste_2018-01-31_18-47-50" src="https://user-images.githubusercontent.com/25399519/35618890-4351cd1e-06b7-11e8-8026-7f30594da3d1.png">

**Comment by lyp741** [comment]
没有配置JAVA_HOME环境变量

**Comment by zsakvo** [comment]
可以了 谢谢
