### ISSUE TITLE
为什么下载ISO文件HASH值全部变了，MD5,SHA1,CRC，全部变了

### ISSUE THREAD

**Issue by freesd** [monkeyWie/proxyee-down#79]
这样没法检验文件下载的是否完整了，不知道是我的个例还是都这样。

**Comment by monkeyWie** [comment]
下载器什么版本，单文件下载还是批量下载？

**Comment by freesd** [comment]
@monkeyWie 就是最新版2.1.1，今天又下载了几个文件，都是单文件下载，都是出现校验值都变了，不是原来的了

**Comment by monkeyWie** [comment]
你有源文件的MD5吗

**Comment by freesd** [comment]
@monkeyWie 换官方的百度云下载下来，与下载站给的原来的MD5一致，不知道是什么原因导致的

**Comment by monkeyWie** [comment]
分享个链接给我试试，还有源文件的MD5
