### ISSUE TITLE
proxyee-down 编译失败

### ISSUE THREAD

**Issue by BenjaminGao** [monkeyWie/proxyee-down#8]
```
node -v
v8.9.1

java version "9.0.1"
Java(TM) SE Runtime Environment (build 9.0.1+11)
Java HotSpot(TM) 64-Bit Server VM (build 9.0.1+11, mixed mode)

 mvn -v
Apache Maven 3.5.2 (138edd61fd100ec658bfa2d307c43b76940a5d7d; 2017-10-18T15:58:13+08:00)
Maven home: /usr/local/Cellar/maven/3.5.2/libexec
Java version: 9.0.1, vendor: Oracle Corporation
Java home: /Library/Java/JavaVirtualMachines/jdk-9.0.1.jdk/Contents/Home
Default locale: zh_CN, platform encoding: UTF-8
OS name: "mac os x", version: "10.13", arch: "x86_64", family: "mac"
```

`proxyee`依赖编译成功
`cd proxyee-down/view`
`npm install` ✅
`npm run build` ✅
`cd ..`
`mvn clean package` ❌

```
[INFO] -------------------------------------------------------------
[WARNING] COMPILATION WARNING :
[INFO] -------------------------------------------------------------
[WARNING] /Users/benjamin/proxyee-down/src/main/java/lee/study/down/HttpDownServer.java: /Users/benjamin/proxyee-down/src/main/java/lee/study/down/HttpDownServer.java使用了未经检查或不安全的操作。
[WARNING] /Users/benjamin/proxyee-down/src/main/java/lee/study/down/HttpDownServer.java: 有关详细信息, 请使用 -Xlint:unchecked 重新编译。
[INFO] 2 warnings
[INFO] -------------------------------------------------------------
[INFO] -------------------------------------------------------------
[ERROR] COMPILATION ERROR :
[INFO] -------------------------------------------------------------
[ERROR] /Users/benjamin/proxyee-down/src/main/java/lee/study/down/util/HttpDownUtil.java:[131,56] 找不到符号
  符号:   变量 clientSslCtx
  位置: 类 lee.study.proxyee.server.HttpProxyServer
[ERROR] /Users/benjamin/proxyee-down/src/main/java/lee/study/down/hanndle/HttpDownInitializer.java:[44,44] 找不到符号
  符号:   变量 clientSslCtx
  位置: 类 lee.study.proxyee.server.HttpProxyServer
[INFO] 2 errors
[INFO] -------------------------------------------------------------
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 2.963 s
[INFO] Finished at: 2017-12-25T11:53:07+08:00
[INFO] Final Memory: 27M/90M
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal org.apache.maven.plugins:maven-compiler-plugin:3.1:compile (default-compile) on project proxyee-down: Compilation failure: Compilation failure:
[ERROR] /Users/benjamin/proxyee-down/src/main/java/lee/study/down/util/HttpDownUtil.java:[131,56] 找不到符号
[ERROR]   符号:   变量 clientSslCtx
[ERROR]   位置: 类 lee.study.proxyee.server.HttpProxyServer
[ERROR] /Users/benjamin/proxyee-down/src/main/java/lee/study/down/hanndle/HttpDownInitializer.java:[44,44] 找不到符号
[ERROR]   符号:   变量 clientSslCtx
[ERROR]   位置: 类 lee.study.proxyee.server.HttpProxyServer
[ERROR] -> [Help 1]
[ERROR]
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR]
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/MojoFailureException
```

**Comment by monkeyWie** [comment]
@BenjaminGao 切换到dev分支去编译，master还没merge

**Comment by BenjaminGao** [comment]
@monkeyWie 不管是 `dev` 或 `v1.4` 都报错，错误跟上面的一样。

**Comment by monkeyWie** [comment]
@BenjaminGao 加上-e把错误堆栈打印出来看看吧

**Comment by BenjaminGao** [comment]
@monkeyWie 切换到 dev 分支后编译过去了，我昨天切换错了。现在运行 `java -jar proxyee-down-1.3-SNAPSHOT.jar 9999` 出现这个
![snipaste_2017-12-26_13-44-09](https://user-images.githubusercontent.com/16028320/34348056-e2e7946c-ea42-11e7-84f0-bd91811c3ff0.png)
，而且浏览器里输入 `localhost:9999` 是这样的
![snipaste_2017-12-26_13-43-14](https://user-images.githubusercontent.com/16028320/34348040-bf664308-ea42-11e7-9c98-f5df3ee7082d.png)

**Comment by monkeyWie** [comment]
@BenjaminGao 
切换到1.4分支吧

**Comment by BenjaminGao** [comment]
好了，谢谢。可以关闭这个 issus 了。

**Comment by BenjaminGao** [comment]
![2017-12-27 8 40 41](https://user-images.githubusercontent.com/16028320/34381918-8cdd7140-eb46-11e7-8803-d09caeeaadac.png)

**Comment by monkeyWie** [comment]
@BenjaminGao 你看看你用代理访问的时候https证书是不是这样的
![image](https://user-images.githubusercontent.com/13160176/34384534-b0f54bb4-eb57-11e7-93f8-e0732982da69.png)

**Comment by BenjaminGao** [comment]
@monkeyWie 当然，
![2017-12-28 9 12 56](https://user-images.githubusercontent.com/16028320/34397251-7085c25e-ebaf-11e7-936c-a087c75d1581.png)
另外问一句，这个小软件会影响到终端吗？（问题有点白痴）我不知道你用不用 mac，如果 _不用_ 下边的话就不用看了：
我昨天在用 brew cask 更新软件的时候发现下载速度非常的慢，跟没挂代理一样。但是我确实把终端挂上代理了，以前也没出现过这情况。我现在必须要在用户根目录下创建 `.curlrc` 文件才可以用代理。很奇怪，我之所以这样问是我最近半个月就安装了这一个软件，而且也没有更改系统任何设置，所以才问问

**Comment by monkeyWie** [comment]
@BenjaminGao 
现在还是不能弹出下载页面吗，是不是和别的chrome插件冲突了。
mac没用过，但如果你不是配置的全局http代理，只是chrome配置了http代理的话是不会影响到其他应用的。

**Comment by BenjaminGao** [comment]
@monkeyWie 我百度云插件就一个，我已经关了，但是仍然不行。点『下载』的时候瞬间出现『获取链接』几个字，然后就显示『启动百度云客户端』。那几个字太快了，我不知道这几个字是本来就有还是插件的字。如果是『获取百度云大文件』这个脚本的字的话，那很可能是脚本问题。

![2017-12-28 12 03 28](https://user-images.githubusercontent.com/16028320/34399966-694ea894-ebc7-11e7-868e-5af3c71afc83.png)

![2017-12-28 12 05 37](https://user-images.githubusercontent.com/16028320/34399969-78747c0e-ebc7-11e7-951c-d25d24a238e0.png)

![2017-12-28 11 58 31](https://user-images.githubusercontent.com/16028320/34399873-949c6730-ebc6-11e7-90a9-731e53640893.png)

brew 的事情可以算作解决了，我用了替代方案，起码速度是没什么问题了。但是还是有疑问，在找资料。

**Comment by monkeyWie** [comment]
用chrome看看响应，有没有加载到hookjs
![image](https://user-images.githubusercontent.com/13160176/34413271-38c145fa-ec1d-11e7-8b7b-01ac56f446e8.png)

**Comment by BenjaminGao** [comment]
@monkeyWie 加载了
![2017-12-29 11 45 52](https://user-images.githubusercontent.com/16028320/34429719-d89c8c0a-ec96-11e7-88bc-90050cf8a84e.png)

**Comment by monkeyWie** [comment]
@BenjaminGao 
发现了，MAC上这段js失效，正在解决此问题
你先下载小点的文件(<500M)，应该没问题，可以弹出下载页面。

**Comment by monkeyWie** [comment]
@BenjaminGao 
dev分支代码已修复MAC上的bug

**Comment by BenjaminGao** [comment]
@monkeyWie 新的问题😂 ，一直显示合并文件中，而且 shell 里报错。如果结束进程，再次重新运行
```shell
java -jar proxyee-down-1.5.jar 9999
```
这个命令，浏览器新建标签页 `http://127.0.0.1:9000/#/` 仍然会显示 __合并文件中__ 。此时 `shell` 里就会报错，报错内容一样。
这个文件下载的时候选择的分块是30个。
![snipaste_2017-12-30_21-48-18](https://user-images.githubusercontent.com/16028320/34454696-97e4da1c-edab-11e7-96b9-f20fe5ca803e.png)
![snipaste_2017-12-30_21-50-49](https://user-images.githubusercontent.com/16028320/34454698-9cf8a0a6-edab-11e7-878c-899c5cef07d6.png)

**Comment by BenjaminGao** [comment]
@monkeyWie 再有，在网盘里点击 __下载__ 的时候，这直接在改标签页（网盘标签页）里显示 `http://127.0.0.1:9000/#/` 网址的内容，可以改成不要覆盖这个标签页吗╮(╯_╰)╭，点击返回键很麻烦啊。

**Comment by monkeyWie** [comment]
@BenjaminGao 
因为浏览器安全策略问题，不是一个域名新开一个tab的话会被chrome拦截成弹窗的，所以就只能这样了。
那个报错的问题是不是和你jdk版本有关系啊，你是1.9?

**Comment by BenjaminGao** [comment]
@monkeyWie 不是啊，是 `java8`。你不是说建议我换 `java8` 么，所以我一直在用 `java8`。
![snipaste_2017-12-31_11-19-00](https://user-images.githubusercontent.com/16028320/34458876-25267748-ee1d-11e7-99ed-0b614016fd1d.png)

> 不是一个域名新开一个tab的话会被chrome弹窗拦截的

的话，那就没必要在运行 `java -jar ...` 的那个命令后在浏览器弹出 `view` 那个标签页了，反正也用不上，因为点了 __下载__ 还会出现，建议撤销。

**Comment by monkeyWie** [comment]
@BenjaminGao 因为改成了托盘很多小白不知道软件运行了没运行，看不到效果，所以启动还是会弹出浏览器页面的，以后会考虑换成首次启动的引导页面

**Comment by BenjaminGao** [comment]
@monkeyWie 合并文件问题如何解决

**Comment by monkeyWie** [comment]
@BenjaminGao 
你这个还有详细点的log吗，下个版本会去掉文件合并的，直接单文件下载

**Comment by BenjaminGao** [comment]
@monkeyWie 终端就这么几行 log，我也不知道上哪里看其他 log 啊。我刚才把最新的 dev 编译了一下，，下载文件正常了。现在又有新 bug，很明显是各个文件名的右侧超了。
![2018-01-03 4 02 17](https://user-images.githubusercontent.com/16028320/34513597-f6ee9bce-f0a3-11e7-95f1-81135fd86408.png)
![2018-01-03 3 56 31](https://user-images.githubusercontent.com/16028320/34512879-06b25e14-f0a0-11e7-87fa-ca54bec34440.png)
![2018-01-03 4 16 53](https://user-images.githubusercontent.com/16028320/34513532-a859c4ca-f0a3-11e7-8963-b76d04e60ff1.png)

**Comment by monkeyWie** [comment]
@BenjaminGao 
UI的问题以后来优化吧，我前端小白~
