### ISSUE TITLE
下载为红色的时候就再也下载不动了

### ISSUE THREAD

**Issue by 970205011** [monkeyWie/proxyee-down#87]
就算暂停然后继续下载都不能解决，只能重新下载。能不能加入重新获取链接的功能[
![1](https://user-images.githubusercontent.com/33717599/35735353-623cd45e-085f-11e8-8116-f7095e4c2ad6.png)
](url)

**Comment by monkeyWie** [comment]
现在百度网盘单文件下载时间久了会链接失效，目前最好是用批量下载的方式来下载，下个版本有刷新下载链接继续下载的功能，敬请期待。
