### ISSUE TITLE
SwitchyOmega的自动切换功能使用测试

### ISSUE THREAD

**Issue by liangxyz** [monkeyWie/proxyee-down#88]
刚刚测试楼主的程序，我按照教程，创建了程序的情景模式。不过在最后一步的时候，我使用的是自动切换情景模式。请看下图：
![image](https://user-images.githubusercontent.com/8108927/35735695-997d39b2-0860-11e8-98c1-23c9f514746e.png)
![image](https://user-images.githubusercontent.com/8108927/35735709-a32f5c42-0860-11e8-9f85-6658adf990aa.png)
请注意，设置代理网址的时候，要写*.baidupcs.com。否则是不会弹出下载框的。我最开始用的是*.baidu.com，就不会弹出下载框。
按照我这样的设置，该翻墙的走翻墙，该直连的直连，只有在下载百度文件的时候，才会走软件的代理并弹出下载框。现在唯一的疑问就是百度网盘所有的下载地址都是baidupcs.com这个域名下面的吗？是的话建议楼主的安装教程最后一步改成我这样的更加方便！

**Comment by monkeyWie** [comment]
下个版本会出专门针对百度云下载的PAC文件，谢谢测试~
