### ISSUE TITLE
合并下载BUG

### ISSUE THREAD

**Issue by MegumiQ** [monkeyWie/proxyee-down#89]
因为下载单个文件是被限速了10kb的，所以就找了一个空文件夹一起合并下载，速度的确达到满速。
但是，合并下载好后的压缩文件不完整。例如：合并下载了一个12GB的文件，打开压缩文件后发现里面的文件只有7GB，并没有下载完整。
刚才我又合并下载了一个3G的文件倒是没有问题。
还有就是，我单个下载文件的时候达到满速时，其他网页因为网速被下载器占用所以打开网页很慢，我觉得很正常。但是，当我使用合并下载时网速被占满时，其他网页好像并没有受到什么影响一样，可以正常浏览网页、视频，感觉有点奇怪，但同样合并下载的压缩文件正确的显示着文件本来的大小，但是打开后准备解压时却发现里面的文件大小比压缩文件的大小 小很多。
还有就是合并下载刚开始几秒的时候，网速都超越我套餐本来的网速了......
![5pxpjcdl sr iw7l5b571](https://user-images.githubusercontent.com/36076659/35739093-81910fda-086b-11e8-838f-cf7812f0a64d.png)
![h_yx e bc l82 yzydma7s4](https://user-images.githubusercontent.com/36076659/35739104-8766f9f6-086b-11e8-9813-cf6de9145303.png)

**Comment by monkeyWie** [comment]
用下载器里的百度云解压工具解压
