### ISSUE TITLE
下载多文件或者压缩包后解压zip文件提示压缩文件夹无效

### ISSUE THREAD

**Issue by kibf** [monkeyWie/proxyee-down#90]
![snipaste_20180202_123212](https://user-images.githubusercontent.com/7852480/35740947-27a78a90-0815-11e8-9293-e1cdf40d5d33.png)

**Comment by monkeyWie** [comment]
用下载器里的百度云解压工具解压

**Comment by kibf** [comment]
用那个工具解压出来文件不完整的

**Comment by monkeyWie** [comment]
@kibf 
下载器是什么版本的

**Comment by kibf** [comment]
最新版

**Comment by monkeyWie** [comment]
能描述下用下载器自带的解压工具解压出来的情况吗？不完整是什么情况

**Comment by kibf** [comment]
下载一个文件显示5g 解压完只有1g

**Comment by monkeyWie** [comment]
proxyee-down里的解压工具解压的吗，有没有提示解压成功或者是服务器异常之类的消息

**Comment by kibf** [comment]
就是proxyee-down里面的解压工具 全部都是提示解压成功 如果用7zip解压就提示crc校验错误

**Comment by monkeyWie** [comment]
解压完只有1G？里面有几个文件啊，解压出来了几个文件

**Comment by kibf** [comment]
一个文件夹 里面只有一个5g的视频文件 我是选了下载文件夹 然后下载下来的压缩包也是显示5g 解压出来才1g

**Comment by monkeyWie** [comment]
用新版本解压看看，有进度条显示
