### ISSUE TITLE
批量下载问题

### ISSUE THREAD

**Issue by VincentZhang701** [monkeyWie/proxyee-down#92]
批量下载完文件后缀为zip，用7z无法打开，但把它改为rar即可正常打开，但可以看到文件都是两个，如图

![screenshot 2](https://user-images.githubusercontent.com/34201579/35765876-46d343e8-0908-11e8-9b66-09d72275ccc2.png)
希望修正。

**Comment by monkeyWie** [comment]
用下载器自带的百度云解压工具解压
