### ISSUE TITLE
bash: npm: command not found

### ISSUE THREAD

**Issue by lindichao** [monkeyWie/proxyee-down#93]
大神您好！使用Gentoo Linux安装时，按操作部骤cd proxyee-down/ui/view，然后npm install，却被提示bash: npm: command not found. 即使emerge nodejs也似乎不见效，目前正在重新emerge net-libs/nodejs，望指明解决思路。

**Comment by monkeyWie** [comment]
node.js环境没装好吧

**Comment by lindichao** [comment]
实在搞不掂了，打算重刷成FreeBSD，请问能在Unix下编译么。

**Comment by monkeyWie** [comment]
可以啊，都是跨平台的
