### ISSUE TITLE
用SwitchyOmega自动切换不成功

### ISSUE THREAD

**Issue by brucmao** [monkeyWie/proxyee-down#94]
SwitchyOmega 设置了匹配到baidu.com就切换到proxy down下载模式，但是点击下载会被chrono-download-manager 扩展接管，只有手动切换到该模式，才会调用proxy down下载。
![snipaste20180203_203331.bmp](https://i.loli.net/2018/02/03/5a75ac66c9595.bmp)

**Comment by monkeyWie** [comment]
可以参考https://github.com/monkeyWie/proxyee-down/issues/88
