### ISSUE TITLE
几点建议

### ISSUE THREAD

**Issue by AnzOOCH** [monkeyWie/proxyee-down#95]
最好添加“打开文件”和“打开文件夹”按钮。
任务列表直接显示速度，而不是需要先点一下任务。
任务圆形进度条很好看，但是在大批量下载时显得臃肿，建议添加列表试图。
如果有任务全部完成后自动关机就好了。
如果有下载速度限制就好了，不过似乎用其他软件配合也可以做到，倒不是非常必要。
对于批量下载的文件，您设计的百度云解压工具很实用，如果能够在任务列表里面，直接在已完成任务的后面添加“批量下载解压……”按钮的话就更方便了，也能防止某些人眼瞎找不到工具骂娘（滑稽）。

Pan#dow#nload已经挂了，原先它还健在的时候杂七杂八功能挺丰富的，我还定期交党费，不过现在查得严，您的插件只要能做好下载就行了，我也会经常给您交党费的（滑稽）。

如果技术上做不到就算了，我也不懂编程，甚至注册Git都用了半天。。。

**Comment by monkeyWie** [comment]
@AnzOOCH 
1.任务列表直接显示下载速度加上，我觉得太丑影响了UI的整洁性所以就没加上
2.列表视图后期后考虑加入
3.新版本会加入下载完自动关机
4.下载限速后期考虑加入
5.新版本对于百度云下载的可以勾选自动解压，下载完成后会自动进行解压，而且解压进度条也做了。

谢谢你的建议，软件会越来越完善的。
