### ISSUE TITLE
【求助】总是调用浏览器内置下载

### ISSUE THREAD

**Issue by player2017** [monkeyWie/proxyee-down#97]
我昨天还用的好好的，今天总是变成浏览器内置下载了（右下角有软件托盘图标），未修改任何配置。
我chrome、opera都试过，证书、端口也检查过，idm、百度盘客户端也都卸载了，proxyee-down是最新版64位（出问题后我又重新下载了，解压，运行，安装证书），请问有啥办法吗？

补充一下，我昨天正常用的时候也要配合油猴的度盘大文件破解插件才能用的，我看proxyee-down内置了这些插件，但似乎没起作用。

**Comment by monkeyWie** [comment]
代理没有设置好

**Comment by player2017** [comment]
可以了，谢谢。😄
