### ISSUE TITLE
[界面]下载任务列表的问题

### ISSUE THREAD

**Issue by LamGC** [monkeyWie/proxyee-down#98]
Chrome 63.0.x  Win10  Proxyee-Down2.11
Chrome在非最大化情况下会导致网页界面布局出问题,如图:
![情况截图](https://user-images.githubusercontent.com/16975255/35774915-1955cafc-09b8-11e8-9487-03a4fc32b383.png)

**Comment by LamGC** [comment]
但是左右两侧都有很多空间可以移过去,我觉得把贴到左侧然后适应到右侧会不会好点呢?
![左右两侧的空间很足](https://user-images.githubusercontent.com/16975255/35774926-7beaccbc-09b8-11e8-9551-80665a3f50f8.png)

**Comment by monkeyWie** [comment]
@LamGC 
UI问题需要前端大佬介入。

**Comment by LamGC** [comment]
哦哦,幸苦了

**Comment by monkeyWie** [comment]
@LamGC 
我前端太渣，还不会响应式布局 - -

**Comment by yongqingxie** [comment]
@monkeyWie  响应式布局可以使用bootstrap

**Comment by xiaoliu2012** [comment]
可否考虑改成列表形式呢，节省空间还直观

**Comment by monkeyWie** [comment]
可以升级到2.5
