### ISSUE TITLE
下载微云文件时突然没有速度

### ISSUE THREAD

**Issue by senayuki** [monkeyWie/proxyee-down#99]
![image](https://user-images.githubusercontent.com/27473098/35804258-fd995e28-0ab1-11e8-8ddc-9246f60ec211.png)
暂停之后重开才行，不知道发生了什么，多个微云文件都是如此

**Comment by senayuki** [comment]
没有下载失败，只是单纯不走字，版本是2.1.1

**Comment by monkeyWie** [comment]
不走字是什么。

**Comment by senayuki** [comment]
没有速度，百分数也不走，任务管理器看也没流量，暂停重开就好，感觉是多线程都掉了不像是cookies过期？
